import type { ToolLocaleContent } from '../../../types';
import { bibliography } from '../bibliography';
import type { RenterInsuranceCoverageGapCalculatorUI } from '../ui';
export const ui: RenterInsuranceCoverageGapCalculatorUI = {
  labelPolicyLimit: 'Eşya teminat limiti', labelDeductible: 'Muafiyet', labelSampleLoss: 'Örnek hasar', labelCurrency: 'Para birimi', labelApproximateRates: 'Dönüşüm, canlı kurlar yerine yaklaşık planlama katsayılarını kullanır.', labelPolicyBoundary: 'Poliçe sınırı', labelSetLimit: 'Sınırı belirle', labelPolicyBoundaryHint: 'Poliçenizdeki eşya tutarını kullanın ve ardından olası bir kaybı deneyin.', labelInventory: 'Yenileme envanteri', labelInventoryHint: 'Her kategoride her şeyi bugün yenilemenin maliyetini tahmin edin.', labelPolicyLimitHelp: 'Bina limitini değil, poliçedeki eşya teminat limitini kullanın.', labelDeductibleHelp: 'Eşya hasarı için geçerli muafiyeti girin.', labelSampleLossHelp: 'Yalnızca açık bulunduğunda örnek bir hasar senaryosu göstermek için kullanılır.', labelTotalContents: 'Tahmini eşya değeri', labelCoverageGap: 'Olası teminat açığı', labelCoverageRatio: 'Tahmini teminat oranı', labelEstimatedPayout: 'Örnek tazminat', labelOutOfPocket: 'Örnek cepten ödeme', labelStatus: 'Teminat değerlendirmesi', labelStatusSafe: 'Limit envanteri karşılıyor', labelStatusReview: 'Küçük açığı incele', labelStatusExposed: 'Eşyalar eksik sigortalı', labelStatusSafeText: 'Girdiğiniz eşya limiti en az yenileme envanteri kadar. Özel eşyalar için ayrı limitleri kontrol edin.', labelStatusReviewText: 'Limit envantere yakın, ancak küçük bir açık var. Pahalı eşyaları ve yeni alışverişleri yeniden kontrol edin.', labelStatusExposedText: 'Limit envanter tahmininin altında. Tam kayıp durumunda poliçeye güvenmeden önce poliçeyi inceleyin.', labelLargestCategories: 'En büyük envanter kategorileri', labelCoverageLine: 'Poliçe limiti', labelReplacementValue: 'Yenileme değeri', labelLimitMarker: 'Limit işareti', labelLossScenario: 'Kayıp senaryosu', labelIllustrativePayout: 'Yalnızca örnektir: oransal tazminat maddesi poliçeniz için geçerli olmayabilir.', labelReset: 'Örneği sıfırla', labelCopy: 'Özeti kopyala', labelCopied: 'Özet kopyalandı', labelCopyFailed: 'Sonucu elle kopyalayın', labelInvalidInput: 'Vurgulanan değeri kontrol edin', labelMethodTitle: 'Bu tahmin nasıl çalışır', labelMethodText: 'Araç kategori tahminlerinizi toplar ve eşya limitiyle karşılaştırır. Açık, bu değerler arasındaki pozitif farktır. Örnek tazminat, teminat oranını kayıp senaryosuna uygular ve muafiyeti çıkarır. Bu bir planlama modelidir, hasar ödemesi tahmini değildir. Poliçenizde eşya alt limitleri, yeni değer kuralları, istisnalar, ilk risk teminatı veya eksik sigorta için farklı bir uygulama bulunabilir.', labelPrivacyNote: 'Envanteriniz bu tarayıcıda kalır. Hesap, yükleme veya sunucu hesabı gerekmez.', labelAmountPlaceholder: '0,00', labelCategoryFurniture: 'Mobilya ve dekorasyon', labelCategoryElectronics: 'Elektronik', labelCategoryClothing: 'Giyim ve ayakkabı', labelCategoryKitchen: 'Mutfak ve cihazlar', labelCategoryPersonal: 'Kişisel eşyalar', labelCategoryOther: 'Diğer eşyalar',
};
const slug = 'kiraci-esya-sigortasi-teminat-acigi-hesaplayici';
const title = 'Kiracı eşya sigortası teminat açığı hesaplayıcısı';
const description = 'Kiracı sigortanızdaki eşya limitinin eşyalarınızın yenileme değerine ulaşıp ulaşmadığını tahmin edin. Envanteri, poliçe limitini, muafiyeti ve örnek hasarı tarayıcıda karşılaştırın.';
const faq = [
  { question: 'Bu kiracı sigortası hesaplayıcısı neyi ölçer?', answer: 'Girdiğiniz ev eşyası yenileme değerlerini toplar ve poliçe eşya limitiyle karşılaştırır. Fark, limit dışında kalabilecek tutarın planlama tahminidir.' },
  { question: 'Envanter için hangi değeri kullanmalıyım?', answer: 'Mobilya, elektronik, giyim, cihaz ve kişisel eşyaların güncel ve gerçekçi yenileme maliyetini kullanın. Poliçenizin istediği değerleme temelini kontrol edin.' },
  { question: 'Sonuç eksik sigortayı kanıtlar mı?', answer: 'Hayır. Sonuç envantere, poliçe metnine ve değerleme varsayımlarına bağlıdır. Alt limitler, istisnalar ve eksik sigorta maddeleri hasarı değiştirebilir.' },
  { question: 'Hesaplayıcı neden örnek tazminat gösteriyor?', answer: 'Girdiğiniz kayıp için basit bir oransal modelin muafiyet sonrasındaki sonucunu gösterir. Sigortacının gerçekte ne ödeyeceğini öngörmez.' },
  { question: 'Ev sahibinin sabit eşyalarını eklemeli miyim?', answer: 'Poliçenizde eşya teminatına girenleri ekleyin. Sorumluluk, bina, sabit donanım ve eşyalar ayrı bölümler olabilir.' },
];
const howTo = [
  { name: 'Yenileme envanteri oluşturun', text: 'Her odayı dolaşın ve eşyaları bugün yenilemenin maliyetini girin. En yüksek değerleri görünür tutmak için altı kategori kullanın.' },
  { name: 'Eşya limitini girin', text: 'Poliçe veya teklifteki eşya sigorta bedelini kopyalayın. Bina ya da sorumluluk limitini kullanmayın.' },
  { name: 'Muafiyet ve kaybı ekleyin', text: 'Eşya hasarlarında geçerli muafiyeti ve örnek kayıp tutarını girerek olası cepten ödemeyi görün.' },
  { name: 'Karar sınırını inceleyin', text: 'Açık oluşursa pahalı eşyaları, alt limitleri, değerli eşyaları ve yeni alışverişleri sigortacı veya broker ile kontrol edin.' },
];
export const content: ToolLocaleContent<RenterInsuranceCoverageGapCalculatorUI> = { slug, title, description, ui, seo: [
  { type: 'title', text: 'Limiti eşyalarınızın değeriyle karşılaştırın', level: 2 },
  { type: 'paragraph', html: '<p>Kiralık ev eşyası sigortası, limit oda oda çıkarılan envanter yerine yuvarlak bir tutarla seçildiğinde kolayca yetersiz kalır. Bu hesaplayıcı kendi yenileme tahminlerinizi görünür bir teminat sınırına dönüştürür.</p>' },
  { type: 'title', text: 'Hesaplamadan önce toplanacaklar', level: 2 },
  { type: 'list', items: ['Mobilya, elektronik, giyim, cihaz ve kişisel eşyalar için yenileme tahmini.', 'Bina ve sorumluluktan ayrı poliçe eşya limiti.', 'Eşya hasarında uygulanan muafiyet.', 'Örnek tazminatı incelemek için gerçekçi bir kayıp tutarı.'] },
  { type: 'title', text: 'Teminat açığını nasıl okuyabilirsiniz', level: 2 },
  { type: 'paragraph', html: '<p>Açık, limitin üzerindeki eşya değeridir. Sıfır açık varsayımlarınıza göre iki toplamın buluştuğunu gösterir; her eşyanın teminat altında olduğunu doğrulamaz. Pozitif açık, değerleme temelini, alt limitleri, istisnaları ve eksik sigorta maddesini incelemek için uyarıdır.</p>' },
  { type: 'table', headers: ['İşaret', 'Ne anlatır', 'Sonraki yararlı adım'], rows: [['Limit envanteri karşılıyor', 'Girilen limit en az yenileme toplamına ulaşıyor.', 'Değerli eşyaları, alt limitleri ve istisnaları kontrol edin.'], ['Küçük açığı incele', 'Limit yakın, ancak yeni alışverişler veya yuvarlama önemli olabilir.', 'En büyük kategorileri yeniden kontrol edin ve poliçeyi güncelleyin.'], ['Eşyalar eksik sigortalı', 'Girilen limit yenileme toplamının belirgin biçimde altında.', 'Yeni teklif isteyin veya eksik sigorta uygulamasını netleştirin.']] },
  { type: 'title', text: 'Tahminin sınırları', level: 2 },
  { type: 'paragraph', html: '<p>Bu araç poliçeyi okumaz, hasarın teminat altında olup olmadığına karar vermez ve bağlayıcı bir tazminat hesaplamaz. Senaryo basit bir oransal model kullanır ve muafiyeti çıkarır. Gerçek poliçelerde farklı maddeler, limitler, değerleme kuralları ve istisnalar olabilir.</p>' },
  { type: 'tip', title: 'Belge saklama önerisi', html: '<p>Değerli eşyalar için faturaları, fotoğrafları ve tarihli bir envanteri saklayın. Financial Ombudsman Service, tam yenileme maliyetinin hesaplanmamasının neden eksik sigortaya yol açabildiğini açıklar; İspanya sigorta sözleşmesi kanunu sigorta bedelini azami tazminat olarak tanımlar ve poliçe aksini söylemiyorsa oransal kural öngörür.</p>' },
], faq, bibliography, howTo, schemas: [
  { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) },
  { '@context': 'https://schema.org', '@type': 'HowTo', name: title, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) },
  { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'TRY' } },
] };
