import { bibliography } from '../bibliography';
import type { WithContext, FAQPage, HowTo, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { InflationPurchasingPowerUI } from '../ui';

const title = 'Calculadora de inflación y poder adquisitivo en el tiempo';
const description = 'Descubre cómo una hipótesis de inflación anual cambia el importe necesario para mantener el poder adquisitivo y el valor real del dinero.';
const ui: InflationPurchasingPowerUI = {
  amountLabel: 'Importe inicial', amountHelp: 'Usa una moneda y mantenla en todo el cálculo', inflationLabel: 'Inflación anual (%)', inflationHelp: 'Una hipótesis de escenario, no una predicción', yearsLabel: 'Horizonte temporal (años)', yearsHelp: 'Elige entre 1 y 80 años', cashFlowLabel: 'Flujo de caja anual', cashFlowHelp: 'Se añade al saldo o se resta de él cada año', cashFlowModeLabel: 'Escenario de flujo', noCashFlowOption: 'Sin flujo recurrente', contributionOption: 'Añadir cada año', withdrawalOption: 'Retirar cada año', costEquivalentLabel: 'Coste equivalente final', realValueLabel: 'Valor final en dinero de hoy', nominalBalanceLabel: 'Saldo nominal final', purchasingPowerLossLabel: 'Poder adquisitivo perdido', todayLabel: 'Hoy', endLabel: 'Fin del horizonte', costLineLabel: 'Coste para mantener la misma cesta', realLineLabel: 'Poder de compra del dinero sin cambios', balanceLineLabel: 'Saldo del escenario en dinero de hoy', chartDescription: 'Línea temporal de inflación con costes crecientes, poder de compra decreciente y saldo del escenario', chartNote: 'Cada línea se compara con el importe inicial', milestoneTitle: 'Hitos en la misma moneda', yearHeader: 'Año', costHeader: 'Coste equivalente', realHeader: 'Dinero sin cambios', balanceHeader: 'Saldo real', methodTitle: 'Cómo funciona la línea temporal', methodText: 'El coste equivalente es el importe inicial multiplicado por (1 + inflación anual) elevado al número de años. El valor del dinero sin cambios es el importe inicial dividido por ese mismo factor. Una aportación se suma al final de cada año y una retirada se resta, sin permitir que el saldo baje de cero.', limitationText: 'Es un modelo de escenarios transparente, no una consulta histórica del IPC, una previsión de rentabilidad ni asesoramiento financiero personal. Tu cesta de consumo puede diferir de un índice de precios publicado y la inflación real puede cambiar cada año.', emptyMessage: 'Introduce un importe positivo, una tasa superior a -100 %, un número entero de años de 1 a 80 y un flujo no negativo.', contributionSummary: 'La línea discontinua muestra el valor actual del saldo después de las aportaciones recurrentes, sin incluir rentabilidad de inversión.', withdrawalSummary: 'La línea discontinua muestra el valor actual del saldo después de las retiradas recurrentes, sin incluir rentabilidad de inversión.', noCashFlowSummary: 'Las líneas continuas aíslan la inflación: una muestra el coste futuro de la misma cesta y la otra lo que puede comprar el dinero sin cambios.', depletionWarning: 'El escenario de retiradas llega a cero en el año {year}; los años posteriores permanecen en cero.', scenarioNote: 'Solo escenario', currencyHint: 'La misma moneda que el importe inicial', yearsSuffix: 'años', amountSuffix: 'en la misma moneda que tu importe inicial',
};
const faq = [
  { question: '¿Cómo reduce la inflación el poder adquisitivo?', answer: 'Cuando sube el nivel general de precios, la misma cantidad compra menos bienes y servicios. La calculadora muestra ese efecto dividiendo el dinero sin cambios por el factor de inflación acumulada.' },
  { question: '¿Qué diferencia hay entre coste equivalente y valor real?', answer: 'El coste equivalente es el importe futuro necesario para comprar lo que hoy compra el importe inicial. El valor real expresa en dinero de hoy lo que ese dinero sin cambios puede comprar al final.' },
  { question: '¿Qué incluyen los escenarios de aportación y retirada?', answer: 'Añaden o restan el flujo al final de cada año. No incluyen rentabilidad, impuestos, comisiones ni intereses, y el saldo de retiradas no puede ser inferior a cero.' },
  { question: '¿La tasa de inflación es una predicción?', answer: 'No. Es una hipótesis para explorar sensibilidad. La inflación real puede variar y un índice de precios publicado puede no coincidir con los gastos de tu hogar.' },
];
const howTo = [
  { name: 'Introduce un importe inicial', text: 'Usa el importe cuya capacidad de compra futura quieres analizar y mantén una sola moneda.' },
  { name: 'Define un escenario de inflación', text: 'Escribe una tasa anual y un horizonte entero. Prueba varias tasas para comparar sensibilidad.' },
  { name: 'Añade un flujo opcional', text: 'Elige Añadir cada año o Retirar cada año e introduce el importe. Deja Sin flujo recurrente para aislar la inflación.' },
  { name: 'Lee las curvas y los hitos', text: 'Compara el coste equivalente final con el valor final en dinero de hoy y revisa cuándo se abre la brecha.' },
];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, inLanguage: 'es' };
const seo = [
  { type: 'title' as const, text: 'Usa una línea temporal de inflación para planificar el poder adquisitivo', level: 2 },
  { type: 'paragraph' as const, html: '<p>La inflación cambia el nivel de precios, por lo que una cantidad de dinero que no varía puede comprar menos en el futuro. Esta calculadora separa cuánto dinero haría falta para comprar la misma cesta y cuánto poder adquisitivo conserva el dinero sin cambios.</p>' },
  { type: 'paragraph' as const, html: '<p>Introduce un importe inicial, una hipótesis de inflación anual y un horizonte temporal. La línea temporal acumula la tasa cada año y muestra cómo sube el coste equivalente mientras baja el poder de compra del dinero sin cambios.</p>' },
  { type: 'title' as const, text: 'Las dos lecturas principales', level: 3 },
  { type: 'table' as const, headers: ['Lectura', 'Fórmula', 'Pregunta'], rows: [['Coste equivalente', 'Importe inicial x (1 + inflación)^años', '¿Cuánto haría falta para comprar la misma cesta?'], ['Poder del dinero sin cambios', 'Importe inicial / (1 + inflación)^años', '¿Qué puede comprar al final, medido en dinero de hoy?'], ['Poder adquisitivo perdido', '(1 - 1 / factor de precios) x 100', '¿Qué parte del poder de compra ya no está disponible?']] },
  { type: 'paragraph' as const, html: '<p>Con una inflación anual del 3 %, 1.000 se convierten en un coste equivalente aproximado de 1.344 después de diez años. Si los 1.000 permanecen en efectivo, su poder adquisitivo equivale a unos 744 en dinero de hoy.</p>' },
  { type: 'title' as const, text: 'Por qué importa la capitalización', level: 3 },
  { type: 'paragraph' as const, html: '<p>Las tasas anuales se acumulan porque los precios de cada año son la base del siguiente. Diez años al 3 % no son un ajuste plano del 30 %: el factor es 1,03 elevado a diez, aproximadamente 1,344.</p>' },
  { type: 'list' as const, items: ['Prueba una tasa baja, central y alta.', 'Usa la tabla de hitos para detectar gastos que se encarecen de forma relevante.', 'Compara el coste equivalente con un objetivo de ahorro, ingreso o pensión.', 'Anota la hipótesis y la fecha y actualízalas cuando cambien tus datos.'] },
  { type: 'title' as const, text: 'Añadir aportaciones o retiradas', level: 3 },
  { type: 'paragraph' as const, html: '<p>El escenario de flujo de caja hace más útil la línea temporal para un plan de ahorro o gasto sin ocultar la inflación. La aportación se suma al saldo nominal al final de cada año; la retirada se resta y el saldo se detiene en cero cuando se agota.</p>' },
  { type: 'paragraph' as const, html: '<p>La línea discontinua del saldo se convierte a dinero de hoy con el mismo factor de inflación. No es una proyección de inversión: no incluye intereses, rentabilidad de mercado, impuestos, comisiones ni crecimiento de las aportaciones.</p>' },
  { type: 'tip' as const, title: 'Usa un intervalo, no una promesa', html: '<p>Los índices de precios describen una cesta media, mientras que tu alquiler, energía, alimentación, viajes y salud pueden evolucionar de otra manera. Prueba varias tasas y guarda la hipótesis utilizada.</p>' },
  { type: 'title' as const, text: 'Lo que la línea temporal no puede decir', level: 3 },
  { type: 'paragraph' as const, html: '<p>Esta herramienta no consulta datos históricos del IPC, predice la inflación, calcula tu coste de vida personal ni recomienda inversiones. Tampoco modela tasas anuales cambiantes, rentabilidades, intereses de deuda o flujos irregulares.</p>' },
  { type: 'paragraph' as const, html: '<p>Para una decisión importante, compara el resultado con un índice de precios adecuado, tus gastos reales y las condiciones del producto o ingreso. Un resultado matemáticamente coherente puede no describir bien tu hogar.</p>' },
];
export const content: ToolLocaleContent<InflationPurchasingPowerUI> = { slug: 'calculadora-linea-tiempo-poder-adquisitivo-inflacion', title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo };
