import { bibliography } from '../bibliography';
import type { WithContext, FAQPage, HowTo, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { InflationPurchasingPowerUI } from '../ui';

const title = 'Calculateur de l inflation et du pouvoir d achat dans le temps';
const description = 'Mesurez comment une hypothèse d inflation annuelle modifie le montant nécessaire pour préserver le pouvoir d achat et la valeur réelle de votre argent.';
const ui: InflationPurchasingPowerUI = {
  amountLabel: 'Montant de départ', amountHelp: 'Utilisez une seule devise pendant le calcul', inflationLabel: 'Taux d inflation annuel (%)', inflationHelp: 'Une hypothèse de scénario, pas une prévision', yearsLabel: 'Horizon (années)', yearsHelp: 'Choisissez de 1 à 80 ans', cashFlowLabel: 'Flux annuel', cashFlowHelp: 'Ajouté au solde ou retiré du solde chaque année', cashFlowModeLabel: 'Scénario de flux', noCashFlowOption: 'Aucun flux récurrent', contributionOption: 'Ajouter chaque année', withdrawalOption: 'Retirer chaque année', costEquivalentLabel: 'Equivalent de coût final', realValueLabel: 'Valeur finale en argent actuel', nominalBalanceLabel: 'Solde nominal final', purchasingPowerLossLabel: 'Pouvoir d achat perdu', todayLabel: 'Aujourd hui', endLabel: 'Fin de l horizon', costLineLabel: 'Coût pour le même panier', realLineLabel: 'Pouvoir d achat de l argent inchangé', balanceLineLabel: 'Solde du scénario en argent actuel', chartDescription: 'Évolution de l inflation montrant la hausse des coûts, la baisse du pouvoir d achat et le solde du scénario', chartNote: 'Chaque ligne est comparée au montant de départ', milestoneTitle: 'Étapes dans la même devise', yearHeader: 'Année', costHeader: 'Equivalent de coût', realHeader: 'Argent inchangé', balanceHeader: 'Solde réel', methodTitle: 'Fonctionnement de la chronologie', methodText: 'L équivalent de coût est le montant de départ multiplié par (1 + taux d inflation annuel) à la puissance du nombre d années. La valeur de l argent inchangé est le montant de départ divisé par ce même facteur. Une contribution est ajoutée en fin d année et un retrait est soustrait; le solde s arrête à zéro.', limitationText: 'Il s agit d un modèle de scénario transparent, pas d une consultation historique de l IPC, d une prévision de rendement ou d un conseil financier personnel. Votre panier peut différer d un indice des prix à la consommation publié et l inflation réelle peut varier chaque année.', emptyMessage: 'Saisissez un montant positif, un taux supérieur à -100 %, un nombre entier d années de 1 à 80 et un flux non négatif.', contributionSummary: 'La ligne en pointillés montre la valeur actuelle du solde après les contributions récurrentes, sans rendement d investissement.', withdrawalSummary: 'La ligne en pointillés montre la valeur actuelle du solde après les retraits récurrents, sans rendement d investissement.', noCashFlowSummary: 'Les lignes continues isolent l inflation: l une montre le coût futur du même panier et l autre ce que peut acheter l argent inchangé.', depletionWarning: 'Le scénario de retraits atteint zéro à l année {year}; les années suivantes restent à zéro.', scenarioNote: 'Scénario uniquement', currencyHint: 'Même devise que le montant de départ', yearsSuffix: 'ans', amountSuffix: 'dans la même devise que votre montant de départ',
};
const faq = [
  { question: 'Comment l inflation réduit-elle le pouvoir d achat?', answer: 'Quand le niveau général des prix augmente, le même montant achète moins de biens et de services. Le calculateur montre cet effet en divisant l argent inchangé par le facteur d inflation composé.' },
  { question: 'Quelle est la différence entre équivalent de coût et valeur réelle?', answer: 'L équivalent de coût est le montant futur nécessaire pour acheter ce que le montant de départ achète aujourd hui. La valeur réelle exprime en argent actuel ce que cet argent inchangé peut acheter à la fin.' },
  { question: 'Que comprennent les scénarios de contribution et de retrait?', answer: 'Le flux est ajouté ou soustrait en fin d année. Les rendements, taxes, frais et intérêts ne sont pas inclus, et un solde de retraits ne peut pas devenir négatif.' },
  { question: 'Le taux d inflation est-il une prédiction?', answer: 'Non. C est une hypothèse destinée à explorer la sensibilité. L inflation réelle peut varier et un indice publié peut ne pas correspondre aux dépenses de votre foyer.' },
];
const howTo = [
  { name: 'Saisir un montant de départ', text: 'Utilisez le montant dont vous voulez examiner le pouvoir d achat futur et gardez la même devise.' },
  { name: 'Définir un scénario d inflation', text: 'Entrez un taux annuel et un horizon en nombre entier. Comparez plusieurs taux pour tester la sensibilité.' },
  { name: 'Ajouter un flux facultatif', text: 'Choisissez Ajouter chaque année ou Retirer chaque année, puis saisissez le montant récurrent. Gardez Aucun flux récurrent pour isoler l inflation.' },
  { name: 'Lire les courbes et les étapes', text: 'Comparez l équivalent de coût final à la valeur finale en argent actuel, puis consultez le tableau.' },
];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, inLanguage: 'fr' };
const seo = [
  { type: 'title' as const, text: 'Utiliser une chronologie de l inflation pour planifier le pouvoir d achat', level: 2 },
  { type: 'paragraph' as const, html: '<p>L inflation modifie le niveau des prix. Une somme qui reste identique peut donc acheter moins à l avenir. Ce calculateur sépare le montant nécessaire pour acheter le même panier et le pouvoir d achat conservé par un argent inchangé.</p>' },
  { type: 'paragraph' as const, html: '<p>Saisissez un montant de départ, une hypothèse de taux annuel et un horizon. La chronologie compose le taux chaque année, puis affiche la hausse de l équivalent de coût et la baisse du pouvoir d achat.</p>' },
  { type: 'title' as const, text: 'Les deux lectures essentielles', level: 3 },
  { type: 'table' as const, headers: ['Lecture', 'Formule', 'Question'], rows: [['Équivalent de coût', 'Montant x (1 + taux d inflation)^années', 'Quel montant acheterait le même panier à la fin?'], ['Pouvoir de l argent inchangé', 'Montant / (1 + taux d inflation)^années', 'Que peut-il acheter à la fin en argent actuel?'], ['Pouvoir d achat perdu', '(1 - 1 / facteur des prix) x 100', 'Quelle part du pouvoir initial n est plus disponible?']] },
  { type: 'paragraph' as const, html: '<p>À 3 % d inflation annuelle, 1 000 deviennent un équivalent de coût d environ 1 344 après dix ans. Si les 1 000 restent en espèces, leur pouvoir d achat vaut environ 744 en argent actuel.</p>' },
  { type: 'title' as const, text: 'Pourquoi la composition compte', level: 3 },
  { type: 'paragraph' as const, html: '<p>Les taux annuels se composent car les prix de chaque année deviennent la base de la suivante. Dix ans à 3 % ne représentent donc pas un simple ajustement de 30 %: le facteur est 1,03 à la puissance dix, soit environ 1,344.</p>' },
  { type: 'list' as const, items: ['Testez un taux bas, central et haut.', 'Utilisez le tableau pour repérer les dépenses qui deviennent importantes.', 'Comparez l équivalent de coût avec un objectif d épargne, de revenu ou de retraite.', 'Notez l hypothèse et la date utilisées et remplacez-les quand les données changent.'] },
  { type: 'title' as const, text: 'Ajouter des contributions ou des retraits', level: 3 },
  { type: 'paragraph' as const, html: '<p>Le scénario de flux rend la chronologie utile pour un plan d épargne ou de dépenses sans masquer l inflation. Une contribution est ajoutée au solde nominal en fin d année, un retrait est soustrait, et le solde s arrête à zéro quand les retraits l épuisent.</p>' },
  { type: 'paragraph' as const, html: '<p>La ligne de solde en pointillés est reconvertie en argent actuel avec le même facteur d inflation. Ce n est pas une projection d investissement: aucun intérêt, rendement de marché, impôt, frais ou croissance des contributions n est inclus.</p>' },
  { type: 'tip' as const, title: 'Utilisez une fourchette, pas une promesse', html: '<p>Les indices des prix décrivent un panier moyen, tandis que votre logement, votre énergie, votre alimentation et votre santé peuvent évoluer autrement. Testez plusieurs taux.</p>' },
  { type: 'title' as const, text: 'Ce que la chronologie ne peut pas dire', level: 3 },
  { type: 'paragraph' as const, html: '<p>L outil ne récupère pas de données historiques de l IPC, ne prévoit pas l inflation et ne recommande pas de placement. Les taux annuels variables, les rendements, les intérêts de dette et les flux irréguliers ne sont pas modélisés.</p>' },
  { type: 'paragraph' as const, html: '<p>Pour une décision importante, comparez le résultat à un indice des prix pertinent, à vos dépenses réelles et aux conditions du produit ou du revenu concerné. Un résultat cohérent peut tout de même mal représenter votre foyer.</p>' },
];
export const content: ToolLocaleContent<InflationPurchasingPowerUI> = { slug: 'calculateur-evolution-pouvoir-achat-inflation', title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo };
