import { bibliography } from '../bibliography';
import type { WithContext, FAQPage, HowTo, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { InflationPurchasingPowerUI } from '../ui';

const title = 'Kalkulator garis waktu inflasi dan daya beli';
const description = 'Lihat bagaimana asumsi inflasi tahunan mengubah jumlah yang dibutuhkan untuk mempertahankan daya beli dan nilai riil uang tunai.';
const ui: InflationPurchasingPowerUI = {
  amountLabel: 'Jumlah awal', amountHelp: 'Gunakan satu mata uang secara konsisten', inflationLabel: 'Tingkat inflasi tahunan (%)', inflationHelp: 'Asumsi skenario, bukan ramalan', yearsLabel: 'Jangka waktu (tahun)', yearsHelp: 'Pilih 1 sampai 80 tahun', cashFlowLabel: 'Arus kas tahunan', cashFlowHelp: 'Ditambahkan ke atau diambil dari saldo setiap tahun', cashFlowModeLabel: 'Skenario arus kas', noCashFlowOption: 'Tanpa arus berulang', contributionOption: 'Tambah setiap tahun', withdrawalOption: 'Tarik setiap tahun', costEquivalentLabel: 'Setara biaya akhir', realValueLabel: 'Nilai akhir dalam uang hari ini', nominalBalanceLabel: 'Saldo nominal akhir', purchasingPowerLossLabel: 'Daya beli yang hilang', todayLabel: 'Hari ini', endLabel: 'Akhir jangka waktu', costLineLabel: 'Biaya untuk keranjang yang sama', realLineLabel: 'Daya beli uang tunai yang tidak berubah', balanceLineLabel: 'Saldo skenario dalam uang hari ini', chartDescription: 'Garis waktu inflasi yang menunjukkan biaya meningkat, daya beli menurun, dan saldo skenario', chartNote: 'Setiap garis dibandingkan dengan jumlah awal', milestoneTitle: 'Tonggak dalam mata uang yang sama', yearHeader: 'Tahun', costHeader: 'Setara biaya', realHeader: 'Uang tunai tetap', balanceHeader: 'Saldo riil', methodTitle: 'Cara kerja garis waktu', methodText: 'Setara biaya adalah jumlah awal dikalikan (1 + tingkat inflasi tahunan) pangkat jumlah tahun. Nilai uang tunai yang tidak berubah adalah jumlah awal dibagi faktor yang sama. Kontribusi ditambahkan pada akhir tahun dan penarikan dikurangkan pada akhir tahun; saldo berhenti di nol.', limitationText: 'Ini adalah model skenario yang transparan, bukan pencarian CPI historis, prakiraan imbal hasil investasi, atau nasihat keuangan pribadi. Keranjang belanja rumah tangga Anda dapat berbeda dari indeks harga konsumen yang diterbitkan dan inflasi nyata dapat berubah setiap tahun.', emptyMessage: 'Masukkan jumlah positif, tingkat di atas -100%, jumlah tahun bulat dari 1 sampai 80, dan arus kas yang tidak negatif.', contributionSummary: 'Garis putus-putus menunjukkan nilai hari ini dari saldo setelah kontribusi berulang, tanpa imbal hasil investasi.', withdrawalSummary: 'Garis putus-putus menunjukkan nilai hari ini dari saldo setelah penarikan berulang, tanpa imbal hasil investasi.', noCashFlowSummary: 'Garis utuh mengisolasi inflasi: satu menunjukkan biaya masa depan keranjang yang sama dan satu lagi menunjukkan daya beli uang tunai tetap.', depletionWarning: 'Skenario penarikan mencapai nol pada tahun {year}; tahun-tahun berikutnya tetap nol.', scenarioNote: 'Skenario saja', currencyHint: 'Mata uang yang sama dengan jumlah awal', yearsSuffix: 'tahun', amountSuffix: 'dalam mata uang yang sama dengan jumlah awal',
};
const faq = [
  { question: 'Bagaimana inflasi mengurangi daya beli?', answer: 'Saat tingkat harga umum naik, jumlah yang sama membeli lebih sedikit barang dan jasa. Kalkulator ini memodelkan efek tersebut dengan membagi uang tunai tetap menggunakan faktor inflasi majemuk.' },
  { question: 'Apa perbedaan setara biaya dan nilai riil?', answer: 'Setara biaya adalah jumlah masa depan yang diperlukan untuk membeli barang yang sama seperti jumlah awal hari ini. Nilai riil menunjukkan apa yang dapat dibeli uang tunai tetap pada akhir periode, dalam uang hari ini.' },
  { question: 'Apa yang termasuk dalam skenario kontribusi dan penarikan?', answer: 'Arus kas ditambahkan atau dikurangkan pada akhir setiap tahun. Imbal hasil, pajak, biaya, dan bunga tidak termasuk, dan saldo penarikan tidak dapat turun di bawah nol.' },
  { question: 'Apakah tingkat inflasi merupakan prediksi?', answer: 'Bukan. Ini adalah asumsi untuk mengeksplorasi sensitivitas. Inflasi nyata dapat berbeda dan indeks harga konsumen dapat tidak sesuai dengan pola belanja rumah tangga Anda.' },
];
const howTo = [
  { name: 'Masukkan jumlah awal', text: 'Gunakan jumlah yang daya belinya ingin Anda periksa di masa depan dan pertahankan satu mata uang.' },
  { name: 'Atur skenario inflasi', text: 'Masukkan tingkat tahunan dan jangka waktu bilangan bulat. Uji beberapa tingkat untuk melihat sensitivitas.' },
  { name: 'Tambahkan arus kas pilihan', text: 'Pilih Tambah setiap tahun atau Tarik setiap tahun, lalu masukkan jumlahnya. Gunakan Tanpa arus berulang untuk mengisolasi inflasi.' },
  { name: 'Baca kurva dan tonggak', text: 'Bandingkan setara biaya akhir dengan nilai akhir dalam uang hari ini, lalu lihat tabel tonggak.' },
];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, inLanguage: 'id' };
const seo = [
  { type: 'title' as const, text: 'Gunakan garis waktu inflasi untuk merencanakan daya beli', level: 2 },
  { type: 'paragraph' as const, html: '<p>Inflasi mengubah tingkat harga, sehingga uang yang tidak berubah dapat membeli lebih sedikit di masa depan. Kalkulator ini memisahkan jumlah yang diperlukan untuk membeli keranjang yang sama dari daya beli yang tersisa pada uang tunai tetap.</p>' },
  { type: 'paragraph' as const, html: '<p>Masukkan jumlah awal, asumsi inflasi tahunan, dan jangka waktu. Garis waktu menggandakan tingkat setiap tahun, lalu menampilkan biaya yang meningkat dan daya beli uang tetap yang menurun.</p>' },
  { type: 'title' as const, text: 'Dua pembacaan utama', level: 3 },
  { type: 'table' as const, headers: ['Pembacaan', 'Rumus', 'Pertanyaan'], rows: [['Setara biaya', 'Jumlah awal x (1 + inflasi)^tahun', 'Berapa yang diperlukan untuk keranjang yang sama?'], ['Daya beli uang tetap', 'Jumlah awal / (1 + inflasi)^tahun', 'Apa yang dapat dibeli pada akhir periode dalam uang hari ini?'], ['Daya beli hilang', '(1 - 1 / faktor harga) x 100', 'Berapa bagian daya beli awal yang hilang?']] },
  { type: 'paragraph' as const, html: '<p>Dengan inflasi tahunan 3%, 1.000 menjadi setara biaya sekitar 1.344 setelah sepuluh tahun. Jika 1.000 tetap sebagai uang tunai, daya belinya sekitar 744 dalam uang hari ini.</p>' },
  { type: 'title' as const, text: 'Mengapa penggandaan penting', level: 3 },
  { type: 'paragraph' as const, html: '<p>Tingkat tahunan digabung karena harga setiap tahun menjadi dasar tahun berikutnya. Sepuluh tahun pada 3% bukan penyesuaian datar 30%; faktornya adalah 1,03 pangkat sepuluh, sekitar 1,344.</p>' },
  { type: 'list' as const, items: ['Uji tingkat rendah, tengah, dan tinggi.', 'Gunakan tabel tonggak untuk menemukan biaya yang menjadi penting.', 'Bandingkan setara biaya dengan target tabungan, pendapatan, atau pensiun.', 'Catat asumsi dan tanggal yang digunakan lalu perbarui saat bukti berubah.'] },
  { type: 'title' as const, text: 'Menambahkan kontribusi atau penarikan', level: 3 },
  { type: 'paragraph' as const, html: '<p>Arus kas pilihan membantu menilai rencana menabung atau belanja tanpa menyembunyikan efek inflasi. Kontribusi ditambahkan ke saldo nominal pada akhir tahun, sedangkan penarikan dikurangkan dan saldo berhenti di nol saat habis.</p>' },
  { type: 'paragraph' as const, html: '<p>Garis saldo putus-putus diubah kembali ke uang hari ini dengan faktor inflasi yang sama. Ini bukan proyeksi investasi: tidak ada bunga, imbal hasil pasar, pajak, biaya, atau pertumbuhan kontribusi.</p>' },
  { type: 'tip' as const, title: 'Gunakan rentang, bukan janji', html: '<p>Indeks harga konsumen menggambarkan keranjang rata-rata, sedangkan sewa, energi, makanan, perjalanan, dan kesehatan Anda dapat bergerak berbeda. Uji beberapa tingkat.</p>' },
  { type: 'title' as const, text: 'Hal yang tidak dapat diberitahukan garis waktu', level: 3 },
  { type: 'paragraph' as const, html: '<p>Alat ini tidak mengambil data CPI historis, meramalkan inflasi, menghitung biaya hidup pribadi, atau merekomendasikan investasi. Tingkat tahunan yang berubah, imbal hasil aset, bunga utang, dan arus kas tidak teratur juga tidak dimodelkan.</p>' },
  { type: 'paragraph' as const, html: '<p>Untuk keputusan penting, bandingkan hasilnya dengan indeks harga yang sesuai, catatan belanja nyata, dan ketentuan produk atau pendapatan. Hasil yang konsisten secara matematika belum tentu menggambarkan rumah tangga Anda.</p>' },
];
export const content: ToolLocaleContent<InflationPurchasingPowerUI> = { slug: 'kalkulator-garis-waktu-daya-beli-inflasi', title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo };
