import { bibliography } from '../bibliography';
import type { WithContext, FAQPage, HowTo, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { InflationPurchasingPowerUI } from '../ui';

const title = 'Calcolatore dell inflazione e del potere d acquisto nel tempo';
const description = 'Scopri come un ipotesi di inflazione annuale cambia la somma necessaria per mantenere il potere d acquisto e il valore reale del denaro.';
const ui: InflationPurchasingPowerUI = {
  amountLabel: 'Importo iniziale', amountHelp: 'Usa una sola valuta per tutto il calcolo', inflationLabel: 'Inflazione annuale (%)', inflationHelp: 'Un ipotesi di scenario, non una previsione', yearsLabel: 'Orizzonte temporale (anni)', yearsHelp: 'Scegli da 1 a 80 anni', cashFlowLabel: 'Flusso di cassa annuale', cashFlowHelp: 'Aggiunto al saldo o sottratto dal saldo ogni anno', cashFlowModeLabel: 'Scenario del flusso', noCashFlowOption: 'Nessun flusso ricorrente', contributionOption: 'Aggiungi ogni anno', withdrawalOption: 'Ritira ogni anno', costEquivalentLabel: 'Costo equivalente finale', realValueLabel: 'Valore finale in denaro di oggi', nominalBalanceLabel: 'Saldo nominale finale', purchasingPowerLossLabel: 'Potere d acquisto perso', todayLabel: 'Oggi', endLabel: 'Fine dell orizzonte', costLineLabel: 'Costo per lo stesso paniere', realLineLabel: 'Potere d acquisto del denaro invariato', balanceLineLabel: 'Saldo dello scenario in denaro di oggi', chartDescription: 'Andamento dell inflazione con costi in crescita, potere d acquisto in calo e saldo dello scenario', chartNote: 'Ogni linea è confrontata con l importo iniziale', milestoneTitle: 'Traguardi nella stessa valuta', yearHeader: 'Anno', costHeader: 'Costo equivalente', realHeader: 'Denaro invariato', balanceHeader: 'Saldo reale', methodTitle: 'Come funziona la sequenza', methodText: 'Il costo equivalente è l importo iniziale moltiplicato per (1 + inflazione annuale) elevato al numero di anni. Il valore del denaro invariato è l importo iniziale diviso per lo stesso fattore. Un versamento viene aggiunto a fine anno e un prelievo viene sottratto; il saldo non scende sotto zero.', limitationText: 'È un modello trasparente di scenario, non una consultazione storica dell IPC, una previsione di rendimento o una consulenza finanziaria personale. Il tuo paniere può differire da un indice dei prezzi pubblicato e l inflazione effettiva può cambiare ogni anno.', emptyMessage: 'Inserisci un importo positivo, un tasso superiore a -100 %, un numero intero di anni da 1 a 80 e un flusso non negativo.', contributionSummary: 'La linea tratteggiata mostra il valore attuale del saldo dopo i versamenti ricorrenti, senza rendimento degli investimenti.', withdrawalSummary: 'La linea tratteggiata mostra il valore attuale del saldo dopo i prelievi ricorrenti, senza rendimento degli investimenti.', noCashFlowSummary: 'Le linee continue isolano l inflazione: una mostra il costo futuro dello stesso paniere e l altra ciò che può comprare il denaro invariato.', depletionWarning: 'Lo scenario di prelievo raggiunge zero nell anno {year}; gli anni successivi restano a zero.', scenarioNote: 'Solo scenario', currencyHint: 'Stessa valuta dell importo iniziale', yearsSuffix: 'anni', amountSuffix: 'nella stessa valuta dell importo iniziale',
};
const faq = [
  { question: 'Come riduce l inflazione il potere d acquisto?', answer: 'Quando il livello generale dei prezzi sale, la stessa somma compra meno beni e servizi. Il calcolatore mostra questo effetto dividendo il denaro invariato per il fattore d inflazione composto.' },
  { question: 'Qual è la differenza tra costo equivalente e valore reale?', answer: 'Il costo equivalente è la somma futura necessaria per comprare ciò che oggi compra l importo iniziale. Il valore reale esprime in denaro di oggi ciò che il denaro invariato può comprare alla fine.' },
  { question: 'Cosa includono gli scenari di versamento e prelievo?', answer: 'Aggiungono o sottraggono il flusso alla fine di ogni anno. Non includono rendimenti, tasse, commissioni o interessi, e il saldo dei prelievi non può diventare negativo.' },
  { question: 'Il tasso d inflazione è una previsione?', answer: 'No. È un ipotesi per esplorare la sensibilità. L inflazione reale può variare e un indice pubblicato può non rispecchiare le spese della tua famiglia.' },
];
const howTo = [
  { name: 'Inserisci un importo iniziale', text: 'Usa l importo di cui vuoi analizzare il potere d acquisto futuro e mantieni una sola valuta.' },
  { name: 'Imposta uno scenario d inflazione', text: 'Inserisci un tasso annuale e un orizzonte intero. Prova più tassi per confrontare la sensibilità.' },
  { name: 'Aggiungi un flusso facoltativo', text: 'Scegli Aggiungi ogni anno o Ritira ogni anno e inserisci l importo ricorrente. Lascia Nessun flusso ricorrente per isolare l inflazione.' },
  { name: 'Leggi curve e traguardi', text: 'Confronta il costo equivalente finale con il valore finale in denaro di oggi e osserva la tabella dei traguardi.' },
];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, inLanguage: 'it' };
const seo = [
  { type: 'title' as const, text: 'Usa una sequenza dell inflazione per pianificare il potere d acquisto', level: 2 },
  { type: 'paragraph' as const, html: '<p>L inflazione cambia il livello dei prezzi, quindi una somma invariata può comprare meno in futuro. Questo calcolatore separa la somma necessaria per acquistare lo stesso paniere dal potere d acquisto conservato dal denaro invariato.</p>' },
  { type: 'paragraph' as const, html: '<p>Inserisci un importo iniziale, un ipotesi annuale e un orizzonte. La sequenza compone il tasso ogni anno, mostrando il costo equivalente in salita e il potere d acquisto del denaro invariato in discesa.</p>' },
  { type: 'title' as const, text: 'Le due letture principali', level: 3 },
  { type: 'table' as const, headers: ['Lettura', 'Formula', 'Domanda'], rows: [['Costo equivalente', 'Importo x (1 + inflazione)^anni', 'Quanto serve alla fine per lo stesso paniere?'], ['Potere del denaro invariato', 'Importo / (1 + inflazione)^anni', 'Cosa può comprare alla fine in denaro di oggi?'], ['Potere d acquisto perso', '(1 - 1 / fattore prezzi) x 100', 'Quale quota del potere iniziale non è più disponibile?']] },
  { type: 'paragraph' as const, html: '<p>Con un inflazione annua del 3 %, 1.000 diventano un costo equivalente di circa 1.344 dopo dieci anni. Se restano in contanti, il loro potere d acquisto vale circa 744 in denaro di oggi.</p>' },
  { type: 'title' as const, text: 'Perché conta la capitalizzazione', level: 3 },
  { type: 'paragraph' as const, html: '<p>I tassi annuali si compongono perché i prezzi di ogni anno diventano la base del successivo. Dieci anni al 3 % non sono un semplice 30 %: il fattore è 1,03 elevato a dieci, circa 1,344.</p>' },
  { type: 'list' as const, items: ['Prova un tasso basso, centrale e alto.', 'Usa la tabella per capire quando una spesa diventa importante.', 'Confronta il costo equivalente con un obiettivo di risparmio, reddito o pensione.', 'Segna ipotesi e data e cambiale quando cambiano le informazioni.'] },
  { type: 'title' as const, text: 'Aggiungere versamenti o prelievi', level: 3 },
  { type: 'paragraph' as const, html: '<p>Lo scenario del flusso rende la sequenza utile per un piano di risparmio o spesa senza nascondere l inflazione. Il versamento si aggiunge al saldo nominale a fine anno; il prelievo si sottrae e il saldo si ferma a zero quando si esaurisce.</p>' },
  { type: 'paragraph' as const, html: '<p>La linea tratteggiata del saldo è riconvertita in denaro di oggi con lo stesso fattore. Non è una proiezione d investimento: non include interessi, rendimenti, imposte, commissioni o crescita dei versamenti.</p>' },
  { type: 'tip' as const, title: 'Usa un intervallo, non una promessa', html: '<p>Gli indici dei prezzi descrivono un paniere medio, mentre affitto, energia, alimentari e salute possono muoversi diversamente. Prova più tassi.</p>' },
  { type: 'title' as const, text: 'Cosa non può dire la sequenza', level: 3 },
  { type: 'paragraph' as const, html: '<p>Lo strumento non recupera dati storici dell IPC, non prevede l inflazione e non consiglia investimenti. Non modella tassi variabili, rendimenti, interessi sul debito o flussi irregolari.</p>' },
  { type: 'paragraph' as const, html: '<p>Per una decisione importante, confronta il risultato con un indice dei prezzi adatto, le tue spese reali e le condizioni del prodotto o del reddito. Un risultato coerente può comunque descrivere male il tuo nucleo familiare.</p>' },
];
export const content: ToolLocaleContent<InflationPurchasingPowerUI> = { slug: 'calcolatore-timeline-potere-acquisto-inflazione', title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo };
