import { bibliography } from '../bibliography';
import type { WithContext, FAQPage, HowTo, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { InflationPurchasingPowerUI } from '../ui';

const title = 'Calculator voor inflatie en koopkracht door de tijd';
const description = 'Bekijk hoe een jaarlijkse inflatieaanname het bedrag voor dezelfde koopkracht en de reële waarde van contant geld verandert.';
const ui: InflationPurchasingPowerUI = {
  amountLabel: 'Startbedrag', amountHelp: 'Gebruik steeds dezelfde valuta', inflationLabel: 'Jaarlijkse inflatie (%)', inflationHelp: 'Een scenarioaanname, geen voorspelling', yearsLabel: 'Periode (jaren)', yearsHelp: 'Kies 1 tot 80 jaar', cashFlowLabel: 'Jaarlijkse kasstroom', cashFlowHelp: 'Wordt elk jaar bij het saldo opgeteld of ervan afgetrokken', cashFlowModeLabel: 'Kasstroomscenario', noCashFlowOption: 'Geen terugkerende stroom', contributionOption: 'Elk jaar toevoegen', withdrawalOption: 'Elk jaar opnemen', costEquivalentLabel: 'Eindwaarde van de kosten', realValueLabel: 'Eindwaarde in geld van vandaag', nominalBalanceLabel: 'Nominaal eindsaldo', purchasingPowerLossLabel: 'Verloren koopkracht', todayLabel: 'Vandaag', endLabel: 'Einde van de periode', costLineLabel: 'Kosten voor dezelfde boodschappenmand', realLineLabel: 'Koopkracht van ongewijzigd contant geld', balanceLineLabel: 'Scenario saldo in geld van vandaag', chartDescription: 'Inflatietijdlijn met stijgende kosten, dalende koopkracht en het scenariosaldo', chartNote: 'Elke lijn wordt vergeleken met het startbedrag', milestoneTitle: 'Mijlpalen in dezelfde valuta', yearHeader: 'Jaar', costHeader: 'Kostenwaarde', realHeader: 'Ongewijzigd geld', balanceHeader: 'Reëel saldo', methodTitle: 'Zo werkt de tijdlijn', methodText: 'De kostenwaarde is het startbedrag vermenigvuldigd met (1 + jaarlijkse inflatie) tot de macht van het aantal jaren. De waarde van ongewijzigd geld is het startbedrag gedeeld door dezelfde factor. Een bijdrage wordt aan het einde van elk jaar toegevoegd en een opname afgetrokken; het saldo stopt bij nul.', limitationText: 'Dit is een transparant scenariomodel, geen historische CPI-opvraag, rendementsprognose of persoonlijk financieel advies. Jouw boodschappenmand kan afwijken van een gepubliceerde consumentenprijsindex en de werkelijke inflatie kan per jaar veranderen.', emptyMessage: 'Vul een positief bedrag in, een percentage boven -100%, een geheel aantal jaren van 1 tot 80 en een niet-negatieve kasstroom.', contributionSummary: 'De stippellijn toont de huidige waarde van het saldo na terugkerende bijdragen, zonder beleggingsrendement.', withdrawalSummary: 'De stippellijn toont de huidige waarde van het saldo na terugkerende opnames, zonder beleggingsrendement.', noCashFlowSummary: 'De doorgetrokken lijnen isoleren inflatie: de ene toont de toekomstige kosten van dezelfde mand en de andere wat ongewijzigd geld kan kopen.', depletionWarning: 'Het opnamescenario bereikt nul in jaar {year}; latere jaren blijven op nul.', scenarioNote: 'Alleen scenario', currencyHint: 'Dezelfde valuta als het startbedrag', yearsSuffix: 'jaar', amountSuffix: 'in dezelfde valuta als je startbedrag',
};
const faq = [
  { question: 'Hoe vermindert inflatie de koopkracht?', answer: 'Als het algemene prijsniveau stijgt, koopt hetzelfde bedrag minder goederen en diensten. Deze calculator deelt ongewijzigd geld door de samengestelde inflatiefactor.' },
  { question: 'Wat is het verschil tussen kostenwaarde en reële waarde?', answer: 'De kostenwaarde is het toekomstige bedrag dat nodig is voor dezelfde mand. De reële waarde laat zien wat het ongewijzigde startbedrag aan het einde kan kopen, uitgedrukt in geld van vandaag.' },
  { question: 'Wat bevatten de scenario\'s voor bijdragen en opnames?', answer: 'De kasstroom wordt aan het einde van elk jaar toegevoegd of afgetrokken. Rendement, belasting, kosten en rente zijn niet inbegrepen en een opnamesaldo kan niet onder nul komen.' },
  { question: 'Is het inflatiepercentage een voorspelling?', answer: 'Nee. Het is een aanname om gevoeligheid te verkennen. De werkelijke inflatie kan verschillen van een gepubliceerde index en van jouw uitgavenpatroon.' },
];
const howTo = [
  { name: 'Voer een startbedrag in', text: 'Gebruik het bedrag waarvan je de toekomstige koopkracht wilt bekijken en houd één valuta aan.' },
  { name: 'Stel een inflatiescenario in', text: 'Voer een jaarlijks percentage en een geheel aantal jaren in. Vergelijk meerdere percentages.' },
  { name: 'Voeg een optionele kasstroom toe', text: 'Kies Elk jaar toevoegen of Elk jaar opnemen en voer het bedrag in. Kies Geen terugkerende stroom om inflatie alleen te bekijken.' },
  { name: 'Lees de lijnen en mijlpalen', text: 'Vergelijk de eindkosten met de eindwaarde in geld van vandaag en bekijk de mijlpalentabel.' },
];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, inLanguage: 'nl' };
const seo = [
  { type: 'title' as const, text: 'Gebruik een inflatietijdlijn om koopkracht te plannen', level: 2 },
  { type: 'paragraph' as const, html: '<p>Inflatie verandert het prijsniveau, waardoor een gelijkblijvend geldbedrag later minder kan kopen. Deze calculator scheidt de kosten voor dezelfde boodschappenmand van de koopkracht die ongewijzigd geld behoudt.</p>' },
  { type: 'paragraph' as const, html: '<p>Voer een startbedrag, jaarlijkse inflatieaanname en periode in. De tijdlijn stapelt het percentage elk jaar op en toont stijgende kosten naast dalende koopkracht.</p>' },
  { type: 'title' as const, text: 'De twee belangrijkste waarden', level: 3 },
  { type: 'table' as const, headers: ['Waarde', 'Formule', 'Vraag'], rows: [['Kostenwaarde', 'Startbedrag x (1 + inflatie)^jaren', 'Hoeveel is er nodig voor dezelfde mand?'], ['Koopkracht van geld', 'Startbedrag / (1 + inflatie)^jaren', 'Wat kan het aan het einde kopen in geld van vandaag?'], ['Verloren koopkracht', '(1 - 1 / prijsfactor) x 100', 'Welk aandeel van de startkoopkracht is weg?']] },
  { type: 'paragraph' as const, html: '<p>Bij 3% jaarlijkse inflatie wordt 1.000 na tien jaar een kostenwaarde van ongeveer 1.344. Als de 1.000 ongewijzigd contant blijft, is de koopkracht ongeveer 744 in geld van vandaag.</p>' },
  { type: 'title' as const, text: 'Waarom samengestelde groei telt', level: 3 },
  { type: 'paragraph' as const, html: '<p>Jaarlijkse inflatie stapelt zich op omdat de prijzen van elk jaar de basis vormen voor het volgende jaar. Tien jaar met 3% is dus geen vlakke 30%; de factor is 1,03 tot de tiende macht, ongeveer 1,344.</p>' },
  { type: 'list' as const, items: ['Test een laag, midden en hoog percentage.', 'Gebruik de mijlpalen voor uitgaven die duidelijk duurder worden.', 'Vergelijk de kostenwaarde met een spaardoel, inkomen of pensioen.', 'Noteer aanname en datum en pas ze aan als je informatie verandert.'] },
  { type: 'title' as const, text: 'Bijdragen of opnames toevoegen', level: 3 },
  { type: 'paragraph' as const, html: '<p>Het kasstroomscenario maakt de tijdlijn bruikbaar voor een spaar- of bestedingsplan zonder het inflatie-effect te verbergen. Een bijdrage komt aan het einde van het jaar bij het nominale saldo; een opname gaat ervan af en het saldo stopt bij nul.</p>' },
  { type: 'paragraph' as const, html: '<p>De gestippelde saldolijn wordt met dezelfde inflatiefactor omgerekend naar geld van vandaag. Het is geen beleggingsprognose: rente, marktresultaat, belasting, kosten en groei van bijdragen ontbreken.</p>' },
  { type: 'tip' as const, title: 'Gebruik een bandbreedte, geen belofte', html: '<p>Prijsindexen beschrijven een gemiddelde mand, terwijl huur, energie, voeding en zorg van jouw huishouden anders kunnen bewegen. Test meerdere percentages.</p>' },
  { type: 'title' as const, text: 'Wat de tijdlijn niet kan vertellen', level: 3 },
  { type: 'paragraph' as const, html: '<p>De tool haalt geen historische CPI op, voorspelt geen inflatie en adviseert geen belegging. Wisselende jaartarieven, rendementen, schuldrente en onregelmatige kasstromen zijn niet gemodelleerd.</p>' },
  { type: 'paragraph' as const, html: '<p>Vergelijk het resultaat bij een belangrijke beslissing met een passende prijsindex, je echte uitgaven en de voorwaarden van het product of inkomen. Een wiskundig consistent resultaat kan je huishouden toch slecht beschrijven.</p>' },
];
export const content: ToolLocaleContent<InflationPurchasingPowerUI> = { slug: 'inflatie-koopkracht-tijdlijn-calculator', title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo };
