import { bibliography } from '../bibliography';
import type { WithContext, FAQPage, HowTo, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { InflationPurchasingPowerUI } from '../ui';

const title = 'Kalkulator inflacji i siły nabywczej w czasie';
const description = 'Sprawdź, jak założenie rocznej inflacji zmienia kwotę potrzebną do zachowania siły nabywczej oraz realną wartość gotówki.';
const ui: InflationPurchasingPowerUI = {
  amountLabel: 'Kwota początkowa', amountHelp: 'Używaj jednej waluty przez całe obliczenie', inflationLabel: 'Roczna stopa inflacji (%)', inflationHelp: 'Założenie scenariusza, nie prognoza', yearsLabel: 'Okres (lata)', yearsHelp: 'Wybierz od 1 do 80 lat', cashFlowLabel: 'Roczny przepływ gotówki', cashFlowHelp: 'Co roku dodawany do salda lub z niego odejmowany', cashFlowModeLabel: 'Scenariusz przepływu', noCashFlowOption: 'Bez przepływu cyklicznego', contributionOption: 'Dodaj co roku', withdrawalOption: 'Wypłacaj co roku', costEquivalentLabel: 'Końcowy równoważnik kosztu', realValueLabel: 'Końcowa wartość w dzisiejszych pieniądzach', nominalBalanceLabel: 'Końcowe saldo nominalne', purchasingPowerLossLabel: 'Utracona siła nabywcza', todayLabel: 'Dziś', endLabel: 'Koniec okresu', costLineLabel: 'Koszt tego samego koszyka', realLineLabel: 'Siła nabywcza niezmienionej gotówki', balanceLineLabel: 'Saldo scenariusza w dzisiejszych pieniądzach', chartDescription: 'Oś czasu inflacji pokazująca rosnący koszt, spadającą siłę nabywczą i saldo scenariusza', chartNote: 'Każda linia jest mierzona względem kwoty początkowej', milestoneTitle: 'Kamienie milowe w tej samej walucie', yearHeader: 'Rok', costHeader: 'Równoważnik kosztu', realHeader: 'Niezmieniona gotówka', balanceHeader: 'Saldo realne', methodTitle: 'Jak działa oś czasu', methodText: 'Równoważnik kosztu to kwota początkowa pomnożona przez (1 + roczna stopa inflacji) do potęgi liczby lat. Wartość niezmienionej gotówki to kwota początkowa podzielona przez ten sam czynnik. Wpłata jest dodawana na koniec roku, a wypłata odejmowana; saldo zatrzymuje się na poziomie zera.', limitationText: 'To przejrzysty model scenariuszowy, a nie wyszukiwanie historycznego CPI, prognoza zwrotu ani osobista porada finansowa. Koszyk Twojego gospodarstwa może różnić się od opublikowanego indeksu cen konsumenckich, a rzeczywista inflacja może zmieniać się z roku na rok.', emptyMessage: 'Wpisz dodatnią kwotę, stopę powyżej -100%, całkowitą liczbę lat od 1 do 80 oraz nieujemny przepływ gotówki.', contributionSummary: 'Linia przerywana pokazuje dzisiejszą wartość salda po cyklicznych wpłatach, bez uwzględniania zwrotu z inwestycji.', withdrawalSummary: 'Linia przerywana pokazuje dzisiejszą wartość salda po cyklicznych wypłatach, bez uwzględniania zwrotu z inwestycji.', noCashFlowSummary: 'Linie ciągłe pokazują samą inflację: jedna przedstawia przyszły koszt tego samego koszyka, a druga to, co może kupić niezmieniona gotówka.', depletionWarning: 'Scenariusz wypłat osiąga zero w roku {year}; w kolejnych latach pozostaje na poziomie zera.', scenarioNote: 'Tylko scenariusz', currencyHint: 'Ta sama waluta co kwota początkowa', yearsSuffix: 'lat', amountSuffix: 'w tej samej walucie co kwota początkowa',
};
const faq = [
  { question: 'Jak inflacja obniża siłę nabywczą?', answer: 'Gdy ogólny poziom cen rośnie, ta sama kwota kupuje mniej towarów i usług. Kalkulator pokazuje ten efekt, dzieląc niezmienioną gotówkę przez skumulowany czynnik inflacji.' },
  { question: 'Jaka jest różnica między równoważnikiem kosztu a wartością realną?', answer: 'Równoważnik kosztu to przyszła kwota potrzebna do kupienia tego, co dziś kupuje kwota początkowa. Wartość realna pokazuje w dzisiejszych pieniądzach, co niezmieniona gotówka kupi na końcu okresu.' },
  { question: 'Co obejmują scenariusze wpłat i wypłat?', answer: 'Dodają lub odejmują przepływ na koniec każdego roku. Nie obejmują zwrotów, podatków, opłat ani odsetek, a saldo wypłat nie może spaść poniżej zera.' },
  { question: 'Czy stopa inflacji jest prognozą?', answer: 'Nie. To założenie do badania wrażliwości. Rzeczywista inflacja może się różnić, a opublikowany indeks może nie odpowiadać wydatkom Twojego gospodarstwa.' },
];
const howTo = [
  { name: 'Wpisz kwotę początkową', text: 'Użyj kwoty, której przyszłą siłę nabywczą chcesz zbadać, i zachowaj jedną walutę.' },
  { name: 'Ustaw scenariusz inflacji', text: 'Wpisz roczną stopę i całkowity okres. Porównuj kilka stóp zamiast opierać się na jednym założeniu.' },
  { name: 'Dodaj opcjonalny przepływ', text: 'Wybierz Dodaj co roku lub Wypłacaj co roku i wpisz kwotę. Wybierz Bez przepływu, aby pokazać samą inflację.' },
  { name: 'Odczytaj krzywe i kamienie milowe', text: 'Porównaj końcowy koszt z końcową wartością w dzisiejszych pieniądzach i sprawdź tabelę.' },
];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, inLanguage: 'pl' };
const seo = [
  { type: 'title' as const, text: 'Użyj osi czasu inflacji do planowania siły nabywczej', level: 2 },
  { type: 'paragraph' as const, html: '<p>Inflacja zmienia poziom cen, więc niezmieniona kwota może w przyszłości kupić mniej. Ten kalkulator oddziela kwotę potrzebną na ten sam koszyk od siły nabywczej zachowanej przez niezmienioną gotówkę.</p>' },
  { type: 'paragraph' as const, html: '<p>Wpisz kwotę początkową, roczne założenie inflacji i okres. Oś czasu kumuluje stopę każdego roku, pokazując wzrost równoważnika kosztu i spadek siły nabywczej gotówki.</p>' },
  { type: 'title' as const, text: 'Dwa podstawowe odczyty', level: 3 },
  { type: 'table' as const, headers: ['Odczyt', 'Wzór', 'Pytanie'], rows: [['Równoważnik kosztu', 'Kwota x (1 + inflacja)^lata', 'Ile będzie potrzebne na ten sam koszyk?'], ['Siła niezmienionej gotówki', 'Kwota / (1 + inflacja)^lata', 'Co kupi na końcu w dzisiejszych pieniądzach?'], ['Utracona siła nabywcza', '(1 - 1 / czynnik cen) x 100', 'Jaka część początkowej siły jest niedostępna?']] },
  { type: 'paragraph' as const, html: '<p>Przy inflacji 3% rocznie kwota 1 000 staje się po dziesięciu latach równoważnikiem kosztu około 1 344. Jeśli pozostaje niezmienioną gotówką, jej siła nabywcza wynosi około 744 w dzisiejszych pieniądzach.</p>' },
  { type: 'title' as const, text: 'Dlaczego kumulacja ma znaczenie', level: 3 },
  { type: 'paragraph' as const, html: '<p>Roczne stopy kumulują się, ponieważ ceny z każdego roku stają się podstawą dla następnego. Dziesięć lat przy 3% to nie płaskie 30%: czynnik wynosi 1,03 do potęgi dziesiątej, czyli około 1,344.</p>' },
  { type: 'list' as const, items: ['Uruchom niski, środkowy i wysoki wariant.', 'Użyj tabeli, aby znaleźć wydatki, które stają się istotnie droższe.', 'Porównaj równoważnik kosztu z celem oszczędności, dochodem lub emeryturą.', 'Zapisz założenie i datę, a potem zmień je, gdy zmienią się dane.'] },
  { type: 'title' as const, text: 'Dodawanie wpłat lub wypłat', level: 3 },
  { type: 'paragraph' as const, html: '<p>Scenariusz przepływu pomaga analizować plan oszczędzania lub wydawania bez ukrywania inflacji. Wpłata trafia do salda nominalnego na koniec roku, wypłata jest odejmowana, a saldo zatrzymuje się na zerze po wyczerpaniu środków.</p>' },
  { type: 'paragraph' as const, html: '<p>Przerywana linia salda jest przeliczana na dzisiejsze pieniądze tym samym czynnikiem. To nie jest prognoza inwestycyjna: nie ma tu odsetek, zwrotu rynkowego, podatków, opłat ani wzrostu wpłat.</p>' },
  { type: 'tip' as const, title: 'Używaj przedziału, nie obietnicy', html: '<p>Indeksy cen opisują przeciętny koszyk, a Twój czynsz, energia, żywność i zdrowie mogą zmieniać się inaczej. Sprawdź kilka stóp.</p>' },
  { type: 'title' as const, text: 'Czego oś czasu nie może powiedzieć', level: 3 },
  { type: 'paragraph' as const, html: '<p>Narzędzie nie pobiera historycznych danych CPI, nie prognozuje inflacji i nie poleca inwestycji. Nie modeluje zmiennych stóp, zwrotów aktywów, odsetek od długu ani nieregularnych przepływów.</p>' },
  { type: 'paragraph' as const, html: '<p>Przy ważnej decyzji porównaj wynik z odpowiednim indeksem cen, własnymi wydatkami i warunkami produktu lub dochodu. Matematycznie spójny wynik może nadal słabo opisywać Twoje gospodarstwo.</p>' },
];
export const content: ToolLocaleContent<InflationPurchasingPowerUI> = { slug: 'kalkulator-osi-czasu-sily-nabywczej-inflacji', title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo };
