import { bibliography } from '../bibliography';
import type { WithContext, FAQPage, HowTo, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { InflationPurchasingPowerUI } from '../ui';

const title = 'Calculadora de inflação e poder de compra ao longo do tempo';
const description = 'Veja como uma hipótese de inflação anual altera o valor necessário para preservar o poder de compra e o valor real do dinheiro.';
const ui: InflationPurchasingPowerUI = {
  amountLabel: 'Valor inicial', amountHelp: 'Use uma moeda e mantenha-a durante o cálculo', inflationLabel: 'Inflação anual (%)', inflationHelp: 'Uma hipótese de cenário, não uma previsão', yearsLabel: 'Horizonte temporal (anos)', yearsHelp: 'Escolha de 1 a 80 anos', cashFlowLabel: 'Fluxo de caixa anual', cashFlowHelp: 'Adicionado ao saldo ou retirado dele todos os anos', cashFlowModeLabel: 'Cenário de fluxo', noCashFlowOption: 'Sem fluxo recorrente', contributionOption: 'Adicionar todos os anos', withdrawalOption: 'Retirar todos os anos', costEquivalentLabel: 'Custo equivalente final', realValueLabel: 'Valor final em dinheiro de hoje', nominalBalanceLabel: 'Saldo nominal final', purchasingPowerLossLabel: 'Poder de compra perdido', todayLabel: 'Hoje', endLabel: 'Fim do horizonte', costLineLabel: 'Custo da mesma cesta', realLineLabel: 'Poder de compra do dinheiro sem alteração', balanceLineLabel: 'Saldo do cenário em dinheiro de hoje', chartDescription: 'Linha do tempo da inflação com custos crescentes, poder de compra em queda e saldo do cenário', chartNote: 'Cada linha é comparada com o valor inicial', milestoneTitle: 'Marcos na mesma moeda', yearHeader: 'Ano', costHeader: 'Custo equivalente', realHeader: 'Dinheiro sem alteração', balanceHeader: 'Saldo real', methodTitle: 'Como funciona a linha do tempo', methodText: 'O custo equivalente é o valor inicial multiplicado por (1 + inflação anual) elevado ao número de anos. O valor do dinheiro sem alteração é o valor inicial dividido pelo mesmo fator. Uma contribuição é adicionada no fim de cada ano e um saque é subtraído; o saldo para em zero.', limitationText: 'Este é um modelo de cenário transparente, não uma consulta histórica do IPC, uma previsão de retorno ou aconselhamento financeiro pessoal. A sua cesta pode ser diferente de um índice de preços ao consumidor publicado, e a inflação real pode mudar a cada ano.', emptyMessage: 'Introduza um valor positivo, uma taxa acima de -100%, um número inteiro de anos entre 1 e 80 e um fluxo não negativo.', contributionSummary: 'A linha tracejada mostra o valor atual do saldo depois das contribuições recorrentes, sem incluir retorno de investimento.', withdrawalSummary: 'A linha tracejada mostra o valor atual do saldo depois dos saques recorrentes, sem incluir retorno de investimento.', noCashFlowSummary: 'As linhas contínuas isolam a inflação: uma mostra o custo futuro da mesma cesta e a outra o que o dinheiro sem alteração pode comprar.', depletionWarning: 'O cenário de saques chega a zero no ano {year}; os anos seguintes permanecem em zero.', scenarioNote: 'Apenas cenário', currencyHint: 'A mesma moeda do valor inicial', yearsSuffix: 'anos', amountSuffix: 'na mesma moeda do seu valor inicial',
};
const faq = [
  { question: 'Como a inflação reduz o poder de compra?', answer: 'Quando o nível geral de preços sobe, o mesmo valor compra menos bens e serviços. A calculadora mostra esse efeito dividindo o dinheiro sem alteração pelo fator de inflação acumulado.' },
  { question: 'Qual é a diferença entre custo equivalente e valor real?', answer: 'O custo equivalente é o valor futuro necessário para comprar o que o valor inicial compra hoje. O valor real mostra, em dinheiro de hoje, o que o dinheiro sem alteração compra no fim do período.' },
  { question: 'O que incluem os cenários de contribuição e saque?', answer: 'Eles adicionam ou subtraem o fluxo no fim de cada ano. Não incluem retornos, impostos, taxas ou juros, e o saldo de saques não pode ficar abaixo de zero.' },
  { question: 'A taxa de inflação é uma previsão?', answer: 'Não. É uma hipótese para explorar a sensibilidade. A inflação real pode variar, e um índice publicado pode não representar os gastos da sua família.' },
];
const howTo = [
  { name: 'Introduza um valor inicial', text: 'Use o valor cujo poder de compra futuro deseja analisar e mantenha uma só moeda.' },
  { name: 'Defina um cenário de inflação', text: 'Introduza uma taxa anual e um horizonte inteiro. Teste várias taxas para comparar a sensibilidade.' },
  { name: 'Adicione um fluxo opcional', text: 'Escolha Adicionar todos os anos ou Retirar todos os anos e introduza o valor. Use Sem fluxo recorrente para isolar a inflação.' },
  { name: 'Leia as curvas e os marcos', text: 'Compare o custo equivalente final com o valor final em dinheiro de hoje e consulte a tabela.' },
];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, inLanguage: 'pt' };
const seo = [
  { type: 'title' as const, text: 'Use uma linha do tempo da inflação para planejar o poder de compra', level: 2 },
  { type: 'paragraph' as const, html: '<p>A inflação altera o nível de preços, por isso um valor que não muda pode comprar menos no futuro. Esta calculadora separa o dinheiro necessário para comprar a mesma cesta do poder de compra que o dinheiro sem alteração conserva.</p>' },
  { type: 'paragraph' as const, html: '<p>Introduza um valor inicial, uma hipótese de inflação anual e um horizonte. A linha do tempo acumula a taxa todos os anos e mostra o custo equivalente a subir enquanto o poder de compra do dinheiro cai.</p>' },
  { type: 'title' as const, text: 'As duas leituras principais', level: 3 },
  { type: 'table' as const, headers: ['Leitura', 'Fórmula', 'Pergunta'], rows: [['Custo equivalente', 'Valor inicial x (1 + inflação)^anos', 'Quanto seria necessário para a mesma cesta?'], ['Poder do dinheiro sem alteração', 'Valor inicial / (1 + inflação)^anos', 'O que pode comprar no fim em dinheiro de hoje?'], ['Poder de compra perdido', '(1 - 1 / fator de preços) x 100', 'Que parte do poder inicial deixou de estar disponível?']] },
  { type: 'paragraph' as const, html: '<p>Com inflação anual de 3%, 1.000 tornam-se um custo equivalente de cerca de 1.344 após dez anos. Se os 1.000 permanecerem em dinheiro, o seu poder de compra será cerca de 744 em dinheiro de hoje.</p>' },
  { type: 'title' as const, text: 'Por que a capitalização importa', level: 3 },
  { type: 'paragraph' as const, html: '<p>As taxas anuais acumulam-se porque os preços de cada ano são a base do seguinte. Dez anos a 3% não são um ajuste fixo de 30%: o fator é 1,03 elevado a dez, cerca de 1,344.</p>' },
  { type: 'list' as const, items: ['Teste uma taxa baixa, central e alta.', 'Use a tabela de marcos para encontrar despesas que ficam relevantes.', 'Compare o custo equivalente com um objetivo de poupança, rendimento ou reforma.', 'Registe a hipótese e a data e altere-as quando os dados mudarem.'] },
  { type: 'title' as const, text: 'Adicionar contribuições ou saques', level: 3 },
  { type: 'paragraph' as const, html: '<p>O cenário de fluxo torna a linha do tempo útil para um plano de poupança ou despesa sem esconder o efeito da inflação. A contribuição é adicionada ao saldo nominal no fim do ano, o saque é subtraído e o saldo para em zero quando se esgota.</p>' },
  { type: 'paragraph' as const, html: '<p>A linha tracejada do saldo é convertida para dinheiro de hoje com o mesmo fator de inflação. Não é uma projeção de investimento: não inclui juros, retorno de mercado, impostos, taxas ou crescimento das contribuições.</p>' },
  { type: 'tip' as const, title: 'Use um intervalo, não uma promessa', html: '<p>Os índices de preços descrevem uma cesta média, enquanto a sua renda, energia, alimentação e saúde podem evoluir de outra forma. Teste várias taxas.</p>' },
  { type: 'title' as const, text: 'O que a linha do tempo não pode dizer', level: 3 },
  { type: 'paragraph' as const, html: '<p>A ferramenta não procura dados históricos do IPC, não prevê a inflação e não recomenda investimentos. Também não modela taxas anuais variáveis, retornos, juros de dívida ou fluxos irregulares.</p>' },
  { type: 'paragraph' as const, html: '<p>Para uma decisão importante, compare o resultado com um índice de preços adequado, as suas despesas reais e as condições do produto ou rendimento. Um resultado matematicamente consistente pode não descrever bem a sua família.</p>' },
];
export const content: ToolLocaleContent<InflationPurchasingPowerUI> = { slug: 'calculadora-linha-tempo-poder-compra-inflacao', title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo };
