import { bibliography } from '../bibliography';
import type { WithContext, FAQPage, HowTo, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { InflationPurchasingPowerUI } from '../ui';

const title = 'Kalkylator för inflation och köpkraft över tid';
const description = 'Se hur ett antagande om årlig inflation ändrar beloppet som krävs för att bevara köpkraften och kontantens verkliga värde.';
const ui: InflationPurchasingPowerUI = {
  amountLabel: 'Startbelopp', amountHelp: 'Använd samma valuta genom hela beräkningen', inflationLabel: 'Årlig inflation (%)', inflationHelp: 'Ett scenarioantagande, inte en prognos', yearsLabel: 'Tidshorisont (år)', yearsHelp: 'Välj 1 till 80 år', cashFlowLabel: 'Årligt kassaflöde', cashFlowHelp: 'Läggs till eller dras från saldot varje år', cashFlowModeLabel: 'Kassaflödesscenario', noCashFlowOption: 'Inget återkommande flöde', contributionOption: 'Lägg till varje år', withdrawalOption: 'Ta ut varje år', costEquivalentLabel: 'Kostnadsekvivalent vid slutet', realValueLabel: 'Slutvärde i dagens pengar', nominalBalanceLabel: 'Nominellt slutsaldo', purchasingPowerLossLabel: 'Förlorad köpkraft', todayLabel: 'I dag', endLabel: 'Tidshorisontens slut', costLineLabel: 'Kostnad för samma varukorg', realLineLabel: 'Oförändrade kontantas köpkraft', balanceLineLabel: 'Scenariosaldo i dagens pengar', chartDescription: 'Inflationslinje som visar stigande kostnad, fallande köpkraft och scenariosaldo', chartNote: 'Varje linje mäts mot startbeloppet', milestoneTitle: 'Milstolpar i samma valuta', yearHeader: 'År', costHeader: 'Kostnadsekvivalent', realHeader: 'Oförändrade kontanter', balanceHeader: 'Reellt saldo', methodTitle: 'Så fungerar tidslinjen', methodText: 'Kostnadsekvivalenten är startbeloppet multiplicerat med (1 + årlig inflation) upphöjt till antalet år. Värdet av oförändrade kontanter är startbeloppet delat med samma faktor. Ett tillskott läggs till i slutet av varje år och ett uttag dras av; saldot stannar vid noll.', limitationText: 'Detta är en transparent scenariomodell, inte en historisk KPI-sökning, avkastningsprognos eller personlig finansiell rådgivning. Din varukorg kan skilja sig från ett publicerat konsumentprisindex och den faktiska inflationen kan ändras från år till år.', emptyMessage: 'Ange ett positivt belopp, en ränta över -100 %, ett helt antal år från 1 till 80 och ett icke-negativt kassaflöde.', contributionSummary: 'Den streckade linjen visar saldots värde i dag efter återkommande insättningar, utan investeringsavkastning.', withdrawalSummary: 'Den streckade linjen visar saldots värde i dag efter återkommande uttag, utan investeringsavkastning.', noCashFlowSummary: 'De heldragna linjerna isolerar inflationen: den ena visar framtida kostnad för samma varukorg och den andra vad oförändrade kontanter kan köpa.', depletionWarning: 'Uttagsscenariot når noll år {year}; senare år ligger kvar på noll.', scenarioNote: 'Endast scenario', currencyHint: 'Samma valuta som startbeloppet', yearsSuffix: 'år', amountSuffix: 'i samma valuta som startbeloppet',
};
const faq = [
  { question: 'Hur minskar inflationen köpkraften?', answer: 'När den allmänna prisnivån stiger köper samma belopp färre varor och tjänster. Kalkylatorn visar effekten genom att dela oförändrade kontanter med den sammansatta inflationsfaktorn.' },
  { question: 'Vad är skillnaden mellan kostnadsekvivalent och realt värde?', answer: 'Kostnadsekvivalenten är det framtida belopp som behövs för samma varukorg. Realt värde visar vad det oförändrade startbeloppet kan köpa vid periodens slut, uttryckt i dagens pengar.' },
  { question: 'Vad ingår i scenarierna för insättningar och uttag?', answer: 'Kassaflödet läggs till eller dras av i slutet av varje år. Avkastning, skatt, avgifter och ränta ingår inte, och ett uttagssaldo kan inte bli negativt.' },
  { question: 'Är inflationstakten en förutsägelse?', answer: 'Nej. Det är ett antagande för att undersöka känslighet. Faktisk inflation kan variera och ett publicerat prisindex kanske inte motsvarar hushållets utgifter.' },
];
const howTo = [
  { name: 'Ange ett startbelopp', text: 'Använd beloppet vars framtida köpkraft du vill undersöka och håll dig till en valuta.' },
  { name: 'Ställ in ett inflationsscenario', text: 'Ange en årlig takt och en tidshorisont i hela år. Jämför flera nivåer för att se känsligheten.' },
  { name: 'Lägg till ett valfritt kassaflöde', text: 'Välj Lägg till varje år eller Ta ut varje år och ange beloppet. Välj inget återkommande flöde för att isolera inflationen.' },
  { name: 'Läs kurvor och milstolpar', text: 'Jämför slutkostnaden med slutvärdet i dagens pengar och granska milstolpetabellen.' },
];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, inLanguage: 'sv' };
const seo = [
  { type: 'title' as const, text: 'Använd en inflationstidslinje för att planera köpkraft', level: 2 },
  { type: 'paragraph' as const, html: '<p>Inflation förändrar prisnivån, så ett oförändrat belopp kan köpa mindre i framtiden. Den här kalkylatorn skiljer på hur mycket som behövs för samma varukorg och hur mycket köpkraft oförändrade kontanter behåller.</p>' },
  { type: 'paragraph' as const, html: '<p>Ange startbelopp, årligt inflationsantagande och tidshorisont. Tidslinjen räknar ihop takten varje år och visar stigande kostnadsekvivalent bredvid fallande köpkraft.</p>' },
  { type: 'title' as const, text: 'De två viktigaste värdena', level: 3 },
  { type: 'table' as const, headers: ['Värde', 'Formel', 'Fråga'], rows: [['Kostnadsekvivalent', 'Startbelopp x (1 + inflation)^år', 'Hur mycket behövs för samma varukorg?'], ['Köpkraft hos kontanter', 'Startbelopp / (1 + inflation)^år', 'Vad kan beloppet köpa i dagens pengar?'], ['Förlorad köpkraft', '(1 - 1 / prisfaktor) x 100', 'Hur stor del av köpkraften saknas?']] },
  { type: 'paragraph' as const, html: '<p>Vid 3 % årlig inflation blir 1 000 en kostnadsekvivalent på ungefär 1 344 efter tio år. Om 1 000 ligger kvar som kontanter motsvarar köpkraften cirka 744 i dagens pengar.</p>' },
  { type: 'title' as const, text: 'Varför ränta på ränta spelar roll', level: 3 },
  { type: 'paragraph' as const, html: '<p>Årliga inflationstal staplas eftersom varje års priser blir bas för nästa år. Tio år med 3 % är därför inte en platt justering på 30 %: faktorn är 1,03 upphöjt till tio, ungefär 1,344.</p>' },
  { type: 'list' as const, items: ['Kör ett lågt, centralt och högt antagande.', 'Använd milstolparna för utgifter som blir märkbart dyrare.', 'Jämför kostnadsekvivalenten med ett sparmål, en inkomst eller pension.', 'Skriv ned antagande och datum och ändra dem när underlaget ändras.'] },
  { type: 'title' as const, text: 'Lägga till insättningar eller uttag', level: 3 },
  { type: 'paragraph' as const, html: '<p>Kassaflödesscenariot gör tidslinjen användbar för sparande eller konsumtion utan att dölja inflationen. En insättning läggs till det nominella saldot vid årets slut, medan ett uttag dras av och saldot stannar på noll när pengarna tar slut.</p>' },
  { type: 'paragraph' as const, html: '<p>Den streckade saldolinjen räknas om till dagens pengar med samma inflationsfaktor. Det är ingen investeringsprognos: ränta, marknadsavkastning, skatt, avgifter och växande insättningar ingår inte.</p>' },
  { type: 'tip' as const, title: 'Använd ett intervall, inte ett löfte', html: '<p>Prisindex beskriver en genomsnittlig varukorg, medan ditt boende, din energi, mat och vård kan utvecklas annorlunda. Testa flera inflationstal.</p>' },
  { type: 'title' as const, text: 'Vad tidslinjen inte kan säga', level: 3 },
  { type: 'paragraph' as const, html: '<p>Verktyget hämtar inte historisk KPI, förutser inte inflation och rekommenderar inte investeringar. Varierande årstal, tillgångsavkastning, skuldränta och oregelbundna kassaflöden modelleras inte.</p>' },
  { type: 'paragraph' as const, html: '<p>Vid ett viktigt beslut bör du jämföra resultatet med ett relevant prisindex, dina faktiska utgifter och villkoren för produkten eller inkomsten. Ett matematiskt konsekvent resultat kan ändå beskriva ditt hushåll dåligt.</p>' },
];
export const content: ToolLocaleContent<InflationPurchasingPowerUI> = { slug: 'inflation-kopkraft-tidslinje-kalkylator', title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo };
