import { bibliography } from '../bibliography';
import type { WithContext, FAQPage, HowTo, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { InflationPurchasingPowerUI } from '../ui';

const title = 'Enflasyon ve satın alma gücü zaman çizelgesi hesaplayıcısı';
const description = 'Yıllık enflasyon varsayımının satın alma gücünü korumak için gereken tutarı ve nakdin reel değerini nasıl değiştirdiğini görün.';
const ui: InflationPurchasingPowerUI = {
  amountLabel: 'Başlangıç tutarı', amountHelp: 'Hesaplama boyunca aynı para birimini kullanın', inflationLabel: 'Yıllık enflasyon oranı (%)', inflationHelp: 'Bir senaryo varsayımıdır, tahmin değildir', yearsLabel: 'Zaman aralığı (yıl)', yearsHelp: '1 ile 80 yıl arasında seçin', cashFlowLabel: 'Yıllık nakit akışı', cashFlowHelp: 'Her yıl bakiyeye eklenir veya bakiyeden çıkarılır', cashFlowModeLabel: 'Nakit akışı senaryosu', noCashFlowOption: 'Tekrarlanan akış yok', contributionOption: 'Her yıl ekle', withdrawalOption: 'Her yıl çek', costEquivalentLabel: 'Dönem sonu eşdeğer maliyet', realValueLabel: 'Bugünün parasıyla dönem sonu değeri', nominalBalanceLabel: 'Dönem sonu nominal bakiye', purchasingPowerLossLabel: 'Kaybedilen satın alma gücü', todayLabel: 'Bugün', endLabel: 'Dönem sonu', costLineLabel: 'Aynı sepeti koruma maliyeti', realLineLabel: 'Değişmeyen nakdin satın alma gücü', balanceLineLabel: 'Senaryo bakiyesi bugünün parasıyla', chartDescription: 'Artan maliyeti, azalan satın alma gücünü ve senaryo bakiyesini gösteren enflasyon zaman çizelgesi', chartNote: 'Her çizgi başlangıç tutarıyla karşılaştırılır', milestoneTitle: 'Aynı para biriminde kilometre taşları', yearHeader: 'Yıl', costHeader: 'Eşdeğer maliyet', realHeader: 'Değişmeyen nakit', balanceHeader: 'Reel bakiye', methodTitle: 'Zaman çizelgesi nasıl çalışır', methodText: 'Eşdeğer maliyet, başlangıç tutarının (1 + yıllık enflasyon oranı) üzeri yıl sayısıyla çarpılmasıdır. Değişmeyen nakdin değeri, başlangıç tutarının aynı faktöre bölünmesidir. Katkı yıl sonunda eklenir, çekim yıl sonunda düşülür ve bakiye sıfırın altına inmez.', limitationText: 'Bu şeffaf bir senaryo modelidir; geçmiş TÜFE sorgusu, getiri tahmini veya kişisel finansal danışmanlık değildir. Hane sepetiniz yayımlanmış bir tüketici fiyat endeksinden farklı olabilir ve gerçek enflasyon her yıl değişebilir.', emptyMessage: 'Pozitif bir tutar, -100% değerinden büyük bir oran, 1 ile 80 arasında tam yıl sayısı ve negatif olmayan bir nakit akışı girin.', contributionSummary: 'Kesikli çizgi, yatırım getirisi eklenmeden tekrarlanan katkılardan sonra bakiyenin bugünkü değerini gösterir.', withdrawalSummary: 'Kesikli çizgi, yatırım getirisi eklenmeden tekrarlanan çekimlerden sonra bakiyenin bugünkü değerini gösterir.', noCashFlowSummary: 'Düz çizgiler yalnızca enflasyonu gösterir: biri aynı sepetin gelecekteki maliyetini, diğeri değişmeyen nakdin alabileceklerini gösterir.', depletionWarning: 'Çekim senaryosu {year}. yılda sıfıra ulaşır; sonraki yıllar sıfırda kalır.', scenarioNote: 'Yalnızca senaryo', currencyHint: 'Başlangıç tutarıyla aynı para birimi', yearsSuffix: 'yıl', amountSuffix: 'başlangıç tutarınızla aynı para biriminde',
};
const faq = [
  { question: 'Enflasyon satın alma gücünü nasıl azaltır?', answer: 'Genel fiyat düzeyi yükseldiğinde aynı tutar daha az mal ve hizmet alır. Hesaplayıcı bu etkiyi değişmeyen nakdi bileşik enflasyon faktörüne bölerek modeller.' },
  { question: 'Eşdeğer maliyet ile reel değer arasındaki fark nedir?', answer: 'Eşdeğer maliyet, başlangıç tutarının bugün aldığı sepeti gelecekte almak için gereken tutardır. Reel değer, değişmeyen paranın dönemin sonunda bugünün parasıyla ne alabileceğini gösterir.' },
  { question: 'Katkı ve çekim senaryoları neleri içerir?', answer: 'Nakit akışını her yılın sonunda ekler veya çıkarır. Getiri, vergi, ücret ve faiz içermez; çekim bakiyesi sıfırın altına düşemez.' },
  { question: 'Enflasyon oranı bir tahmin midir?', answer: 'Hayır. Duyarlılığı incelemek için kullanılan bir varsayımdır. Gerçek enflasyon değişebilir ve yayımlanan bir endeks hanenizin harcama düzenine uymayabilir.' },
];
const howTo = [
  { name: 'Başlangıç tutarını girin', text: 'Gelecekteki satın alma gücünü incelemek istediğiniz tutarı girin ve tek para birimi kullanın.' },
  { name: 'Enflasyon senaryosunu ayarlayın', text: 'Yıllık oranı ve tam yıl olarak zaman aralığını girin. Duyarlılığı görmek için birkaç oran deneyin.' },
  { name: 'İsteğe bağlı nakit akışı ekleyin', text: 'Her yıl ekle veya Her yıl çek seçeneğini seçip tutarı girin. Sadece enflasyonu görmek için Tekrarlanan akış yok seçeneğini kullanın.' },
  { name: 'Eğrileri ve kilometre taşlarını okuyun', text: 'Dönem sonu maliyetini bugünün parasıyla değerle karşılaştırın ve tabloyu inceleyin.' },
];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, inLanguage: 'tr' };
const seo = [
  { type: 'title' as const, text: 'Satın alma gücünü planlamak için enflasyon zaman çizelgesini kullanın', level: 2 },
  { type: 'paragraph' as const, html: '<p>Enflasyon fiyat düzeyini değiştirir; bu nedenle değişmeyen bir para tutarı gelecekte daha az şey alabilir. Bu hesaplayıcı aynı sepet için gereken tutarı, değişmeyen nakdin koruduğu satın alma gücünden ayırır.</p>' },
  { type: 'paragraph' as const, html: '<p>Başlangıç tutarını, yıllık enflasyon varsayımını ve dönemi girin. Zaman çizelgesi oranı her yıl bileştirir; eşdeğer maliyeti yükselirken değişmeyen nakdin gücünü düşerken gösterir.</p>' },
  { type: 'title' as const, text: 'İki temel okuma', level: 3 },
  { type: 'table' as const, headers: ['Değer', 'Formül', 'Soru'], rows: [['Eşdeğer maliyet', 'Başlangıç x (1 + enflasyon)^yıl', 'Aynı sepet için dönem sonunda ne gerekir?'], ['Değişmeyen nakdin gücü', 'Başlangıç / (1 + enflasyon)^yıl', 'Bugünün parasıyla dönem sonunda ne alabilir?'], ['Kaybedilen güç', '(1 - 1 / fiyat faktörü) x 100', 'Başlangıç gücünün ne kadarı kullanılamaz?']] },
  { type: 'paragraph' as const, html: '<p>Yıllık %3 enflasyonda 1.000, on yıl sonra yaklaşık 1.344 eşdeğer maliyete dönüşür. 1.000 nakit olarak değişmeden kalırsa satın alma gücü bugünün parasıyla yaklaşık 744 olur.</p>' },
  { type: 'title' as const, text: 'Bileşik etkinin önemi', level: 3 },
  { type: 'paragraph' as const, html: '<p>Yıllık oranlar birleşir, çünkü her yılın fiyatları sonraki yılın temelidir. %3 ile on yıl düz bir %30 ayarlama değildir: faktör 1,03 üzeri on, yani yaklaşık 1,344 olur.</p>' },
  { type: 'list' as const, items: ['Düşük, orta ve yüksek oranları deneyin.', 'Belirgin şekilde pahalanan harcamaları kilometre taşlarıyla görün.', 'Eşdeğer maliyeti tasarruf hedefi, gelir veya emekli maaşıyla karşılaştırın.', 'Varsayımı ve tarihi not edin; veriler değişince güncelleyin.'] },
  { type: 'title' as const, text: 'Katkı veya çekim eklemek', level: 3 },
  { type: 'paragraph' as const, html: '<p>Nakit akışı senaryosu, enflasyon etkisini gizlemeden tasarruf veya harcama planını incelemeyi sağlar. Katkı nominal bakiyeye yıl sonunda eklenir, çekim çıkarılır ve para tükenince bakiye sıfırda kalır.</p>' },
  { type: 'paragraph' as const, html: '<p>Kesikli bakiye çizgisi aynı enflasyon faktörüyle bugünün parasına çevrilir. Bu bir yatırım projeksiyonu değildir: faiz, piyasa getirisi, vergi, ücret ve katkı büyümesi içerilmez.</p>' },
  { type: 'tip' as const, title: 'Vaat yerine aralık kullanın', html: '<p>Fiyat endeksleri ortalama bir sepeti anlatır; kira, enerji, gıda ve sağlık harcamalarınız farklı değişebilir. Birkaç oranı test edin.</p>' },
  { type: 'title' as const, text: 'Zaman çizelgesinin söyleyemeyecekleri', level: 3 },
  { type: 'paragraph' as const, html: '<p>Araç geçmiş TÜFE verisi çekmez, enflasyonu tahmin etmez ve yatırım önermez. Değişen yıllık oranlar, varlık getirileri, borç faizi ve düzensiz nakit akışları modellenmez.</p>' },
  { type: 'paragraph' as const, html: '<p>Önemli bir kararda sonucu uygun bir fiyat endeksi, gerçek harcama kayıtlarınız ve ürün ya da gelirin koşullarıyla karşılaştırın. Matematiksel olarak tutarlı bir sonuç hanenizi yine de iyi anlatmayabilir.</p>' },
];
export const content: ToolLocaleContent<InflationPurchasingPowerUI> = { slug: 'enflasyon-satin-alma-gucu-zaman-cizelgesi-hesaplama', title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo };
