import type { WithContext, FAQPage, HowTo, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { DividendYieldUI } from '../ui';
import { bibliography } from '../bibliography';

const title = 'Dividendenrendite Rechner für Aktien';
const description = 'Berechne Brutto- und Nettodividendenrendite, Jahreseinkommen und ein Wachstumsszenario aus deinen eigenen Aktienwerten.';
const faq = [
  { question: 'Wie berechne ich die Dividendenrendite?', answer: 'Multipliziere eine Dividende pro Zahlung mit der Anzahl der Zahlungen pro Jahr, teile durch den Aktienkurs und multipliziere mit 100. Bei einer vierteljährlichen Zahlung wird die Zahlung zuerst mit vier multipliziert.' },
  { question: 'Soll ich eine jährliche oder vierteljährliche Dividende eingeben?', answer: 'Wähle den Rhythmus, der zum eingegebenen Betrag passt. Der Rechner rechnet vierteljährliche Zahlungen automatisch auf ein Jahr hoch.' },
  { question: 'Was ist der Unterschied zwischen Brutto- und Nettodividendeneinkommen?', answer: 'Das Bruttoeinkommen ist die jährliche Dividende vor dem eingegebenen Quellensteuersatz. Das Nettoeinkommen zieht diesen Satz als einfache Planungsschätzung ab; die tatsächliche Steuer kann abweichen.' },
  { question: 'Bedeutet eine hohe Dividendenrendite, dass eine Aktie besser ist?', answer: 'Nein. Die Rendite kann durch einen fallenden Aktienkurs steigen, und ein Unternehmen kann seine Dividende kürzen oder einstellen. Prüfe Unternehmen, Ausschüttung und Risiken separat.' },
];
const howTo = [
  { name: 'Aktienkurs eingeben', text: 'Gib den Preis pro Aktie ein, den du als Bezugswert verwenden möchtest.' },
  { name: 'Dividendenzahlung ergänzen', text: 'Gib die Dividende pro Aktie ein und wähle, ob sie jährlich oder vierteljährlich gezahlt wird.' },
  { name: 'Rendite und Einkommen prüfen', text: 'Lies Bruttorendite, Rendite nach Quellensteuer und Jahreseinkommen ab. Verwende Wachstum nur als separates Szenario.' },
];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, inLanguage: 'de' };

const ui: DividendYieldUI = {
  priceLabel: 'Aktienkurs', priceHelp: 'Betrag in deiner Währung eingeben', dividendLabel: 'Dividende pro Zahlung', dividendHelp: 'Bargeldbetrag pro Aktie in derselben Währung', cadenceLabel: 'Zahlungsrhythmus', annualOption: 'Jährlich', quarterlyOption: 'Vierteljährlich', sharesLabel: 'Gehaltene Aktien', sharesHelp: 'Optional für Einkommenssummen', withholdingLabel: 'Quellensteuersatz (%)', withholdingHelp: 'Einfache Schätzung des Nettoeinkommens', growthLabel: 'Angenommenes Wachstum (%)', growthHelp: 'Optionale Eingabe für das Zukunftsszenario', grossYieldLabel: 'Bruttodividendenrendite', netYieldLabel: 'Nach Quellensteuer', grossIncomeLabel: 'Bruttojahreseinkommen', netIncomeLabel: 'Nettojahreseinkommen', annualDividendLabel: 'Jährliche Dividende', priceShareLabel: 'Aktienkurs', couponNote: 'Der Streifen setzt die jährliche Dividende ins Verhältnis zum eingegebenen Aktienkurs.', forwardTitle: 'Zukunftsszenario mit deiner Wachstumsannahme', forwardYieldLabel: 'Rendite bei eingegebenem Dividendenwachstum', forwardDividendLabel: 'Zukünftige Dividende pro Aktie', growthNote: 'Dies ist ein Szenario, keine Prognose.', formulaTitle: 'So funktioniert die Berechnung', formulaText: 'Die jährliche Dividende pro Aktie entspricht dem Zahlungsbetrag multipliziert mit der Zahl der Zahlungen. Die Bruttorendite entspricht der jährlichen Dividende geteilt durch den Aktienkurs mal 100. Für das Nettoeinkommen wird der Quellensteuersatz vom Bruttoeinkommen abgezogen. Wachstum verändert nur das Zukunftsszenario.', riskNote: 'Die Dividendenrendite ist ein Verhältnis aus deinen Eingaben. Kursgewinne, Kursverluste, Gebühren, Kürzungen, Inflation und Änderungen der Ausschüttung sind nicht enthalten.', emptyMessage: 'Gib einen positiven Aktienkurs und eine nicht negative Dividende ein, um ein Ergebnis zu sehen.', annualSuffix: 'pro Jahr', perShareSuffix: 'pro Aktie', percentageSuffix: '%',
};

export const content: ToolLocaleContent<DividendYieldUI> = {
  slug: 'dividendenrendite-rechner-aktien', title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema],
  seo: [
    { type: 'title', text: 'Dividendenrendite verstehen und für Aktien berechnen', level: 2 },
    { type: 'paragraph', html: '<p>Die Dividendenrendite vergleicht die jährliche Barausschüttung einer Aktie mit dem verwendeten Aktienkurs. Dieser Rechner rechnet eine Dividende pro Zahlung auf ein Jahr hoch, teilt sie durch den Aktienkurs und zeigt das Ergebnis als Prozentsatz. Zusätzlich kannst du dein Jahreseinkommen, eine einfache Quellensteuerschätzung und ein separates Wachstumsszenario berechnen.</p>' },
    { type: 'paragraph', html: '<p>Das Ergebnis ist ein Verhältnis und keine versprochene Rendite. Kursveränderungen, Gebühren, Währungsbewegungen, Sonderdividenden und das Risiko einer Kürzung oder Streichung sind nicht enthalten. Nutze die Zahl als Ausgangspunkt für den Vergleich und untersuche danach das Unternehmen und die konkrete Aktie.</p>' },
    { type: 'title', text: 'Die Formel der Dividendenrendite', level: 3 },
    { type: 'paragraph', html: '<p><strong>Dividendenrendite = jährliche Dividende pro Aktie / Aktienkurs x 100</strong>. Bei vierteljährlichen Zahlungen wird der Betrag vor der Berechnung mit vier multipliziert. Bei einer jährlichen Zahlung wird der eingegebene Betrag direkt verwendet.</p>' },
    { type: 'table', headers: ['Wert', 'Berechnung', 'Bedeutung'], rows: [['Jährliche Dividende pro Aktie', 'Zahlungsbetrag x Zahlungen pro Jahr', 'Macht jährliche und vierteljährliche Zahlungen vergleichbar'], ['Bruttodividendenrendite', 'Jährliche Dividende / Aktienkurs x 100', 'Zeigt die Ausschüttung als Prozentsatz des Bezugskurses'], ['Bruttojahreseinkommen', 'Jährliche Dividende pro Aktie x Aktien', 'Schätzt das Einkommen vor Quellensteuer'], ['Nettojahreseinkommen', 'Bruttoeinkommen x (1 - Quellensteuersatz / 100)', 'Einfache Schätzung nach dem eingegebenen Satz']] },
    { type: 'title', text: 'Beispiel mit jährlicher und vierteljährlicher Zahlung', level: 3 },
    { type: 'paragraph', html: '<p>Kostet eine Aktie 100 in deiner Währung und zahlt sie vierteljährlich 1, beträgt die jährliche Dividende 1 x 4 = 4. Die Bruttodividendenrendite ist dann 4 / 100 x 100 = 4 %. Bei 50 Aktien ergibt sich ein Bruttojahreseinkommen von 200 vor Quellensteuer.</p>' },
    { type: 'paragraph', html: '<p>Würde dieselbe Aktie einmal jährlich 4 zahlen, bliebe die Rendite ebenfalls 4 %. Der Zahlungsrhythmus ändert nur die Hochrechnung. Eine falsche Auswahl des Rhythmus kann das Ergebnis daher deutlich verfälschen.</p>' },
    { type: 'title', text: 'Warum der Aktienkurs die Rendite verändert', level: 3 },
    { type: 'paragraph', html: '<p>Eine Dividendenrendite kann sich ändern, obwohl das Unternehmen seine Dividende nicht verändert. Bei einer jährlichen Dividende von 4 ergibt ein Kurs von 100 eine Rendite von 4 %, ein Kurs von 80 dagegen 5 %. Die höhere Zahl bedeutet nicht automatisch höhere Gewinne; sie kann lediglich einen niedrigeren Marktpreis widerspiegeln.</p>' },
    { type: 'paragraph', html: '<p>Verwende beim Vergleich mehrerer Aktien dieselbe Kurslogik, etwa den aktuellen Kurs, den Schlusskurs eines bestimmten Tages oder deinen Einstandskurs. Kennzeichne die Wahl klar, denn Kursdatum und Dividendenzeitraum beeinflussen die Aussage.</p>' },
    { type: 'title', text: 'Bruttorendite, Quellensteuer und Einkommen unterscheiden', level: 3 },
    { type: 'comparative', columns: 3, items: [{ title: 'Bruttorendite', description: 'Jährliche Dividende pro Aktie im Verhältnis zum Bezugskurs.', points: ['Vergleicht Ausschüttung und Preis', 'Zieht keine Quellensteuer ab', 'Enthält keine Kursgewinne oder Verluste'] }, { title: 'Rendite nach Quellensteuer', description: 'Bruttorendite abzüglich des eingegebenen Prozentsatzes.', points: ['Einfache Planungsschätzung', 'Steuerregeln können abweichen', 'Kein Ergebnis für eine Steuererklärung'], highlight: true }, { title: 'Jahreseinkommen', description: 'Barausschüttung aus Dividende und Aktienanzahl.', points: ['Brutto vor Quellensteuer', 'Netto verwendet den eingegebenen Satz', 'Hängt von der Aktienanzahl ab'] }] },
    { type: 'paragraph', html: '<p>Quellensteuer ist nicht automatisch deine endgültige Steuerlast. Wohnsitz, Quellenstaat, Depot, Doppelbesteuerungsabkommen und Erstattungsverfahren können eine Rolle spielen. Der Rechner wendet nur deinen eingegebenen Prozentsatz mechanisch an und bestimmt nicht den für dich geltenden Satz.</p>' },
    { type: 'title', text: 'So verwendest du den Rechner sinnvoll', level: 3 },
    { type: 'list', items: ['Gib Aktienkurs und Dividende in derselben Währung und auf derselben zeitlichen Grundlage ein.', 'Wähle jährlich oder vierteljährlich passend zum eingegebenen Zahlungsbetrag.', 'Ergänze die Aktienanzahl, wenn du ein Einkommen statt nur einer Pro-Aktie-Rendite brauchst.', 'Nutze Quellensteuer als klar gekennzeichnete Planungsschätzung und prüfe die Regeln separat.', 'Verwende Wachstum nur zum Testen eines Szenarios, nicht als Vorhersage.', 'Notiere Kursdatum und Dividendenzeitraum, wenn du Ergebnisse vergleichst.'] },
    { type: 'title', text: 'Was eine hohe Dividendenrendite aussagt und was nicht', level: 3 },
    { type: 'paragraph', html: '<p>Eine hohe Rendite kann eine großzügige Ausschüttung bedeuten, aber auch durch einen fallenden Aktienkurs entstehen. Sie ist deshalb ein Anlass zur Recherche und kein eigenständiges Kaufsignal. Prüfe Cashflow, Gewinne, Schulden, Ausschüttungshistorie, Unternehmenspolitik und aktuelle Mitteilungen.</p>' },
    { type: 'tip', title: 'Wachstum als Szenario behandeln', html: '<p>Die Zukunftsansicht wendet den eingegebenen Prozentsatz nur auf die aktuelle Dividende an. Sie modelliert weder Wiederanlage, Kursänderung, Ausschüttungsquote noch künftige Entscheidungen des Unternehmens. Kennzeichne das Ergebnis daher immer als Annahme.</p>' },
    { type: 'title', text: 'Grenzen dieses Dividendenrendite Rechners', level: 3 },
    { type: 'paragraph', html: '<p>Das Tool modelliert eine regelmäßige Dividende pro Aktie, einen jährlichen oder vierteljährlichen Rhythmus, eine optionale Aktienanzahl, einen eingegebenen Quellensteuersatz und ein einstufiges Wachstumsszenario. Es prognostiziert nicht die Gesamtrendite, bewertet keine Dividendensicherheit, behandelt keine Sonderdividenden, rechnet keine Währungen um und erstellt keine lokale Steuerberechnung.</p>' },
  ],
};
