import type { WithContext, FAQPage, HowTo, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { DividendYieldUI } from '../ui';
import { bibliography } from '../bibliography';

const title = 'Calculadora de rentabilidad por dividendo de acciones';
const description = 'Calcula la rentabilidad por dividendo bruta y después de retenciones, los ingresos anuales y un escenario de crecimiento con tus propios datos.';
const faq = [
  { question: '¿Cómo se calcula la rentabilidad por dividendo?', answer: 'Multiplica el dividendo por pago por el número de pagos anuales, divídelo entre el precio de la acción y multiplica por 100. Si el pago es trimestral, primero se multiplica por cuatro.' },
  { question: '¿Debo introducir un dividendo anual o trimestral?', answer: 'Elige la frecuencia que corresponda al importe introducido. La calculadora anualiza automáticamente los pagos trimestrales.' },
  { question: '¿Qué diferencia hay entre ingresos brutos y netos por dividendos?', answer: 'Los ingresos brutos son el dividendo anual antes de la retención introducida. Los ingresos netos restan ese porcentaje como una estimación sencilla; tu fiscalidad real puede ser distinta.' },
  { question: '¿Una rentabilidad por dividendo alta significa que una acción es mejor?', answer: 'No. Puede subir porque ha caído el precio de la acción y la empresa puede reducir o cancelar el dividendo. Analiza la empresa y sus riesgos por separado.' },
];
const howTo = [{ name: 'Introduce el precio de la acción', text: 'Escribe el precio por acción que quieres utilizar como referencia.' }, { name: 'Añade el pago del dividendo', text: 'Introduce el dividendo por acción y elige si es anual o trimestral.' }, { name: 'Revisa la rentabilidad y los ingresos', text: 'Consulta la rentabilidad bruta, la posterior a retenciones y los ingresos anuales. Usa el crecimiento solo como escenario separado.' }];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, inLanguage: 'es' };

const ui: DividendYieldUI = {
  priceLabel: 'Precio de la acción', priceHelp: 'Introduce un importe en tu moneda', dividendLabel: 'Dividendo por pago', dividendHelp: 'Importe en efectivo por acción en la misma moneda', cadenceLabel: 'Frecuencia de pago', annualOption: 'Anual', quarterlyOption: 'Trimestral', sharesLabel: 'Acciones en cartera', sharesHelp: 'Opcional para calcular ingresos', withholdingLabel: 'Retención (%)', withholdingHelp: 'Estimación sencilla del ingreso neto', growthLabel: 'Escenario de crecimiento (%)', growthHelp: 'Dato opcional para el escenario futuro', grossYieldLabel: 'Rentabilidad por dividendo bruta', netYieldLabel: 'Después de retenciones', grossIncomeLabel: 'Ingreso anual bruto', netIncomeLabel: 'Ingreso anual neto', annualDividendLabel: 'Dividendo anual', priceShareLabel: 'Precio de la acción', couponNote: 'La banda convierte el dividendo anual en una proporción del precio de la acción introducido.', forwardTitle: 'Escenario futuro con tu hipótesis de crecimiento', forwardYieldLabel: 'Rentabilidad si el dividendo crece como has indicado', forwardDividendLabel: 'Dividendo futuro por acción', growthNote: 'Es un escenario, no una previsión.', formulaTitle: 'Cómo funciona el cálculo', formulaText: 'El dividendo anual por acción es el importe de cada pago multiplicado por el número de pagos. La rentabilidad bruta es el dividendo anual por acción dividido entre el precio y multiplicado por 100. El ingreso neto aplica la retención al ingreso bruto. El crecimiento solo cambia el escenario futuro.', riskNote: 'La rentabilidad por dividendo es un porcentaje basado en los datos introducidos. No incluye subidas o bajadas de precio, comisiones, recortes, inflación ni el riesgo de que cambie el reparto.', emptyMessage: 'Introduce un precio de acción positivo y un dividendo no negativo para ver el resultado.', annualSuffix: 'al año', perShareSuffix: 'por acción', percentageSuffix: '%',
};

export const content: ToolLocaleContent<DividendYieldUI> = {
  slug: 'calculadora-rentabilidad-dividendo-acciones', title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema],
  seo: [
    { type: 'title', text: 'Qué es la rentabilidad por dividendo y cómo calcularla', level: 2 },
    { type: 'paragraph', html: '<p>La rentabilidad por dividendo compara el dinero que una acción reparte en un año con el precio utilizado como referencia. Esta calculadora convierte un dividendo por pago en un importe anual, lo divide entre el precio de la acción y muestra el resultado como porcentaje. También estima tus ingresos anuales y separa el resultado bruto de una sencilla hipótesis después de retenciones.</p>' },
    { type: 'paragraph', html: '<p>El resultado es una proporción, no una promesa de rentabilidad. No incluye cambios en el precio, comisiones, divisas, dividendos extraordinarios ni el riesgo de que la empresa reduzca, suspenda o cancele el reparto. Úsalo para comparar cifras y después investiga la empresa y el valor concreto.</p>' },
    { type: 'title', text: 'La fórmula de la rentabilidad por dividendo', level: 3 },
    { type: 'paragraph', html: '<p>La fórmula principal es <strong>rentabilidad por dividendo = dividendo anual por acción / precio de la acción x 100</strong>. Si el pago es trimestral, la calculadora lo multiplica por cuatro antes de obtener el porcentaje. Si es anual, utiliza el importe tal como lo has introducido.</p>' },
    { type: 'table', headers: ['Dato', 'Cálculo', 'Para qué sirve'], rows: [['Dividendo anual por acción', 'Importe por pago x pagos al año', 'Pone en la misma base los pagos anuales y trimestrales'], ['Rentabilidad bruta', 'Dividendo anual / precio x 100', 'Muestra el reparto como porcentaje del precio de referencia'], ['Ingreso anual bruto', 'Dividendo anual por acción x acciones', 'Estima el dinero antes de la retención introducida'], ['Ingreso anual neto', 'Ingreso bruto x (1 - retención / 100)', 'Aporta una estimación sencilla después del porcentaje indicado']] },
    { type: 'title', text: 'Ejemplo con pagos anuales y trimestrales', level: 3 },
    { type: 'paragraph', html: '<p>Imagina una acción con precio de 100 en tu moneda y un dividendo de 1 pagado cada trimestre. El dividendo anual es 1 x 4 = 4, por lo que la rentabilidad bruta es 4 / 100 x 100 = 4 %. Con 50 acciones, el ingreso anual bruto estimado sería 200 antes de retenciones.</p>' },
    { type: 'paragraph', html: '<p>Si la misma acción pagara 4 una vez al año, la rentabilidad seguiría siendo del 4 %. La frecuencia solo cambia la anualización. Elegir una frecuencia incorrecta es una de las formas más fáciles de distorsionar el resultado.</p>' },
    { type: 'title', text: 'Por qué el precio cambia la rentabilidad', level: 3 },
    { type: 'paragraph', html: '<p>La rentabilidad puede cambiar aunque la empresa mantenga el mismo dividendo. Con un dividendo anual de 4, un precio de 100 produce un 4 %, mientras que un precio de 80 produce un 5 %. El porcentaje mayor no significa necesariamente que el negocio sea más rentable: puede reflejar solo una caída del precio de mercado.</p>' },
    { type: 'paragraph', html: '<p>Para comparar acciones, usa la misma referencia de precio: el precio actual, el cierre de una fecha concreta o tu precio de compra. Indica cuál has utilizado, porque la fecha del precio y el periodo del dividendo cambian el significado de la comparación.</p>' },
    { type: 'title', text: 'No confundas rentabilidad, retención e ingresos', level: 3 },
    { type: 'comparative', columns: 3, items: [{ title: 'Rentabilidad bruta', description: 'Dividendo anual por acción comparado con el precio de referencia.', points: ['Sirve para comparar reparto y precio', 'No resta retenciones', 'No incluye ganancias ni pérdidas de precio'] }, { title: 'Rentabilidad después de retenciones', description: 'Rentabilidad bruta reducida por el porcentaje introducido.', points: ['Es una hipótesis de planificación', 'La fiscalidad real puede variar', 'No es un resultado para presentar impuestos'], highlight: true }, { title: 'Ingreso anual', description: 'Dinero derivado del dividendo anual y las acciones en cartera.', points: ['El bruto es antes de retenciones', 'El neto usa el porcentaje indicado', 'Depende del número de acciones'] }] },
    { type: 'paragraph', html: '<p>La retención no equivale necesariamente a tu impuesto final. Pueden influir tu residencia, el país de la empresa, el tipo de cuenta, los convenios y los procedimientos de devolución. La calculadora aplica mecánicamente el porcentaje que escribes; no determina qué tipo te corresponde.</p>' },
    { type: 'title', text: 'Cómo usar bien la calculadora', level: 3 },
    { type: 'list', items: ['Introduce precio y dividendo en la misma moneda y con una base temporal comparable.', 'Elige Anual o Trimestral según la frecuencia del importe introducido.', 'Añade las acciones cuando necesites ingresos totales y no solo rentabilidad por acción.', 'Usa la retención como hipótesis explícita y comprueba las reglas aplicables por separado.', 'Utiliza el crecimiento para probar un escenario, no para predecir el reparto futuro.', 'Anota la fecha del precio y el periodo del dividendo al guardar una comparación.'] },
    { type: 'title', text: 'Qué puede indicar una rentabilidad alta y qué no', level: 3 },
    { type: 'paragraph', html: '<p>Una rentabilidad alta puede reflejar un reparto generoso, pero también un precio que ha caído. Por eso debe servir como señal para investigar y no como recomendación automática de compra. Revisa la generación de caja, los beneficios, la deuda, el historial de reparto, la política de dividendos y las comunicaciones recientes.</p>' },
    { type: 'tip', title: 'Trata el crecimiento como un escenario', html: '<p>La vista futura aplica únicamente el porcentaje de crecimiento que escribes al dividendo actual. No modela reinversión, cambios de precio, porcentaje de distribución, crecimiento de beneficios ni decisiones futuras de la empresa. Conserva el resultado etiquetado como hipótesis.</p>' },
    { type: 'title', text: 'Límites de esta calculadora de dividendos', level: 3 },
    { type: 'paragraph', html: '<p>La herramienta modela un pago regular por acción, una frecuencia anual o trimestral, un número opcional de acciones, una retención introducida y un escenario de crecimiento de un solo paso. No predice la rentabilidad total, no valora la seguridad del dividendo, no trata dividendos especiales, no convierte divisas ni calcula tu fiscalidad local.</p>' },
  ],
};
