import type { WithContext, FAQPage, HowTo, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { DividendYieldUI } from '../ui';
import { bibliography } from '../bibliography';

const title = 'Calculateur de rendement des dividendes des actions';
const description = 'Calculez le rendement brut et après prélèvement, le revenu annuel et un scénario de croissance à partir de vos données boursières.';
const faq = [
  { question: 'Comment calculer le rendement du dividende ?', answer: 'Multipliez le dividende par versement par le nombre de versements annuels, divisez par le cours de l action et multipliez par 100. Pour un paiement trimestriel, multipliez d abord par quatre.' },
  { question: 'Dois-je saisir un dividende annuel ou trimestriel ?', answer: 'Choisissez la fréquence correspondant au montant saisi. Le calculateur annualise automatiquement les versements trimestriels.' },
  { question: 'Quelle est la différence entre revenu brut et net ?', answer: 'Le revenu brut est le dividende annuel avant le taux de prélèvement saisi. Le revenu net retire ce taux comme estimation simple; la fiscalité réelle peut être différente.' },
  { question: 'Un rendement élevé signifie-t-il qu une action est meilleure ?', answer: 'Non. Il peut augmenter parce que le cours baisse, et l entreprise peut réduire ou arrêter son dividende. Analysez séparément l entreprise et ses risques.' },
];
const howTo = [{ name: 'Saisir le cours de l action', text: 'Indiquez le prix par action à utiliser comme référence.' }, { name: 'Ajouter le versement', text: 'Saisissez le dividende par action et choisissez une fréquence annuelle ou trimestrielle.' }, { name: 'Lire le rendement et le revenu', text: 'Consultez le rendement brut, celui après prélèvement et le revenu annuel. Utilisez la croissance comme scénario séparé.' }];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, inLanguage: 'fr' };

const ui: DividendYieldUI = {
  priceLabel: 'Cours de l action', priceHelp: 'Saisissez un montant dans votre devise', dividendLabel: 'Dividende par versement', dividendHelp: 'Montant par action dans la même devise', cadenceLabel: 'Fréquence de versement', annualOption: 'Annuel', quarterlyOption: 'Trimestriel', sharesLabel: 'Actions détenues', sharesHelp: 'Facultatif pour le revenu total', withholdingLabel: 'Prélèvement (%)', withholdingHelp: 'Estimation simple du revenu net', growthLabel: 'Scénario de croissance (%)', growthHelp: 'Valeur facultative pour le scénario futur', grossYieldLabel: 'Rendement brut du dividende', netYieldLabel: 'Après prélèvement', grossIncomeLabel: 'Revenu annuel brut', netIncomeLabel: 'Revenu annuel net', annualDividendLabel: 'Dividende annuel', priceShareLabel: 'Cours de l action', couponNote: 'La bande met le dividende annuel en proportion du cours saisi.', forwardTitle: 'Scénario futur avec votre hypothèse de croissance', forwardYieldLabel: 'Rendement si le dividende progresse comme saisi', forwardDividendLabel: 'Dividende futur par action', growthNote: 'Il s agit d un scénario, pas d une prévision.', formulaTitle: 'Comment fonctionne le calcul', formulaText: 'Le dividende annuel par action est le montant du versement multiplié par le nombre de versements. Le rendement brut est le dividende annuel par action divisé par le cours, multiplié par 100. Le revenu net applique le prélèvement au revenu brut. La croissance ne modifie que le scénario futur.', riskNote: 'Le rendement est un ratio basé sur vos données. Il n inclut ni les variations de cours, ni les frais, ni les réductions, ni l inflation, ni le risque d une modification du versement.', emptyMessage: 'Saisissez un cours positif et un dividende non négatif pour voir le résultat.', annualSuffix: 'par an', perShareSuffix: 'par action', percentageSuffix: '%',
};

export const content: ToolLocaleContent<DividendYieldUI> = {
  slug: 'calculateur-rendement-dividende-actions', title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema],
  seo: [
    { type: 'title', text: 'Comprendre et calculer le rendement des dividendes', level: 2 },
    { type: 'paragraph', html: '<p>Le rendement du dividende compare la distribution annuelle en espèces d une action avec le cours de référence. Ce calculateur annualise un versement, le divise par le cours et affiche le résultat en pourcentage. Il estime aussi le revenu annuel et distingue le résultat brut d une hypothèse simple après prélèvement.</p>' },
    { type: 'paragraph', html: '<p>Le résultat est un ratio, pas une promesse de rendement. Il n inclut pas les variations de cours, les frais, les devises, les dividendes exceptionnels ni le risque d une baisse ou d une suppression du dividende. Utilisez-le pour comparer des chiffres, puis étudiez l entreprise et le titre concerné.</p>' },
    { type: 'title', text: 'La formule du rendement du dividende', level: 3 },
    { type: 'paragraph', html: '<p>La formule est <strong>rendement du dividende = dividende annuel par action / cours de l action x 100</strong>. Pour un paiement trimestriel, le montant est multiplié par quatre avant le calcul. Pour un paiement annuel, le montant saisi est utilisé directement.</p>' },
    { type: 'table', headers: ['Donnée', 'Calcul', 'Utilité'], rows: [['Dividende annuel par action', 'Montant par versement x versements par an', 'Place les paiements annuels et trimestriels sur la même base'], ['Rendement brut', 'Dividende annuel / cours x 100', 'Exprime la distribution en pourcentage du cours de référence'], ['Revenu annuel brut', 'Dividende annuel par action x actions', 'Estime le revenu avant le prélèvement saisi'], ['Revenu annuel net', 'Revenu brut x (1 - prélèvement / 100)', 'Donne une estimation simple après le taux indiqué']] },
    { type: 'title', text: 'Exemple avec paiements annuels et trimestriels', level: 3 },
    { type: 'paragraph', html: '<p>Pour une action cotée 100 dans votre devise qui verse 1 chaque trimestre, le dividende annuel vaut 1 x 4 = 4. Le rendement brut vaut donc 4 / 100 x 100 = 4 %. Avec 50 actions, le revenu annuel brut estimé est de 200 avant prélèvement.</p>' },
    { type: 'paragraph', html: '<p>Si la même action versait 4 une seule fois par an, le rendement resterait de 4 %. La fréquence ne change que l annualisation. Une fréquence mal choisie peut donc fausser fortement le résultat.</p>' },
    { type: 'title', text: 'Pourquoi le cours modifie le rendement', level: 3 },
    { type: 'paragraph', html: '<p>Le rendement peut changer même si l entreprise conserve le même dividende. Avec un dividende annuel de 4, un cours de 100 donne 4 %, tandis qu un cours de 80 donne 5 %. Le pourcentage supérieur ne signifie pas forcément que l activité est devenue plus rentable; il peut simplement refléter un cours plus bas.</p>' },
    { type: 'paragraph', html: '<p>Pour comparer plusieurs actions, utilisez la même convention: cours actuel, clôture d une date donnée ou prix d achat. Précisez votre choix, car la date du cours et la période du dividende changent l interprétation.</p>' },
    { type: 'title', text: 'Ne pas confondre rendement, prélèvement et revenu', level: 3 },
    { type: 'comparative', columns: 3, items: [{ title: 'Rendement brut', description: 'Dividende annuel par action comparé au cours de référence.', points: ['Compare distribution et cours', 'Ne retire pas le prélèvement', 'N inclut pas les gains ou pertes de cours'] }, { title: 'Rendement après prélèvement', description: 'Rendement brut réduit du pourcentage saisi.', points: ['Hypothèse utile pour planifier', 'La fiscalité réelle peut varier', 'Ce n est pas une déclaration fiscale'], highlight: true }, { title: 'Revenu annuel', description: 'Montant issu du dividende annuel et du nombre d actions.', points: ['Le brut est avant prélèvement', 'Le net utilise le taux saisi', 'Il dépend du nombre d actions'] }] },
    { type: 'paragraph', html: '<p>Un prélèvement à la source n est pas nécessairement votre impôt final. La résidence, le pays de l entreprise, le compte, les conventions et les procédures de remboursement peuvent compter. Le calculateur applique mécaniquement le taux saisi et ne détermine pas celui qui vous concerne.</p>' },
    { type: 'title', text: 'Bien utiliser le calculateur', level: 3 },
    { type: 'list', items: ['Saisissez le cours et le dividende dans la même devise et sur une base temporelle comparable.', 'Choisissez Annuel ou Trimestriel selon la fréquence du montant saisi.', 'Ajoutez vos actions si vous voulez un revenu total et pas seulement un rendement par action.', 'Utilisez le prélèvement comme hypothèse explicite et vérifiez les règles séparément.', 'Utilisez la croissance pour tester un scénario, pas pour prévoir le futur.', 'Notez la date du cours et la période du dividende lors d une comparaison.'] },
    { type: 'title', text: 'Ce qu un rendement élevé indique ou non', level: 3 },
    { type: 'paragraph', html: '<p>Un rendement élevé peut correspondre à une distribution généreuse, mais aussi à une baisse du cours. Il doit donc inciter à rechercher davantage, pas servir seul de signal d achat. Examinez la trésorerie, les bénéfices, la dette, l historique, la politique de distribution et les annonces récentes.</p>' },
    { type: 'tip', title: 'Considérer la croissance comme un scénario', html: '<p>La vue future applique uniquement le pourcentage saisi au dividende actuel. Elle ne modélise ni le réinvestissement, ni le cours, ni le taux de distribution, ni les bénéfices futurs, ni les décisions de l entreprise. Gardez le résultat identifié comme une hypothèse.</p>' },
    { type: 'title', text: 'Limites de ce calculateur de dividendes', level: 3 },
    { type: 'paragraph', html: '<p>L outil modélise un paiement régulier par action, une fréquence annuelle ou trimestrielle, un nombre d actions facultatif, un prélèvement saisi et un scénario de croissance en une étape. Il ne prévoit pas le rendement total, ne mesure pas la sécurité du dividende, ne traite pas les paiements exceptionnels, ne convertit pas les devises et ne calcule pas votre fiscalité locale.</p>' },
  ],
};
