import type { WithContext, FAQPage, HowTo, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { DividendYieldUI } from '../ui';
import { bibliography } from '../bibliography';

const title = 'Kalkulator Imbal Hasil Dividen Saham';
const description = 'Hitung imbal hasil dividen bruto dan setelah pemotongan, pendapatan tahunan, serta skenario pertumbuhan dari data saham Anda.';
const faq = [
  { question: 'Bagaimana cara menghitung imbal hasil dividen?', answer: 'Kalikan dividen per pembayaran dengan jumlah pembayaran per tahun, bagi dengan harga saham, lalu kalikan 100. Untuk pembayaran triwulanan, kalikan jumlahnya dengan empat terlebih dahulu.' },
  { question: 'Haruskah saya memasukkan dividen tahunan atau triwulanan?', answer: 'Pilih frekuensi yang sesuai dengan jumlah yang Anda masukkan. Kalkulator akan mengubah pembayaran triwulanan menjadi angka tahunan secara otomatis.' },
  { question: 'Apa perbedaan pendapatan dividen bruto dan bersih?', answer: 'Pendapatan bruto adalah dividen tahunan sebelum tingkat pemotongan yang Anda masukkan. Pendapatan bersih mengurangi tingkat tersebut sebagai perkiraan sederhana; pajak sebenarnya dapat berbeda.' },
  { question: 'Apakah imbal hasil dividen tinggi berarti sahamnya lebih baik?', answer: 'Tidak. Imbal hasil dapat naik karena harga saham turun, dan perusahaan dapat mengurangi atau menghentikan dividen. Analisis perusahaan dan risikonya secara terpisah.' },
];
const howTo = [{ name: 'Masukkan harga saham', text: 'Ketik harga per saham yang ingin Anda gunakan sebagai acuan.' }, { name: 'Tambahkan pembayaran dividen', text: 'Masukkan dividen per saham dan pilih apakah pembayarannya tahunan atau triwulanan.' }, { name: 'Tinjau hasil', text: 'Baca imbal hasil bruto, hasil setelah pemotongan, dan pendapatan tahunan. Gunakan pertumbuhan hanya sebagai skenario terpisah.' }];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, inLanguage: 'id' };

const ui: DividendYieldUI = {
  priceLabel: 'Harga saham', priceHelp: 'Masukkan jumlah dalam mata uang Anda', dividendLabel: 'Dividen per pembayaran', dividendHelp: 'Jumlah per saham dalam mata uang yang sama', cadenceLabel: 'Frekuensi pembayaran', annualOption: 'Tahunan', quarterlyOption: 'Triwulanan', sharesLabel: 'Jumlah saham', sharesHelp: 'Opsional untuk total pendapatan', withholdingLabel: 'Tingkat pemotongan (%)', withholdingHelp: 'Perkiraan sederhana pendapatan bersih', growthLabel: 'Skenario pertumbuhan (%)', growthHelp: 'Input opsional untuk skenario ke depan', grossYieldLabel: 'Imbal hasil dividen bruto', netYieldLabel: 'Setelah pemotongan', grossIncomeLabel: 'Pendapatan tahunan bruto', netIncomeLabel: 'Pendapatan tahunan bersih', annualDividendLabel: 'Dividen tahunan', priceShareLabel: 'Harga saham', couponNote: 'Pita ini mengubah dividen tahunan menjadi proporsi dari harga saham yang dimasukkan.', forwardTitle: 'Skenario ke depan dengan asumsi pertumbuhan Anda', forwardYieldLabel: 'Imbal hasil jika dividen tumbuh sesuai input', forwardDividendLabel: 'Dividen ke depan per saham', growthNote: 'Ini skenario, bukan ramalan.', formulaTitle: 'Cara kerja perhitungan', formulaText: 'Dividen tahunan per saham adalah jumlah pembayaran dikalikan jumlah pembayaran. Imbal hasil bruto adalah dividen tahunan per saham dibagi harga saham lalu dikalikan 100. Pendapatan bersih menerapkan tingkat pemotongan pada pendapatan bruto. Pertumbuhan hanya mengubah skenario ke depan.', riskNote: 'Imbal hasil adalah rasio berdasarkan angka yang Anda masukkan. Hasil ini tidak mencakup perubahan harga, biaya, pemotongan dividen, inflasi, atau risiko perubahan pembagian.', emptyMessage: 'Masukkan harga saham positif dan dividen tidak negatif untuk melihat hasil.', annualSuffix: 'per tahun', perShareSuffix: 'per saham', percentageSuffix: '%',
};

export const content: ToolLocaleContent<DividendYieldUI> = {
  slug: 'kalkulator-imbal-hasil-dividen-saham', title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema],
  seo: [
    { type: 'title', text: 'Memahami dan menghitung imbal hasil dividen saham', level: 2 },
    { type: 'paragraph', html: '<p>Imbal hasil dividen membandingkan pembagian tunai tahunan dari sebuah saham dengan harga yang digunakan sebagai acuan. Kalkulator ini mengubah pembayaran dividen menjadi nilai tahunan, membaginya dengan harga saham, lalu menampilkannya sebagai persentase. Anda juga dapat memperkirakan pendapatan tahunan dan memisahkan hasil bruto dari asumsi setelah pemotongan.</p>' },
    { type: 'paragraph', html: '<p>Hasilnya adalah rasio, bukan jaminan keuntungan. Perubahan harga, biaya, pergerakan mata uang, dividen khusus, dan risiko perusahaan mengurangi atau menghentikan dividen tidak termasuk. Gunakan hasil ini untuk membandingkan angka, lalu teliti perusahaan dan sahamnya.</p>' },
    { type: 'title', text: 'Rumus imbal hasil dividen', level: 3 },
    { type: 'paragraph', html: '<p>Rumusnya adalah <strong>imbal hasil dividen = dividen tahunan per saham / harga saham x 100</strong>. Jika pembayaran dilakukan setiap kuartal, jumlah pembayaran dikalikan empat sebelum perhitungan. Untuk pembayaran tahunan, jumlah yang dimasukkan digunakan langsung.</p>' },
    { type: 'table', headers: ['Angka', 'Perhitungan', 'Kegunaan'], rows: [['Dividen tahunan per saham', 'Jumlah pembayaran x pembayaran per tahun', 'Menyamakan dasar pembayaran tahunan dan triwulanan'], ['Imbal hasil bruto', 'Dividen tahunan / harga saham x 100', 'Menunjukkan pembagian sebagai persentase harga acuan'], ['Pendapatan tahunan bruto', 'Dividen tahunan per saham x jumlah saham', 'Memperkirakan pendapatan sebelum pemotongan'], ['Pendapatan tahunan bersih', 'Pendapatan bruto x (1 - pemotongan / 100)', 'Memberi perkiraan sederhana setelah tingkat yang dimasukkan']] },
    { type: 'title', text: 'Contoh pembayaran tahunan dan triwulanan', level: 3 },
    { type: 'paragraph', html: '<p>Misalkan harga saham 100 dalam mata uang Anda dan dividen 1 dibayar setiap kuartal. Dividen tahunan adalah 1 x 4 = 4, sehingga imbal hasil bruto adalah 4 / 100 x 100 = 4%. Dengan 50 saham, pendapatan tahunan bruto diperkirakan 200 sebelum pemotongan.</p>' },
    { type: 'paragraph', html: '<p>Jika saham yang sama membayar 4 sekali setahun, hasilnya tetap 4%. Frekuensi hanya mengubah annualisasi. Memilih frekuensi yang salah dapat membuat hasil sangat menyesatkan.</p>' },
    { type: 'title', text: 'Mengapa harga saham mengubah imbal hasil', level: 3 },
    { type: 'paragraph', html: '<p>Imbal hasil dapat berubah meskipun perusahaan mempertahankan dividen yang sama. Dengan dividen tahunan 4, harga 100 menghasilkan 4%, sedangkan harga 80 menghasilkan 5%. Angka yang lebih tinggi tidak otomatis berarti bisnis lebih menguntungkan; bisa saja hanya mencerminkan harga pasar yang lebih rendah.</p>' },
    { type: 'paragraph', html: '<p>Untuk membandingkan saham, gunakan dasar harga yang sama: harga saat ini, harga penutupan pada tanggal tertentu, atau harga beli Anda. Catat pilihan tersebut karena tanggal harga dan periode dividen memengaruhi makna perbandingan.</p>' },
    { type: 'title', text: 'Bedakan imbal hasil bruto, pemotongan, dan pendapatan', level: 3 },
    { type: 'comparative', columns: 3, items: [{ title: 'Imbal hasil bruto', description: 'Dividen tahunan per saham dibandingkan dengan harga acuan.', points: ['Membandingkan pembagian dan harga', 'Tidak mengurangi pemotongan', 'Tidak memasukkan untung atau rugi harga'] }, { title: 'Imbal hasil setelah pemotongan', description: 'Imbal hasil bruto dikurangi persentase yang dimasukkan.', points: ['Asumsi sederhana untuk perencanaan', 'Pajak sebenarnya dapat berbeda', 'Bukan hasil pelaporan pajak'], highlight: true }, { title: 'Pendapatan tahunan', description: 'Jumlah tunai dari dividen tahunan dan jumlah saham.', points: ['Bruto sebelum pemotongan', 'Bersih memakai tingkat input', 'Bergantung pada jumlah saham'] }] },
    { type: 'paragraph', html: '<p>Pemotongan bukan berarti kewajiban pajak akhir Anda. Domisili, negara perusahaan, jenis rekening, perjanjian pajak, dan prosedur pengembalian dapat berpengaruh. Kalkulator hanya menerapkan persentase yang Anda masukkan dan tidak menentukan tarif yang berlaku.</p>' },
    { type: 'title', text: 'Cara menggunakan kalkulator dengan baik', level: 3 },
    { type: 'list', items: ['Masukkan harga dan dividen dalam mata uang yang sama serta dasar waktu yang sebanding.', 'Pilih Tahunan atau Triwulanan sesuai frekuensi jumlah yang dimasukkan.', 'Tambahkan jumlah saham jika Anda memerlukan total pendapatan, bukan hanya hasil per saham.', 'Gunakan pemotongan sebagai asumsi yang jelas dan periksa aturan yang berlaku secara terpisah.', 'Gunakan pertumbuhan untuk menguji skenario, bukan untuk meramalkan dividen masa depan.', 'Catat tanggal harga dan periode dividen saat membandingkan hasil.'] },
    { type: 'title', text: 'Apa yang dapat dan tidak dapat ditunjukkan imbal hasil tinggi', level: 3 },
    { type: 'paragraph', html: '<p>Imbal hasil tinggi dapat menunjukkan pembagian yang besar, tetapi juga dapat terjadi karena harga saham turun. Jadikan itu alasan untuk melakukan riset, bukan sinyal beli tunggal. Periksa arus kas, laba, utang, riwayat pembagian, kebijakan perusahaan, dan pengumuman terbaru.</p>' },
    { type: 'tip', title: 'Perlakukan pertumbuhan sebagai skenario', html: '<p>Tampilan ke depan hanya menerapkan persentase pertumbuhan yang Anda masukkan pada dividen saat ini. Tampilan ini tidak memodelkan investasi ulang, perubahan harga, rasio pembagian, pertumbuhan laba, atau keputusan perusahaan di masa depan. Tandai hasil sebagai asumsi.</p>' },
    { type: 'title', text: 'Batasan kalkulator dividen ini', level: 3 },
    { type: 'paragraph', html: '<p>Alat ini memodelkan pembayaran reguler per saham, frekuensi tahunan atau triwulanan, jumlah saham opsional, tingkat pemotongan yang dimasukkan, dan satu skenario pertumbuhan. Alat ini tidak meramalkan total imbal hasil, menilai keamanan dividen, menangani dividen khusus, mengonversi mata uang, atau menghitung pajak lokal.</p>' },
  ],
};
