import type { WithContext, FAQPage, HowTo, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { DividendYieldUI } from '../ui';
import { bibliography } from '../bibliography';

const title = 'Calcolatore del rendimento da dividendi delle azioni';
const description = 'Calcola il rendimento lordo e dopo la ritenuta, il reddito annuo e uno scenario di crescita usando i dati della tua azione.';
const faq = [
  { question: 'Come si calcola il rendimento da dividendi?', answer: 'Moltiplica il dividendo per pagamento per il numero di pagamenti annuali, dividi per il prezzo dell azione e moltiplica per 100. Per un pagamento trimestrale, moltiplica prima per quattro.' },
  { question: 'Devo inserire un dividendo annuale o trimestrale?', answer: 'Scegli la frequenza che corrisponde all importo inserito. Il calcolatore annualizza automaticamente i pagamenti trimestrali.' },
  { question: 'Qual è la differenza tra reddito lordo e netto?', answer: 'Il reddito lordo è il dividendo annuale prima della ritenuta inserita. Il reddito netto sottrae quella percentuale come semplice stima; la tua tassazione reale può essere diversa.' },
  { question: 'Un rendimento elevato significa che un azione è migliore?', answer: 'No. Può aumentare perché il prezzo è sceso e una società può ridurre o interrompere il dividendo. Analizza separatamente società e rischi.' },
];
const howTo = [{ name: 'Inserisci il prezzo dell azione', text: 'Scrivi il prezzo per azione che vuoi usare come riferimento.' }, { name: 'Aggiungi il pagamento', text: 'Inserisci il dividendo per azione e scegli se è annuale o trimestrale.' }, { name: 'Controlla rendimento e reddito', text: 'Leggi il rendimento lordo, quello dopo la ritenuta e il reddito annuo. Usa la crescita solo come scenario separato.' }];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, inLanguage: 'it' };

const ui: DividendYieldUI = {
  priceLabel: 'Prezzo dell azione', priceHelp: 'Inserisci un importo nella tua valuta', dividendLabel: 'Dividendo per pagamento', dividendHelp: 'Importo per azione nella stessa valuta', cadenceLabel: 'Frequenza di pagamento', annualOption: 'Annuale', quarterlyOption: 'Trimestrale', sharesLabel: 'Azioni possedute', sharesHelp: 'Facoltativo per il reddito totale', withholdingLabel: 'Ritenuta (%)', withholdingHelp: 'Stima semplice del reddito netto', growthLabel: 'Scenario di crescita (%)', growthHelp: 'Dato facoltativo per lo scenario futuro', grossYieldLabel: 'Rendimento lordo da dividendo', netYieldLabel: 'Dopo la ritenuta', grossIncomeLabel: 'Reddito annuo lordo', netIncomeLabel: 'Reddito annuo netto', annualDividendLabel: 'Dividendo annuo', priceShareLabel: 'Prezzo dell azione', couponNote: 'La fascia trasforma il dividendo annuo in una proporzione del prezzo inserito.', forwardTitle: 'Scenario futuro con la tua ipotesi di crescita', forwardYieldLabel: 'Rendimento se il dividendo cresce come indicato', forwardDividendLabel: 'Dividendo futuro per azione', growthNote: 'È uno scenario, non una previsione.', formulaTitle: 'Come funziona il calcolo', formulaText: 'Il dividendo annuo per azione è l importo del pagamento moltiplicato per il numero di pagamenti. Il rendimento lordo è il dividendo annuo per azione diviso per il prezzo, moltiplicato per 100. Il reddito netto applica la ritenuta al reddito lordo. La crescita modifica solo lo scenario futuro.', riskNote: 'Il rendimento è un rapporto basato sui dati inseriti. Non comprende variazioni di prezzo, commissioni, tagli, inflazione o il rischio che la società modifichi la distribuzione.', emptyMessage: 'Inserisci un prezzo positivo e un dividendo non negativo per vedere il risultato.', annualSuffix: 'all anno', perShareSuffix: 'per azione', percentageSuffix: '%',
};

export const content: ToolLocaleContent<DividendYieldUI> = {
  slug: 'calcolatore-rendimento-dividendi-azioni', title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema],
  seo: [
    { type: 'title', text: 'Capire e calcolare il rendimento da dividendi', level: 2 },
    { type: 'paragraph', html: '<p>Il rendimento da dividendi confronta la distribuzione annuale in contanti di un azione con il prezzo usato come riferimento. Questo calcolatore annualizza un pagamento, lo divide per il prezzo dell azione e mostra il risultato in percentuale. Stima anche il reddito annuo e distingue il risultato lordo da una semplice ipotesi dopo la ritenuta.</p>' },
    { type: 'paragraph', html: '<p>Il risultato è un rapporto, non una promessa di rendimento. Non comprende variazioni di prezzo, commissioni, valute, dividendi straordinari né il rischio che la società riduca o elimini il pagamento. Usalo per confrontare i dati e poi analizza la società e il titolo.</p>' },
    { type: 'title', text: 'La formula del rendimento da dividendi', level: 3 },
    { type: 'paragraph', html: '<p>La formula è <strong>rendimento da dividendi = dividendo annuo per azione / prezzo dell azione x 100</strong>. Per un pagamento trimestrale, l importo viene moltiplicato per quattro prima del calcolo. Per un pagamento annuale, si usa direttamente l importo inserito.</p>' },
    { type: 'table', headers: ['Dato', 'Calcolo', 'Perché conta'], rows: [['Dividendo annuo per azione', 'Importo per pagamento x pagamenti annui', 'Mette pagamenti annuali e trimestrali sulla stessa base'], ['Rendimento lordo', 'Dividendo annuo / prezzo x 100', 'Mostra la distribuzione come percentuale del prezzo di riferimento'], ['Reddito annuo lordo', 'Dividendo annuo per azione x azioni', 'Stima il reddito prima della ritenuta inserita'], ['Reddito annuo netto', 'Reddito lordo x (1 - ritenuta / 100)', 'Offre una stima semplice dopo la percentuale indicata']] },
    { type: 'title', text: 'Esempio con pagamenti annuali e trimestrali', level: 3 },
    { type: 'paragraph', html: '<p>Supponi un azione dal prezzo di 100 nella tua valuta e un dividendo di 1 pagato ogni trimestre. Il dividendo annuo è 1 x 4 = 4, quindi il rendimento lordo è 4 / 100 x 100 = 4 %. Con 50 azioni, il reddito annuo lordo stimato è 200 prima della ritenuta.</p>' },
    { type: 'paragraph', html: '<p>Se la stessa azione pagasse 4 una volta all anno, il rendimento resterebbe del 4 %. La frequenza cambia solo l annualizzazione. Selezionare la frequenza sbagliata può quindi falsare il risultato.</p>' },
    { type: 'title', text: 'Perché il prezzo cambia il rendimento', level: 3 },
    { type: 'paragraph', html: '<p>Il rendimento può cambiare anche se la società mantiene lo stesso dividendo. Con un dividendo annuo di 4, un prezzo di 100 produce il 4 %, mentre un prezzo di 80 produce il 5 %. Il numero più alto non significa necessariamente che l attività sia più redditizia: può riflettere solo un prezzo di mercato più basso.</p>' },
    { type: 'paragraph', html: '<p>Per confrontare più azioni, usa la stessa convenzione: prezzo attuale, chiusura di una data precisa o prezzo di acquisto. Indica la scelta, perché la data del prezzo e il periodo del dividendo cambiano il significato del confronto.</p>' },
    { type: 'title', text: 'Non confondere rendimento, ritenuta e reddito', level: 3 },
    { type: 'comparative', columns: 3, items: [{ title: 'Rendimento lordo', description: 'Dividendo annuo per azione confrontato con il prezzo di riferimento.', points: ['Confronta distribuzione e prezzo', 'Non sottrae la ritenuta', 'Non include guadagni o perdite di prezzo'] }, { title: 'Rendimento dopo la ritenuta', description: 'Rendimento lordo ridotto della percentuale inserita.', points: ['Ipotesi utile per pianificare', 'La tassazione effettiva può variare', 'Non è un risultato fiscale'], highlight: true }, { title: 'Reddito annuo', description: 'Somma derivata dal dividendo annuo e dal numero di azioni.', points: ['Il lordo è prima della ritenuta', 'Il netto usa il tasso indicato', 'Dipende dal numero di azioni'] }] },
    { type: 'paragraph', html: '<p>La ritenuta non coincide necessariamente con la tua imposta finale. Possono contare residenza, paese della società, tipo di conto, convenzioni e procedure di rimborso. Il calcolatore applica meccanicamente la percentuale inserita e non stabilisce quella corretta per te.</p>' },
    { type: 'title', text: 'Come usare bene il calcolatore', level: 3 },
    { type: 'list', items: ['Inserisci prezzo e dividendo nella stessa valuta e su una base temporale confrontabile.', 'Scegli Annuale o Trimestrale secondo la frequenza dell importo inserito.', 'Aggiungi le azioni quando ti serve il reddito totale e non solo il rendimento per azione.', 'Usa la ritenuta come ipotesi esplicita e verifica separatamente le regole applicabili.', 'Usa la crescita per testare uno scenario, non per prevedere la distribuzione futura.', 'Annota la data del prezzo e il periodo del dividendo quando confronti i risultati.'] },
    { type: 'title', text: 'Cosa può e non può dire un rendimento elevato', level: 3 },
    { type: 'paragraph', html: '<p>Un rendimento elevato può indicare una distribuzione generosa, ma anche un prezzo in calo. Deve quindi spingere a fare ricerche e non diventare da solo un segnale di acquisto. Controlla flussi di cassa, utili, debito, storia delle distribuzioni, politica societaria e comunicati recenti.</p>' },
    { type: 'tip', title: 'Tratta la crescita come uno scenario', html: '<p>La vista futura applica solo la percentuale inserita al dividendo attuale. Non modella reinvestimento, prezzo, payout, crescita degli utili o decisioni future della società. Mantieni il risultato identificato come ipotesi.</p>' },
    { type: 'title', text: 'Limiti di questo calcolatore di dividendi', level: 3 },
    { type: 'paragraph', html: '<p>Lo strumento modella un pagamento regolare per azione, una frequenza annuale o trimestrale, un numero opzionale di azioni, una ritenuta inserita e uno scenario di crescita a un solo passaggio. Non prevede il rendimento totale, non misura la sicurezza del dividendo, non tratta dividendi speciali, non converte valute e non calcola la fiscalità locale.</p>' },
  ],
};
