import type { WithContext, FAQPage, HowTo, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { DividendYieldUI } from '../ui';
import { bibliography } from '../bibliography';

const title = '주식 배당수익률 계산기';
const description = '주식 데이터를 바탕으로 세전 및 원천징수 후 배당수익률, 연간 수입과 성장 시나리오를 계산합니다.';
const faq = [{ question: '배당수익률은 어떻게 계산하나요?', answer: '1회 배당금에 연간 지급 횟수를 곱하고 주가로 나눈 뒤 100을 곱합니다. 분기 배당이면 먼저 4를 곱합니다.' }, { question: '연간 배당과 분기 배당 중 무엇을 입력하나요?', answer: '입력한 금액에 맞는 지급 빈도를 선택하세요. 계산기는 분기 배당을 자동으로 연간 금액으로 환산합니다.' }, { question: '세전 배당소득과 세후 배당소득의 차이는 무엇인가요?', answer: '세전 소득은 원천징수 전 금액입니다. 세후 소득은 입력한 비율을 적용한 단순한 추정치이며 실제 세금과 다를 수 있습니다.' }, { question: '배당수익률이 높으면 더 좋은 주식인가요?', answer: '그렇지 않습니다. 주가 하락만으로 수익률이 높아질 수 있고 기업은 배당을 줄이거나 중단할 수 있습니다.' }];
const howTo = [{ name: '주가 입력', text: '기준으로 사용할 주당 가격을 입력합니다.' }, { name: '배당금 입력', text: '주당 배당금과 연간 또는 분기 지급 빈도를 입력합니다.' }, { name: '결과 확인', text: '세전 수익률, 원천징수 후 수익률과 연간 소득을 확인합니다. 성장률은 별도 시나리오로 사용합니다.' }];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, inLanguage: 'ko' };
const ui: DividendYieldUI = { priceLabel: '주가', priceHelp: '사용할 통화로 금액 입력', dividendLabel: '1회 배당금', dividendHelp: '같은 통화의 주당 금액', cadenceLabel: '지급 빈도', annualOption: '연간', quarterlyOption: '분기', sharesLabel: '보유 주식 수', sharesHelp: '총소득 계산에 선택 입력', withholdingLabel: '원천징수율 (%)', withholdingHelp: '세후 소득의 단순 추정에 사용', growthLabel: '가정 성장률 (%)', growthHelp: '미래 시나리오용 선택 입력', grossYieldLabel: '세전 배당수익률', netYieldLabel: '원천징수 후', grossIncomeLabel: '세전 연간 소득', netIncomeLabel: '세후 연간 소득', annualDividendLabel: '연간 배당금', priceShareLabel: '주가', couponNote: '이 띠는 연간 배당금을 입력한 주가와의 비율로 보여줍니다.', forwardTitle: '성장 가정을 적용한 미래 시나리오', forwardYieldLabel: '입력한 만큼 배당이 증가했을 때의 수익률', forwardDividendLabel: '미래 주당 배당금', growthNote: '예측이 아니라 시나리오입니다.', formulaTitle: '계산 방법', formulaText: '연간 주당 배당금은 1회 배당금에 연간 지급 횟수를 곱한 값입니다. 세전 수익률은 연간 주당 배당금을 주가로 나눈 뒤 100을 곱합니다. 세후 소득에는 입력한 원천징수율을 적용합니다. 성장률은 미래 시나리오만 바꿉니다.', riskNote: '배당수익률은 입력값으로 만든 비율입니다. 주가 변동, 수수료, 감액, 인플레이션과 배당 변경 위험은 포함하지 않습니다.', emptyMessage: '양의 주가와 0 이상인 배당금을 입력하면 결과가 표시됩니다.', annualSuffix: '연간', perShareSuffix: '주당', percentageSuffix: '%', };
const p = (html: string) => ({ type: 'paragraph' as const, html: `<p>${html}</p>` });
export const content: ToolLocaleContent<DividendYieldUI> = { slug: 'dividend-yield-calculator', title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo: [
  { type: 'title', text: '주식 배당수익률을 이해하고 계산하는 방법', level: 2 }, p('배당수익률은 주식이 1년 동안 지급하는 현금 배당을 기준 주가와 비교하는 지표입니다. 이 계산기는 1회 배당을 연간 금액으로 환산하고 주가로 나누어 백분율로 표시합니다. 보유 주식 수에 따른 연간 소득과 원천징수 후 단순 시나리오도 확인할 수 있습니다.'), p('결과는 비율이지 수익 보장이 아닙니다. 주가 변동, 수수료, 환율, 특별 배당, 감액 또는 무배당 위험은 포함하지 않습니다. 비교의 출발점으로 사용한 뒤 기업과 종목을 따로 조사하세요.'),
  { type: 'title', text: '배당수익률 공식', level: 3 }, p('<strong>배당수익률 = 주당 연간 배당금 / 주가 x 100</strong>입니다. 분기 배당은 계산 전에 금액을 4배로 환산하고, 연간 배당은 입력값을 그대로 사용합니다.'),
  { type: 'table', headers: ['수치', '계산', '의미'], rows: [['주당 연간 배당금', '1회 배당금 x 연간 지급 횟수', '연간과 분기 지급을 같은 기준으로 비교'], ['세전 배당수익률', '연간 배당금 / 주가 x 100', '기준 주가에 대한 배당 비율'], ['세전 연간 소득', '연간 주당 배당금 x 주식 수', '원천징수 전 소득 추정'], ['세후 연간 소득', '세전 소득 x (1 - 원천징수율 / 100)', '입력한 비율을 적용한 단순 추정']] },
  { type: 'title', text: '연간 지급과 분기 지급 예시', level: 3 }, p('주가가 100이고 분기마다 1을 지급하면 연간 배당은 1 x 4 = 4입니다. 세전 수익률은 4 / 100 x 100 = 4%이며, 50주를 보유하면 원천징수 전 연간 소득은 200입니다.'), p('같은 주식이 1년에 한 번 4를 지급해도 수익률은 4%입니다. 지급 빈도는 연환산 방법만 바꾸므로, 잘못 선택하면 결과가 왜곡됩니다.'),
  { type: 'title', text: '주가가 수익률을 바꾸는 이유', level: 3 }, p('기업이 같은 배당을 유지해도 수익률은 달라집니다. 연간 배당이 4라면 주가 100에서는 4%, 주가 80에서는 5%입니다. 더 높은 수익률이 기업의 수익성 향상을 뜻하는 것은 아니며 주가 하락의 결과일 수 있습니다.'), p('종목을 비교할 때는 현재가, 특정일 종가 또는 매수가처럼 같은 가격 기준을 사용하세요. 가격 날짜와 배당 기간도 함께 기록해야 비교를 올바르게 해석할 수 있습니다.'),
  { type: 'title', text: '수익률, 원천징수와 소득을 구분하기', level: 3 }, { type: 'comparative', columns: 3, items: [{ title: '세전 수익률', description: '연간 주당 배당금을 기준 주가와 비교한 값입니다.', points: ['배당과 가격을 비교', '원천징수를 차감하지 않음', '주가 손익은 포함하지 않음'] }, { title: '원천징수 후 수익률', description: '입력한 비율을 차감한 세전 수익률입니다.', points: ['계획을 위한 단순 시나리오', '실제 세금은 다를 수 있음', '세금 신고 결과가 아님'], highlight: true }, { title: '연간 소득', description: '연간 배당금과 보유 주식 수로 계산한 현금액입니다.', points: ['세전은 원천징수 전', '세후는 입력 비율 사용', '보유 주식 수에 따라 달라짐'] }] }, p('원천징수율이 최종 세금과 같지는 않습니다. 거주지, 기업의 국가, 계좌 유형, 조세조약과 환급 절차가 영향을 줄 수 있습니다. 계산기는 입력한 비율만 기계적으로 적용합니다.'),
  { type: 'title', text: '계산기를 잘 사용하는 방법', level: 3 }, { type: 'list', items: ['주가와 배당을 같은 통화와 비교 가능한 기간으로 입력합니다.', '입력한 금액에 맞춰 연간 또는 분기를 선택합니다.', '총소득이 필요할 때 보유 주식 수를 추가합니다.', '원천징수는 명시적인 가정으로 사용하고 세금 규정은 따로 확인합니다.', '성장률은 시나리오를 시험하는 값이지 미래 예측이 아닙니다.', '비교할 때 가격 날짜와 배당 기간을 기록합니다.'] },
  { type: 'title', text: '높은 배당수익률이 말해 주는 것과 말해 주지 않는 것', level: 3 }, p('높은 수익률은 큰 배당을 뜻할 수도 있지만 주가 하락으로 생길 수도 있습니다. 단독 매수 신호가 아니라 조사할 이유로 보세요. 현금흐름, 이익, 부채, 배당 이력, 정책과 최근 공시를 확인하세요.'), { type: 'tip', title: '성장률을 시나리오로 다루기', html: '<p>미래 화면은 입력한 성장률을 현재 배당에 적용할 뿐입니다. 재투자, 주가, 배당성향, 이익 성장이나 기업의 미래 결정을 모델링하지 않습니다. 결과를 가정으로 표시하세요.</p>' },
  { type: 'title', text: '이 배당수익률 계산기의 한계', level: 3 }, p('이 도구는 정기적인 주당 배당, 연간 또는 분기 빈도, 선택적인 주식 수, 입력한 원천징수율과 한 단계 성장 시나리오를 계산합니다. 총주주수익률, 배당 안전성, 특별 배당, 환전과 현지 세금은 계산하지 않습니다.'),
] };
