import type { WithContext, FAQPage, HowTo, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { DividendYieldUI } from '../ui';
import { bibliography } from '../bibliography';

const title = 'Dividendrendement calculator voor aandelen';
const description = 'Bereken bruto en netto dividendrendement, jaarinkomen en een groeiscenario met je eigen aandelengegevens.';
const faq = [{ question: 'Hoe bereken ik dividendrendement?', answer: 'Vermenigvuldig het dividend per betaling met het aantal betalingen per jaar, deel door de aandelenkoers en vermenigvuldig met 100. Bij een kwartaalbetaling vermenigvuldig je eerst met vier.' }, { question: 'Voer ik een jaarlijks of kwartaaldividend in?', answer: 'Kies de frequentie die bij het ingevoerde bedrag hoort. De calculator rekent kwartaalbetalingen automatisch om naar een jaarbedrag.' }, { question: 'Wat is het verschil tussen bruto en netto dividendinkomen?', answer: 'Bruto inkomen is het jaarlijkse dividend vóór het ingevoerde inhoudingspercentage. Netto inkomen trekt dat percentage af als eenvoudige schatting; je werkelijke belasting kan anders zijn.' }, { question: 'Betekent een hoog dividendrendement dat een aandeel beter is?', answer: 'Nee. Het rendement kan stijgen doordat de koers daalt en een bedrijf kan het dividend verlagen of stoppen. Onderzoek het bedrijf en de risico s afzonderlijk.' }];
const howTo = [{ name: 'Voer de aandelenkoers in', text: 'Vul de prijs per aandeel in die je als referentie wilt gebruiken.' }, { name: 'Voeg de dividendbetaling toe', text: 'Vul het dividend per aandeel in en kies jaarlijks of per kwartaal.' }, { name: 'Bekijk rendement en inkomen', text: 'Lees bruto rendement, rendement na inhouding en jaarinkomen af. Gebruik groei alleen als apart scenario.' }];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, inLanguage: 'nl' };
const ui: DividendYieldUI = { priceLabel: 'Aandelenkoers', priceHelp: 'Voer een bedrag in je valuta in', dividendLabel: 'Dividend per betaling', dividendHelp: 'Bedrag per aandeel in dezelfde valuta', cadenceLabel: 'Betalingsfrequentie', annualOption: 'Jaarlijks', quarterlyOption: 'Per kwartaal', sharesLabel: 'Aandelen in bezit', sharesHelp: 'Optioneel voor totaal inkomen', withholdingLabel: 'Inhoudingspercentage (%)', withholdingHelp: 'Eenvoudige schatting van netto inkomen', growthLabel: 'Veronderstelde groei (%)', growthHelp: 'Optionele invoer voor het toekomstscenario', grossYieldLabel: 'Bruto dividendrendement', netYieldLabel: 'Na inhouding', grossIncomeLabel: 'Bruto jaarinkomen', netIncomeLabel: 'Netto jaarinkomen', annualDividendLabel: 'Jaarlijks dividend', priceShareLabel: 'Aandelenkoers', couponNote: 'De strook zet het jaarlijkse dividend af tegen de ingevoerde aandelenkoers.', forwardTitle: 'Toekomstscenario met je groeiaanname', forwardYieldLabel: 'Rendement als het dividend groeit zoals ingevoerd', forwardDividendLabel: 'Toekomstig dividend per aandeel', growthNote: 'Dit is een scenario, geen voorspelling.', formulaTitle: 'Zo werkt de berekening', formulaText: 'Het jaarlijkse dividend per aandeel is het bedrag per betaling vermenigvuldigd met het aantal betalingen. Het bruto rendement is het jaarlijkse dividend per aandeel gedeeld door de koers maal 100. Netto inkomen past het inhoudingspercentage toe op bruto inkomen. Groei verandert alleen het toekomstscenario.', riskNote: 'Dividendrendement is een verhouding op basis van je invoer. Koerswinst, koersverlies, kosten, dividendverlagingen, inflatie en wijzigingen in de uitkering zijn niet inbegrepen.', emptyMessage: 'Voer een positieve aandelenkoers en een niet-negatief dividend in om het resultaat te zien.', annualSuffix: 'per jaar', perShareSuffix: 'per aandeel', percentageSuffix: '%', };
const p = (html: string) => ({ type: 'paragraph' as const, html: `<p>${html}</p>` });
export const content: ToolLocaleContent<DividendYieldUI> = { slug: 'calculator-dividendrendement-aandelen', title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo: [
  { type: 'title', text: 'Dividendrendement begrijpen en berekenen', level: 2 }, p('Dividendrendement vergelijkt de jaarlijkse uitkering van een aandeel met de koers die je als referentie gebruikt. Deze calculator rekent een betaling om naar een jaarbedrag, deelt dat door de aandelenkoers en toont het resultaat als percentage. Je kunt ook jaarinkomen en een eenvoudige schatting na inhouding bekijken.'), p('Het resultaat is een verhouding en geen beloofd rendement. Koersbewegingen, kosten, valuta, speciale dividenden en het risico op een verlaging of stopzetting zijn niet inbegrepen. Gebruik het als beginpunt en onderzoek daarna het bedrijf en het aandeel.'),
  { type: 'title', text: 'De formule voor dividendrendement', level: 3 }, p('<strong>Dividendrendement = jaarlijks dividend per aandeel / aandelenkoers x 100</strong>. Bij kwartaalbetalingen wordt het bedrag eerst met vier vermenigvuldigd; bij jaarlijkse betalingen wordt de invoer direct gebruikt.'),
  { type: 'table', headers: ['Gegeven', 'Berekening', 'Betekenis'], rows: [['Jaarlijks dividend per aandeel', 'Bedrag per betaling x betalingen per jaar', 'Zet jaarlijkse en kwartaalbetalingen op dezelfde basis'], ['Bruto dividendrendement', 'Jaarlijks dividend / koers x 100', 'Toont de uitkering als percentage van de referentiekoers'], ['Bruto jaarinkomen', 'Jaarlijks dividend per aandeel x aandelen', 'Schat inkomen vóór de ingevoerde inhouding'], ['Netto jaarinkomen', 'Bruto inkomen x (1 - inhouding / 100)', 'Geeft een eenvoudige schatting na het ingevoerde percentage']] },
  { type: 'title', text: 'Voorbeeld met jaarlijkse en kwartaalbetalingen', level: 3 }, p('Stel dat een aandeel 100 kost en elk kwartaal 1 uitkeert. Het jaarlijkse dividend is 1 x 4 = 4 en het bruto rendement is 4 / 100 x 100 = 4%. Met 50 aandelen is het geschatte bruto jaarinkomen 200 vóór inhouding.'), p('Als hetzelfde aandeel eenmaal per jaar 4 uitkeert, blijft het rendement 4%. De frequentie verandert alleen de annualisering. Een verkeerde keuze kan het resultaat daarom misleiden.'),
  { type: 'title', text: 'Waarom de aandelenkoers het rendement verandert', level: 3 }, p('Het rendement kan veranderen terwijl het bedrijf hetzelfde dividend betaalt. Bij een jaarlijks dividend van 4 geeft een koers van 100 een rendement van 4% en een koers van 80 een rendement van 5%. Het hogere percentage betekent niet automatisch betere bedrijfsresultaten; het kan een lagere marktkoers weerspiegelen.'), p('Gebruik bij vergelijkingen dezelfde koersbasis: de huidige koers, de slotkoers op een bepaalde datum of je aankoopprijs. Noteer de datum en het dividendtijdvak, want beide beïnvloeden de betekenis.'),
  { type: 'title', text: 'Bruto rendement, inhouding en inkomen onderscheiden', level: 3 }, { type: 'comparative', columns: 3, items: [{ title: 'Bruto rendement', description: 'Jaarlijks dividend per aandeel vergeleken met de referentiekoers.', points: ['Vergelijkt uitkering en prijs', 'Trekt geen inhouding af', 'Bevat geen koerswinst of verlies'] }, { title: 'Rendement na inhouding', description: 'Bruto rendement verminderd met het ingevoerde percentage.', points: ['Eenvoudige planningsaanname', 'Werkelijke belasting kan verschillen', 'Geen aangifteresultaat'], highlight: true }, { title: 'Jaarinkomen', description: 'Cashbedrag uit dividend en aantal aandelen.', points: ['Bruto is vóór inhouding', 'Netto gebruikt de invoer', 'Hangt af van het aantal aandelen'] }] }, p('Inhouding is niet automatisch je uiteindelijke belasting. Woonplaats, land van het bedrijf, rekeningtype, verdragen en teruggaafprocedures kunnen meetellen. De calculator past alleen je ingevoerde percentage mechanisch toe.'),
  { type: 'title', text: 'De calculator goed gebruiken', level: 3 }, { type: 'list', items: ['Voer koers en dividend in dezelfde valuta en op een vergelijkbare tijdsbasis in.', 'Kies Jaarlijks of Per kwartaal volgens de frequentie van het bedrag.', 'Voeg aandelen toe wanneer je totaal inkomen wilt berekenen.', 'Gebruik inhouding als expliciete aanname en controleer de regels apart.', 'Gebruik groei om een scenario te testen, niet om de toekomst te voorspellen.', 'Noteer koersdatum en dividendperiode bij een vergelijking.'] },
  { type: 'title', text: 'Wat een hoog dividendrendement wel en niet zegt', level: 3 }, p('Een hoog rendement kan op een grote uitkering wijzen, maar ook op een dalende koers. Zie het als aanleiding voor onderzoek, niet als zelfstandig koopsignaal. Bekijk kasstromen, winst, schuld, uitkeringsgeschiedenis, beleid en recente berichten.'), { type: 'tip', title: 'Behandel groei als scenario', html: '<p>De toekomstweergave past alleen het ingevoerde groeipercentage toe op het huidige dividend. Herbelegging, koers, uitkeringsratio, winstgroei en toekomstige bedrijfsbesluiten worden niet gemodelleerd.</p>' },
  { type: 'title', text: 'Beperkingen van deze dividendcalculator', level: 3 }, p('De tool modelleert een reguliere betaling per aandeel, jaarlijkse of kwartaalfrequentie, een optioneel aantal aandelen, een ingevoerd inhoudingspercentage en een groeiscenario in één stap. Hij voorspelt geen totaalrendement, dividendveiligheid, speciale dividenden, valutaomrekening of lokale belasting.'),
] };
