import type { WithContext, FAQPage, HowTo, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { DividendYieldUI } from '../ui';
import { bibliography } from '../bibliography';

const title = 'Kalkulator stopy dywidendy akcji';
const description = 'Oblicz brutto i netto stopę dywidendy, roczny dochód oraz scenariusz wzrostu na podstawie danych akcji.';
const faq = [{ question: 'Jak obliczyć stopę dywidendy?', answer: 'Pomnóż dywidendę za wypłatę przez liczbę wypłat w roku, podziel przez cenę akcji i pomnóż przez 100. Przy wypłacie kwartalnej najpierw pomnóż kwotę przez cztery.' }, { question: 'Czy wpisać dywidendę roczną czy kwartalną?', answer: 'Wybierz częstotliwość zgodną z wpisaną kwotą. Kalkulator automatycznie przelicza wypłaty kwartalne na rok.' }, { question: 'Czym różni się dochód brutto od netto?', answer: 'Dochód brutto to roczna dywidenda przed wpisanym podatkiem u źródła. Dochód netto odejmuje ten procent jako proste założenie; rzeczywiste opodatkowanie może być inne.' }, { question: 'Czy wysoka stopa dywidendy oznacza lepszą akcję?', answer: 'Nie. Stopa może wzrosnąć, gdy spada cena akcji, a spółka może obniżyć lub wstrzymać dywidendę. Zbadaj osobno spółkę i ryzyko.' }];
const howTo = [{ name: 'Wpisz cenę akcji', text: 'Podaj cenę jednej akcji, której chcesz użyć jako punktu odniesienia.' }, { name: 'Dodaj wypłatę dywidendy', text: 'Wpisz dywidendę na akcję i wybierz wypłatę roczną albo kwartalną.' }, { name: 'Sprawdź wynik', text: 'Odczytaj brutto, wynik po podatku u źródła i roczny dochód. Wzrost traktuj jako osobny scenariusz.' }];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, inLanguage: 'pl' };
const ui: DividendYieldUI = { priceLabel: 'Cena akcji', priceHelp: 'Wpisz kwotę w swojej walucie', dividendLabel: 'Dywidenda za wypłatę', dividendHelp: 'Kwota na akcję w tej samej walucie', cadenceLabel: 'Częstotliwość wypłat', annualOption: 'Rocznie', quarterlyOption: 'Kwartalnie', sharesLabel: 'Posiadane akcje', sharesHelp: 'Opcjonalnie do obliczenia dochodu', withholdingLabel: 'Podatek u źródła (%)', withholdingHelp: 'Proste oszacowanie dochodu netto', growthLabel: 'Założony wzrost (%)', growthHelp: 'Opcjonalne założenie dla przyszłego scenariusza', grossYieldLabel: 'Brutto stopa dywidendy', netYieldLabel: 'Po podatku u źródła', grossIncomeLabel: 'Roczny dochód brutto', netIncomeLabel: 'Roczny dochód netto', annualDividendLabel: 'Dywidenda roczna', priceShareLabel: 'Cena akcji', couponNote: 'Pasek pokazuje roczną dywidendę jako część wpisanej ceny akcji.', forwardTitle: 'Przyszły scenariusz z założeniem wzrostu', forwardYieldLabel: 'Stopa, jeśli dywidenda wzrośnie zgodnie z założeniem', forwardDividendLabel: 'Przyszła dywidenda na akcję', growthNote: 'To scenariusz, nie prognoza.', formulaTitle: 'Jak działa obliczenie', formulaText: 'Roczna dywidenda na akcję to kwota wypłaty pomnożona przez liczbę wypłat. Brutto stopa dywidendy to roczna dywidenda na akcję podzielona przez cenę akcji i pomnożona przez 100. Dochód netto stosuje podatek u źródła do dochodu brutto. Wzrost zmienia tylko przyszły scenariusz.', riskNote: 'Stopa dywidendy jest wskaźnikiem opartym na wpisanych danych. Nie obejmuje zmian ceny, opłat, obniżek, inflacji ani ryzyka zmiany wypłaty przez spółkę.', emptyMessage: 'Wpisz dodatnią cenę akcji i nieujemną dywidendę, aby zobaczyć wynik.', annualSuffix: 'rocznie', perShareSuffix: 'na akcję', percentageSuffix: '%', };
const p = (html: string) => ({ type: 'paragraph' as const, html: `<p>${html}</p>` });
export const content: ToolLocaleContent<DividendYieldUI> = { slug: 'kalkulator-stopy-dywidendy-akcji', title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo: [
  { type: 'title', text: 'Jak rozumieć i obliczać stopę dywidendy', level: 2 }, p('Stopa dywidendy porównuje roczną wypłatę gotówkową akcji z ceną przyjętą jako punkt odniesienia. Kalkulator przelicza jedną wypłatę na rok, dzieli ją przez cenę akcji i pokazuje wynik w procentach. Możesz także oszacować roczny dochód oraz prosty scenariusz po podatku u źródła.'), p('Wynik jest wskaźnikiem, a nie obietnicą zysku. Nie obejmuje zmian kursu, opłat, walut, dywidend specjalnych ani ryzyka obniżenia lub zawieszenia wypłaty. Traktuj go jako początek porównania, a potem zbadaj spółkę i akcję.'),
  { type: 'title', text: 'Wzór na stopę dywidendy', level: 3 }, p('<strong>Stopa dywidendy = roczna dywidenda na akcję / cena akcji x 100</strong>. Przy wypłacie kwartalnej kwotę najpierw mnoży się przez cztery, a przy rocznej wykorzystuje się ją bezpośrednio.'),
  { type: 'table', headers: ['Dane', 'Obliczenie', 'Znaczenie'], rows: [['Roczna dywidenda na akcję', 'Kwota wypłaty x wypłaty w roku', 'Ujednolica wypłaty roczne i kwartalne'], ['Brutto stopa dywidendy', 'Dywidenda roczna / cena x 100', 'Pokazuje wypłatę jako procent ceny odniesienia'], ['Roczny dochód brutto', 'Dywidenda roczna na akcję x akcje', 'Szacuje dochód przed wpisanym podatkiem'], ['Roczny dochód netto', 'Dochód brutto x (1 - podatek / 100)', 'Daje proste oszacowanie po wpisanej stawce']] },
  { type: 'title', text: 'Przykład wypłat rocznych i kwartalnych', level: 3 }, p('Załóżmy cenę akcji 100 i dywidendę 1 wypłacaną co kwartał. Roczna dywidenda wynosi 1 x 4 = 4, więc brutto stopa dywidendy to 4 / 100 x 100 = 4%. Przy 50 akcjach roczny dochód brutto wynosi około 200 przed podatkiem.'), p('Jeśli ta sama akcja wypłacałaby 4 raz w roku, wynik nadal wyniósłby 4%. Częstotliwość zmienia tylko przeliczenie na rok, dlatego jej błędny wybór zniekształca wynik.'),
  { type: 'title', text: 'Dlaczego cena akcji zmienia stopę', level: 3 }, p('Stopa może się zmienić, mimo że spółka utrzymuje tę samą dywidendę. Przy dywidendzie rocznej 4 cena 100 daje 4%, a cena 80 daje 5%. Wyższy procent nie musi oznaczać lepszego biznesu; może wynikać wyłącznie ze spadku ceny rynkowej.'), p('Porównując akcje, stosuj tę samą podstawę ceny: kurs bieżący, zamknięcie z wybranego dnia albo cenę zakupu. Zapisz datę ceny i okres dywidendy, bo wpływają na interpretację. Warto też porównywać spółki o podobnym profilu i nie mieszać bieżącej stopy z historycznym kosztem zakupu bez wyraźnego oznaczenia. Dzięki temu wiadomo, czy wynik opisuje obecną cenę, czy osobistą stopę dochodu inwestora.'),
  { type: 'title', text: 'Nie myl stopy, podatku i dochodu', level: 3 }, { type: 'comparative', columns: 3, items: [{ title: 'Brutto stopa', description: 'Roczna dywidenda na akcję w porównaniu z ceną odniesienia.', points: ['Porównuje wypłatę z ceną', 'Nie odejmuje podatku', 'Nie obejmuje zysku ani straty kursowej'] }, { title: 'Stopa po podatku', description: 'Brutto stopa pomniejszona o wpisany procent.', points: ['Proste założenie planistyczne', 'Rzeczywisty podatek może być inny', 'Nie jest wynikiem rozliczenia'], highlight: true }, { title: 'Roczny dochód', description: 'Kwota gotówki wynikająca z dywidendy i liczby akcji.', points: ['Brutto jest przed podatkiem', 'Netto używa wpisanej stawki', 'Zależy od liczby akcji'] }] }, p('Podatek u źródła nie musi być końcowym podatkiem. Znaczenie mogą mieć rezydencja, kraj spółki, rachunek, umowy podatkowe i procedury zwrotu. Kalkulator stosuje wyłącznie wpisany procent.'),
  { type: 'title', text: 'Jak dobrze korzystać z kalkulatora', level: 3 }, { type: 'list', items: ['Wpisz cenę i dywidendę w tej samej walucie i porównywalnym okresie.', 'Wybierz Rocznie lub Kwartalnie zgodnie z częstotliwością kwoty.', 'Dodaj liczbę akcji, gdy potrzebujesz całkowitego dochodu.', 'Traktuj podatek jako jawne założenie i sprawdź zasady osobno.', 'Użyj wzrostu do testowania scenariusza, nie do przewidywania dywidendy.', 'Zapisz datę ceny i okres dywidendy przy porównaniu, aby później odtworzyć założenia.'] },
  { type: 'title', text: 'Co pokazuje wysoka stopa dywidendy', level: 3 }, p('Wysoka stopa może oznaczać dużą wypłatę, ale także spadek ceny. Jest powodem do dalszego sprawdzenia, a nie samodzielnym sygnałem zakupu. Przeanalizuj przepływy pieniężne, zyski, zadłużenie, historię wypłat, politykę spółki i najnowsze komunikaty.'), { type: 'tip', title: 'Wzrost traktuj jako scenariusz', html: '<p>Widok przyszły stosuje wpisany procent tylko do obecnej dywidendy. Nie modeluje reinwestowania, ceny, stopy wypłaty, wzrostu zysków ani przyszłych decyzji spółki.</p>' },
  { type: 'title', text: 'Ograniczenia tego kalkulatora dywidendy', level: 3 }, p('Narzędzie modeluje regularną wypłatę na akcję, częstotliwość roczną lub kwartalną, opcjonalną liczbę akcji, wpisany podatek i jednostopniowy scenariusz wzrostu. Nie prognozuje całkowitego zwrotu, bezpieczeństwa dywidendy, dywidend specjalnych, kursów walut ani lokalnego podatku.'),
] };
