import type { WithContext, FAQPage, HowTo, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { DividendYieldUI } from '../ui';
import { bibliography } from '../bibliography';

const title = 'Calculadora de rendimento de dividendos de ações';
const description = 'Calcule o rendimento bruto e após retenção, o rendimento anual e um cenário de crescimento com os dados da sua ação.';
const faq = [{ question: 'Como calculo o rendimento de dividendos?', answer: 'Multiplique o dividendo por pagamento pelo número de pagamentos anuais, divida pelo preço da ação e multiplique por 100. Para pagamentos trimestrais, multiplique primeiro por quatro.' }, { question: 'Devo inserir um dividendo anual ou trimestral?', answer: 'Escolha a frequência correspondente ao valor inserido. A calculadora anualiza automaticamente os pagamentos trimestrais.' }, { question: 'Qual é a diferença entre rendimento bruto e líquido?', answer: 'O rendimento bruto é o dividendo anual antes da retenção inserida. O rendimento líquido subtrai essa percentagem como uma estimativa simples; a tributação real pode ser diferente.' }, { question: 'Um rendimento elevado significa que uma ação é melhor?', answer: 'Não. O rendimento pode subir porque o preço caiu, e a empresa pode reduzir ou suspender o dividendo. Analise a empresa e os riscos separadamente.' }];
const howTo = [{ name: 'Insira o preço da ação', text: 'Digite o preço por ação que pretende usar como referência.' }, { name: 'Adicione o pagamento', text: 'Insira o dividendo por ação e escolha uma frequência anual ou trimestral.' }, { name: 'Analise o resultado', text: 'Veja o rendimento bruto, após retenção e o rendimento anual. Use o crescimento apenas como cenário separado.' }];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, inLanguage: 'pt' };
const ui: DividendYieldUI = { priceLabel: 'Preço da ação', priceHelp: 'Insira um valor na sua moeda', dividendLabel: 'Dividendo por pagamento', dividendHelp: 'Valor por ação na mesma moeda', cadenceLabel: 'Frequência de pagamento', annualOption: 'Anual', quarterlyOption: 'Trimestral', sharesLabel: 'Ações detidas', sharesHelp: 'Opcional para o rendimento total', withholdingLabel: 'Retenção (%)', withholdingHelp: 'Estimativa simples do rendimento líquido', growthLabel: 'Cenário de crescimento (%)', growthHelp: 'Valor opcional para o cenário futuro', grossYieldLabel: 'Rendimento bruto de dividendos', netYieldLabel: 'Após retenção', grossIncomeLabel: 'Rendimento anual bruto', netIncomeLabel: 'Rendimento anual líquido', annualDividendLabel: 'Dividendo anual', priceShareLabel: 'Preço da ação', couponNote: 'A faixa transforma o dividendo anual numa proporção do preço introduzido.', forwardTitle: 'Cenário futuro com a sua hipótese de crescimento', forwardYieldLabel: 'Rendimento se o dividendo crescer como indicado', forwardDividendLabel: 'Dividendo futuro por ação', growthNote: 'É um cenário, não uma previsão.', formulaTitle: 'Como funciona o cálculo', formulaText: 'O dividendo anual por ação é o valor do pagamento multiplicado pelo número de pagamentos. O rendimento bruto é o dividendo anual por ação dividido pelo preço, multiplicado por 100. O rendimento líquido aplica a retenção ao rendimento bruto. O crescimento altera apenas o cenário futuro.', riskNote: 'O rendimento é uma proporção baseada nos valores introduzidos. Não inclui variações de preço, comissões, cortes, inflação ou o risco de alteração da distribuição.', emptyMessage: 'Insira um preço positivo e um dividendo não negativo para ver o resultado.', annualSuffix: 'por ano', perShareSuffix: 'por ação', percentageSuffix: '%', };
const p = (html: string) => ({ type: 'paragraph' as const, html: `<p>${html}</p>` });
export const content: ToolLocaleContent<DividendYieldUI> = { slug: 'calculadora-rendimento-dividendos-acoes', title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo: [
  { type: 'title', text: 'Compreender e calcular o rendimento de dividendos', level: 2 }, p('O rendimento de dividendos compara a distribuição anual em dinheiro de uma ação com o preço usado como referência. Esta calculadora anualiza um pagamento, divide-o pelo preço da ação e mostra o resultado em percentagem. Também estima o rendimento anual e separa o valor bruto de uma hipótese simples após retenção.'), p('O resultado é uma proporção, não uma promessa de retorno. Não inclui variações de preço, comissões, câmbio, dividendos extraordinários nem o risco de a empresa reduzir ou cancelar o pagamento. Use-o para comparar valores e depois analise a empresa e o título.'),
  { type: 'title', text: 'A fórmula do rendimento de dividendos', level: 3 }, p('A fórmula é <strong>rendimento de dividendos = dividendo anual por ação / preço da ação x 100</strong>. Nos pagamentos trimestrais, o valor é multiplicado por quatro antes do cálculo. Nos pagamentos anuais, usa-se diretamente o valor inserido.'),
  { type: 'table', headers: ['Valor', 'Cálculo', 'Utilidade'], rows: [['Dividendo anual por ação', 'Valor por pagamento x pagamentos por ano', 'Coloca pagamentos anuais e trimestrais na mesma base'], ['Rendimento bruto', 'Dividendo anual / preço x 100', 'Mostra a distribuição como percentagem do preço de referência'], ['Rendimento anual bruto', 'Dividendo anual por ação x ações', 'Estima o rendimento antes da retenção'], ['Rendimento anual líquido', 'Rendimento bruto x (1 - retenção / 100)', 'Oferece uma estimativa simples após a taxa indicada']] },
  { type: 'title', text: 'Exemplo com pagamentos anuais e trimestrais', level: 3 }, p('Imagine uma ação a 100 na sua moeda que paga 1 por trimestre. O dividendo anual é 1 x 4 = 4 e o rendimento bruto é 4 / 100 x 100 = 4%. Com 50 ações, o rendimento anual bruto estimado é 200 antes da retenção.'), p('Se a mesma ação pagasse 4 uma vez por ano, o resultado continuaria a ser 4%. A frequência apenas altera a anualização, por isso escolhê-la mal distorce o cálculo.'),
  { type: 'title', text: 'Por que o preço da ação muda o rendimento', level: 3 }, p('O rendimento pode mudar mesmo quando a empresa mantém o mesmo dividendo. Com um dividendo anual de 4, um preço de 100 produz 4%, enquanto um preço de 80 produz 5%. A percentagem maior pode refletir apenas um preço de mercado mais baixo, e não um negócio mais rentável.'), p('Para comparar ações, utilize a mesma referência de preço: preço atual, fecho de uma data ou preço de compra. Registe a data do preço e o período do dividendo, pois ambos alteram a interpretação.'),
  { type: 'title', text: 'Não confunda rendimento, retenção e rendimento anual', level: 3 }, { type: 'comparative', columns: 3, items: [{ title: 'Rendimento bruto', description: 'Dividendo anual por ação comparado com o preço de referência.', points: ['Compara distribuição e preço', 'Não desconta retenção', 'Não inclui ganhos ou perdas de preço'] }, { title: 'Rendimento após retenção', description: 'Rendimento bruto reduzido pela percentagem inserida.', points: ['Hipótese simples para planeamento', 'A tributação real pode variar', 'Não é uma declaração fiscal'], highlight: true }, { title: 'Rendimento anual', description: 'Valor em dinheiro do dividendo e das ações detidas.', points: ['Bruto antes da retenção', 'Líquido usa a taxa indicada', 'Depende do número de ações'] }] }, p('A retenção não é necessariamente o seu imposto final. Residência, país da empresa, tipo de conta, convenções fiscais e reembolsos podem ser relevantes. A calculadora aplica apenas a percentagem inserida.'),
  { type: 'title', text: 'Como usar bem a calculadora', level: 3 }, { type: 'list', items: ['Insira preço e dividendo na mesma moeda e numa base temporal comparável.', 'Escolha Anual ou Trimestral de acordo com a frequência do valor.', 'Adicione as ações quando precisar do rendimento total.', 'Use a retenção como hipótese explícita e confirme as regras separadamente.', 'Use o crescimento para testar um cenário, não para prever o futuro.', 'Anote a data do preço e o período do dividendo numa comparação.'] },
  { type: 'title', text: 'O que um rendimento elevado pode ou não indicar', level: 3 }, p('Um rendimento elevado pode indicar uma distribuição generosa, mas também resultar de uma queda do preço. Deve motivar investigação, não ser um sinal de compra isolado. Consulte fluxos de caixa, lucros, dívida, histórico, política de distribuição e comunicações recentes.'), { type: 'tip', title: 'Trate o crescimento como um cenário', html: '<p>A vista futura aplica apenas a percentagem indicada ao dividendo atual. Não modela reinvestimento, preço, payout, crescimento dos lucros ou decisões futuras da empresa.</p>' },
  { type: 'title', text: 'Limitações desta calculadora de dividendos', level: 3 }, p('A ferramenta modela um pagamento regular por ação, frequência anual ou trimestral, número opcional de ações, retenção inserida e um cenário de crescimento numa etapa. Não prevê o retorno total, a segurança do dividendo, dividendos especiais, conversão cambial ou impostos locais.'),
] };
