import type { WithContext, FAQPage, HowTo, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { DividendYieldUI } from '../ui';
import { bibliography } from '../bibliography';

const title = 'Kalkylator för aktiers direktavkastning';
const description = 'Beräkna brutto och netto direktavkastning, årsinkomst och ett tillväxtscenario med dina egna aktieuppgifter.';
const faq = [{ question: 'Hur räknar jag ut direktavkastning?', answer: 'Multiplicera utdelningen per betalning med antalet betalningar per år, dela med aktiekursen och multiplicera med 100. Vid kvartalsutdelning multiplicerar du först med fyra.' }, { question: 'Ska jag ange årlig eller kvartalsvis utdelning?', answer: 'Välj den frekvens som motsvarar beloppet du anger. Kalkylatorn räknar automatiskt om kvartalsbetalningar till årsbasis.' }, { question: 'Vad är skillnaden mellan brutto och netto utdelningsinkomst?', answer: 'Bruttoinkomst är årsutdelningen före den innehållning du anger. Nettoinkomst drar av den procentsatsen som en enkel uppskattning; din faktiska skatt kan skilja sig.' }, { question: 'Betyder hög direktavkastning att en aktie är bättre?', answer: 'Nej. Avkastningen kan öka när kursen faller och ett företag kan sänka eller stoppa utdelningen. Granska företaget och riskerna separat.' }];
const howTo = [{ name: 'Ange aktiekursen', text: 'Skriv in priset per aktie som du vill använda som referens.' }, { name: 'Lägg till utdelningen', text: 'Ange utdelning per aktie och välj årlig eller kvartalsvis betalning.' }, { name: 'Granska resultatet', text: 'Läs bruttoavkastning, avkastning efter innehållning och årsinkomst. Använd tillväxt som ett separat scenario.' }];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, inLanguage: 'sv' };
const ui: DividendYieldUI = { priceLabel: 'Aktiekurs', priceHelp: 'Ange ett belopp i din valuta', dividendLabel: 'Utdelning per betalning', dividendHelp: 'Belopp per aktie i samma valuta', cadenceLabel: 'Betalningsfrekvens', annualOption: 'Årlig', quarterlyOption: 'Kvartalsvis', sharesLabel: 'Antal aktier', sharesHelp: 'Valfritt för total inkomst', withholdingLabel: 'Innehållning (%)', withholdingHelp: 'Enkel uppskattning av nettoinkomst', growthLabel: 'Antagen tillväxt (%)', growthHelp: 'Valfritt värde för framtidsscenariot', grossYieldLabel: 'Brutto direktavkastning', netYieldLabel: 'Efter innehållning', grossIncomeLabel: 'Brutto årsinkomst', netIncomeLabel: 'Netto årsinkomst', annualDividendLabel: 'Årlig utdelning', priceShareLabel: 'Aktiekurs', couponNote: 'Bandet visar den årliga utdelningen som andel av den angivna aktiekursen.', forwardTitle: 'Framtidsscenario med ditt tillväxtantagande', forwardYieldLabel: 'Avkastning om utdelningen växer enligt antagandet', forwardDividendLabel: 'Framtida utdelning per aktie', growthNote: 'Detta är ett scenario, inte en prognos.', formulaTitle: 'Så fungerar beräkningen', formulaText: 'Årlig utdelning per aktie är betalningsbeloppet multiplicerat med antalet betalningar. Brutto direktavkastning är årlig utdelning per aktie delat med aktiekursen, multiplicerat med 100. Nettoinkomst tillämpar innehållningen på bruttoinkomsten. Tillväxt ändrar bara framtidsscenariot.', riskNote: 'Direktavkastningen är ett förhållande baserat på dina uppgifter. Kursförändringar, avgifter, sänkta utdelningar, inflation och risken att företaget ändrar sin utdelning ingår inte.', emptyMessage: 'Ange en positiv aktiekurs och en utdelning som inte är negativ för att se resultatet.', annualSuffix: 'per år', perShareSuffix: 'per aktie', percentageSuffix: '%', };
const p = (html: string) => ({ type: 'paragraph' as const, html: `<p>${html}</p>` });
export const content: ToolLocaleContent<DividendYieldUI> = { slug: 'kalkylator-direktavkastning-aktier', title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo: [
  { type: 'title', text: 'Förstå och beräkna aktiers direktavkastning', level: 2 }, p('Direktavkastning jämför en akties årliga kontantutdelning med aktiekursen som används som referens. Kalkylatorn räknar om en betalning till ett årsbelopp, delar det med aktiekursen och visar resultatet i procent. Du kan också uppskatta årsinkomst och en enkel beräkning efter innehållning.'), p('Resultatet är ett förhållande och inte ett löfte om avkastning. Kursförändringar, avgifter, valuta, extrautdelningar och risken för sänkt eller inställd utdelning ingår inte. Använd siffran som utgångspunkt och undersök sedan bolaget och aktien.'),
  { type: 'title', text: 'Formeln för direktavkastning', level: 3 }, p('<strong>Direktavkastning = årlig utdelning per aktie / aktiekurs x 100</strong>. Vid kvartalsutdelning multipliceras beloppet med fyra före beräkningen. Vid årsutdelning används det angivna beloppet direkt.'),
  { type: 'table', headers: ['Värde', 'Beräkning', 'Betydelse'], rows: [['Årlig utdelning per aktie', 'Belopp per betalning x betalningar per år', 'Gör årliga och kvartalsvisa betalningar jämförbara'], ['Brutto direktavkastning', 'Årlig utdelning / aktiekurs x 100', 'Visar utdelningen som andel av referenskursen'], ['Brutto årsinkomst', 'Årlig utdelning per aktie x aktier', 'Uppskattar inkomst före innehållning'], ['Netto årsinkomst', 'Bruttoinkomst x (1 - innehållning / 100)', 'Ger en enkel uppskattning efter angiven procentsats']] },
  { type: 'title', text: 'Exempel med årliga och kvartalsvisa betalningar', level: 3 }, p('Anta en aktiekurs på 100 och en utdelning på 1 varje kvartal. Årsutdelningen är 1 x 4 = 4 och brutto direktavkastning är 4 / 100 x 100 = 4%. Med 50 aktier blir den uppskattade brutto årsinkomsten 200 före innehållning.'), p('Om samma aktie betalade 4 en gång om året skulle avkastningen fortfarande vara 4%. Frekvensen ändrar bara omräkningen till årsbasis. Fel frekvens kan därför ge ett missvisande resultat.'),
  { type: 'title', text: 'Varför aktiekursen ändrar avkastningen', level: 3 }, p('Avkastningen kan ändras även om bolaget behåller samma utdelning. Med en årsutdelning på 4 ger en kurs på 100 en avkastning på 4%, medan en kurs på 80 ger 5%. Den högre siffran betyder inte automatiskt ett lönsammare företag; den kan bero på en lägre marknadskurs.'), p('Använd samma kursgrund när du jämför aktier: aktuell kurs, stängningskurs på ett visst datum eller inköpskurs. Anteckna kursdatum och utdelningsperiod eftersom båda påverkar tolkningen.'),
  { type: 'title', text: 'Skilj på avkastning, innehållning och inkomst', level: 3 }, { type: 'comparative', columns: 3, items: [{ title: 'Bruttoavkastning', description: 'Årlig utdelning per aktie jämförd med referenskursen.', points: ['Jämför utdelning och pris', 'Drar inte av innehållning', 'Omfattar inte kursvinst eller kursförlust'] }, { title: 'Avkastning efter innehållning', description: 'Bruttoavkastning minskad med den angivna procentsatsen.', points: ['Enkel planeringshypotes', 'Verklig skatt kan skilja sig', 'Inte ett skattebesked'], highlight: true }, { title: 'Årsinkomst', description: 'Kontantbelopp från årlig utdelning och antal aktier.', points: ['Brutto är före innehållning', 'Netto använder angiven sats', 'Beror på antal aktier'] }] }, p('Innehållning är inte alltid samma sak som din slutliga skatt. Hemvist, bolagets land, konto, skatteavtal och återbetalningsförfaranden kan påverka. Kalkylatorn använder bara den procentsats du anger.'),
  { type: 'title', text: 'Så använder du kalkylatorn på ett bra sätt', level: 3 }, { type: 'list', items: ['Ange pris och utdelning i samma valuta och på jämförbar tidsbasis.', 'Välj Årlig eller Kvartalsvis enligt beloppets betalningsfrekvens.', 'Lägg till antal aktier när du behöver total inkomst.', 'Använd innehållning som ett tydligt antagande och kontrollera reglerna separat.', 'Använd tillväxt för att testa ett scenario, inte för att förutsäga framtiden.', 'Anteckna kursdatum och utdelningsperiod vid jämförelser.'] },
  { type: 'title', text: 'Vad hög direktavkastning kan och inte kan visa', level: 3 }, p('Hög avkastning kan betyda en stor utdelning, men också bero på att aktiekursen har fallit. Se den som en anledning att undersöka vidare och inte som en ensam köpsignal. Kontrollera kassaflöde, vinst, skulder, historik, utdelningspolicy och nya meddelanden.'), { type: 'tip', title: 'Behandla tillväxt som ett scenario', html: '<p>Framtidsvyn tillämpar bara den angivna tillväxten på den aktuella utdelningen. Den modellerar inte återinvestering, kurs, utdelningsandel, vinsttillväxt eller framtida beslut.</p>' },
  { type: 'title', text: 'Begränsningar i denna utdelningskalkylator', level: 3 }, p('Verktyget modellerar en regelbunden betalning per aktie, årlig eller kvartalsvis frekvens, valfritt antal aktier, angiven innehållning och ett tillväxtscenario i ett steg. Det prognostiserar inte total avkastning, utdelningssäkerhet, extrautdelningar, valutaomräkning eller lokal skatt.'),
] };
