import type { WithContext, FAQPage, HowTo, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { DividendYieldUI } from '../ui';
import { bibliography } from '../bibliography';

const title = 'Hisse temettü verimi hesaplama aracı';
const description = 'Kendi hisse verilerinizle brüt ve kesinti sonrası temettü verimini, yıllık geliri ve büyüme senaryosunu hesaplayın.';
const faq = [{ question: 'Temettü verimi nasıl hesaplanır?', answer: 'Ödeme başına temettüyü yıllık ödeme sayısıyla çarpın, hisse fiyatına bölün ve 100 ile çarpın. Üç aylık ödemede önce dört ile çarpılır.' }, { question: 'Yıllık mı yoksa üç aylık temettü mü girmeliyim?', answer: 'Girdiğiniz tutara uyan sıklığı seçin. Hesaplama aracı üç aylık ödemeleri otomatik olarak yıllık tutara çevirir.' }, { question: 'Brüt ve net temettü geliri arasındaki fark nedir?', answer: 'Brüt gelir, girdiğiniz kesinti oranından önceki yıllık temettüdür. Net gelir bu oranı basit bir tahmin olarak düşer; gerçek verginiz farklı olabilir.' }, { question: 'Yüksek temettü verimi hissenin daha iyi olduğu anlamına mı gelir?', answer: 'Hayır. Hisse fiyatı düştüğü için verim yükselebilir ve şirket temettüyü azaltabilir veya durdurabilir. Şirketi ve riskleri ayrıca inceleyin.' }];
const howTo = [{ name: 'Hisse fiyatını girin', text: 'Referans olarak kullanmak istediğiniz hisse başına fiyatı yazın.' }, { name: 'Temettü ödemesini ekleyin', text: 'Hisse başına temettüyü girin ve yıllık ya da üç aylık sıklığı seçin.' }, { name: 'Sonucu inceleyin', text: 'Brüt verimi, kesinti sonrası verimi ve yıllık geliri okuyun. Büyümeyi yalnızca ayrı bir senaryo olarak kullanın.' }];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, inLanguage: 'tr' };
const ui: DividendYieldUI = { priceLabel: 'Hisse fiyatı', priceHelp: 'Kendi para biriminizde tutar girin', dividendLabel: 'Ödeme başına temettü', dividendHelp: 'Aynı para biriminde hisse başına tutar', cadenceLabel: 'Ödeme sıklığı', annualOption: 'Yıllık', quarterlyOption: 'Üç aylık', sharesLabel: 'Sahip olunan hisse', sharesHelp: 'Toplam gelir için isteğe bağlı', withholdingLabel: 'Kesinti oranı (%)', withholdingHelp: 'Net gelir için basit tahmin', growthLabel: 'Varsayılan büyüme (%)', growthHelp: 'Gelecek senaryosu için isteğe bağlı', grossYieldLabel: 'Brüt temettü verimi', netYieldLabel: 'Kesinti sonrası', grossIncomeLabel: 'Brüt yıllık gelir', netIncomeLabel: 'Net yıllık gelir', annualDividendLabel: 'Yıllık temettü', priceShareLabel: 'Hisse fiyatı', couponNote: 'Şerit, yıllık temettüyü girilen hisse fiyatının bir oranı olarak gösterir.', forwardTitle: 'Büyüme varsayımınızla gelecek senaryosu', forwardYieldLabel: 'Temettü girilen oranda büyürse verim', forwardDividendLabel: 'Hisse başına gelecek temettüsü', growthNote: 'Bu bir senaryodur, tahmin değildir.', formulaTitle: 'Hesaplama nasıl çalışır?', formulaText: 'Hisse başına yıllık temettü, ödeme tutarının yıllık ödeme sayısıyla çarpılmasıdır. Brüt verim, hisse başına yıllık temettünün fiyata bölünüp 100 ile çarpılmasıdır. Net gelirde kesinti oranı brüt gelire uygulanır. Büyüme yalnızca gelecek senaryosunu değiştirir.', riskNote: 'Temettü verimi girdiğiniz değerlere dayalı bir orandır. Fiyat değişimleri, ücretler, temettü kesintileri, enflasyon ve şirketin dağıtımı değiştirme riski dahil değildir.', emptyMessage: 'Sonucu görmek için pozitif bir hisse fiyatı ve negatif olmayan bir temettü girin.', annualSuffix: 'yıllık', perShareSuffix: 'hisse başına', percentageSuffix: '%', };
const p = (html: string) => ({ type: 'paragraph' as const, html: `<p>${html}</p>` });
export const content: ToolLocaleContent<DividendYieldUI> = { slug: 'hisse-temettu-verimi-hesaplama', title, description, ui, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema], seo: [
  { type: 'title', text: 'Hisse temettü verimini anlama ve hesaplama', level: 2 }, p('Temettü verimi, bir hissenin yıllık nakit dağıtımını referans olarak kullanılan hisse fiyatıyla karşılaştırır. Bu araç bir ödemeyi yıllık tutara çevirir, hisse fiyatına böler ve sonucu yüzde olarak gösterir. Hisse sayınıza göre yıllık geliri ve kesinti sonrası basit bir senaryoyu da inceleyebilirsiniz.'), p('Sonuç bir orandır, getiri garantisi değildir. Fiyat değişimleri, ücretler, kur hareketleri, özel temettüler ve şirketin ödemeyi azaltma veya durdurma riski dahil değildir. Karşılaştırmaya başlangıç olarak kullanın, ardından şirketi ve hisseyi araştırın.'),
  { type: 'title', text: 'Temettü verimi formülü', level: 3 }, p('<strong>Temettü verimi = hisse başına yıllık temettü / hisse fiyatı x 100</strong>. Üç aylık ödemede tutar hesaplamadan önce dört ile çarpılır; yıllık ödemede girilen tutar doğrudan kullanılır.'),
  { type: 'table', headers: ['Değer', 'Hesaplama', 'Anlamı'], rows: [['Hisse başına yıllık temettü', 'Ödeme tutarı x yıllık ödeme sayısı', 'Yıllık ve üç aylık ödemeleri aynı temele getirir'], ['Brüt temettü verimi', 'Yıllık temettü / fiyat x 100', 'Dağıtımı referans fiyatın yüzdesi olarak gösterir'], ['Brüt yıllık gelir', 'Yıllık temettü x hisse sayısı', 'Kesinti öncesi geliri tahmin eder'], ['Net yıllık gelir', 'Brüt gelir x (1 - kesinti / 100)', 'Girilen orandan sonra basit tahmin sağlar']] },
  { type: 'title', text: 'Yıllık ve üç aylık ödeme örneği', level: 3 }, p('Fiyatı 100 olan bir hissenin her üç ayda 1 ödediğini düşünün. Yıllık temettü 1 x 4 = 4, brüt verim ise 4 / 100 x 100 = 4% olur. 50 hisse için kesinti öncesi yıllık gelir 200 olarak tahmin edilir.'), p('Aynı hisse yılda bir kez 4 ödeseydi verim yine 4% olurdu. Sıklık yalnızca yıllıklaştırmayı değiştirir; yanlış seçim sonucu bozabilir.'),
  { type: 'title', text: 'Hisse fiyatı verimi neden değiştirir?', level: 3 }, p('Şirket aynı temettüyü korusa bile verim değişebilir. Yıllık temettü 4 iken fiyat 100 verimi 4%, fiyat 80 ise 5% yapar. Yüksek oran şirketin daha kârlı olduğunu göstermez; yalnızca daha düşük piyasa fiyatını yansıtabilir.'), p('Karşılaştırma yaparken aynı fiyat temelini kullanın: güncel fiyat, belirli bir tarihin kapanışı veya alış fiyatınız. Fiyat tarihini ve temettü dönemini kaydedin, çünkü yorum bunlara bağlıdır. Geçmiş alış fiyatınıza göre hesaplanan kişisel getiri ile bugün yeni bir yatırımcının göreceği piyasa verimini de birbirinden ayırın; ikisi farklı sorulara cevap verir.'),
  { type: 'title', text: 'Verim, kesinti ve geliri birbirine karıştırmayın', level: 3 }, { type: 'comparative', columns: 3, items: [{ title: 'Brüt verim', description: 'Hisse başına yıllık temettünün referans fiyata oranı.', points: ['Dağıtım ve fiyatı karşılaştırır', 'Kesintiyi düşmez', 'Fiyat kazancı veya kaybını içermez'] }, { title: 'Kesinti sonrası verim', description: 'Girilen oranla azaltılmış brüt verim.', points: ['Planlama için basit senaryo', 'Gerçek vergi değişebilir', 'Vergi beyannamesi sonucu değildir'], highlight: true }, { title: 'Yıllık gelir', description: 'Yıllık temettü ve hisse sayısından gelen nakit.', points: ['Brüt tutar kesinti öncesidir', 'Net tutar girilen oranı kullanır', 'Hisse sayısına bağlıdır'] }] }, p('Kesinti oranı nihai verginizle aynı olmayabilir. İkamet, şirketin ülkesi, hesap türü, vergi anlaşmaları ve iade süreçleri etkili olabilir. Araç yalnızca girdiğiniz oranı uygular.'),
  { type: 'title', text: 'Hesaplama aracını doğru kullanma', level: 3 }, { type: 'list', items: ['Fiyatı ve temettüyü aynı para biriminde ve karşılaştırılabilir dönemde girin.', 'Tutarın sıklığına göre Yıllık veya Üç aylık seçin.', 'Toplam gelir için sahip olduğunuz hisse sayısını ekleyin.', 'Kesintiyi açık bir varsayım olarak kullanın ve kuralları ayrıca kontrol edin.', 'Büyümeyi tahmin için değil, senaryo testi için kullanın.', 'Karşılaştırmada fiyat tarihini ve temettü dönemini not edin.'] },
  { type: 'title', text: 'Yüksek temettü verimi neyi gösterir?', level: 3 }, p('Yüksek verim büyük bir dağıtımın sonucu olabilir, ancak fiyat düşüşünden de kaynaklanabilir. Tek başına alım sinyali değil, araştırma nedeni olarak görün. Nakit akışı, kâr, borç, dağıtım geçmişi, şirket politikası ve son açıklamaları inceleyin.'), { type: 'tip', title: 'Büyümeyi senaryo olarak ele alın', html: '<p>Gelecek görünümü yalnızca girdiğiniz büyüme oranını mevcut temettüye uygular. Yeniden yatırım, fiyat, dağıtım oranı, kâr büyümesi veya gelecekteki şirket kararlarını modellemez.</p>' },
  { type: 'title', text: 'Bu temettü verimi aracının sınırları', level: 3 }, p('Araç düzenli hisse başı ödemeyi, yıllık veya üç aylık sıklığı, isteğe bağlı hisse sayısını, girilen kesintiyi ve tek adımlı büyüme senaryosunu modeller. Toplam getiriyi, temettü güvenliğini, özel temettüleri, döviz dönüşümünü veya yerel vergiyi hesaplamaz. Sonucu bir yatırım tavsiyesi olarak değil, karşılaştırma ve araştırma için başlangıç noktası olarak değerlendirin.'),
] };
