import { bibliography } from '../bibliography';
import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { MortgageExtraPaymentPlannerUI } from '../ui';

const slug = 'mortgage-amortization-extra-payment-planner';
const title = '繰り上げ返済対応の住宅ローン返済計画';
const description = '固定金利の住宅ローンに定期的または一度きりの繰り上げ返済を追加し、節約できる利息を比較して、すべての金額を1つの通貨で確認します。';
const ui: MortgageExtraPaymentPlannerUI = {
  currencyLabel: '通貨', currencyHelp: '1つだけ選択します。計画内のすべての金額にこの通貨を使います。', principalLabel: '開始時の元金残高', principalHelp: '計画開始時点で残っている借入額', annualRateLabel: '年利', annualRateHelp: '各支払期間に使う名目固定金利', termLabel: '残りの期間（年）', termHelp: '繰り上げ返済を行わない場合の予定期間', frequencyLabel: '支払頻度', recurringExtraLabel: '定期的な繰り上げ返済', recurringExtraHelp: '毎回の支払期間に追加する元金', oneOffExtraLabel: '一度きりの繰り上げ返済', oneOffExtraHelp: '指定した期間に行う1回の元金返済', oneOffPeriodLabel: '一度きりの返済期間', oneOffPeriodHelp: '1は最初の支払期間を表します', startDateLabel: '初回支払日', startDateHelp: '完済予定日の推定に使います', extraSectionTitle: '繰り上げ返済プラン', outputTitle: '残高の推移', regularPaymentLabel: '繰り上げ前の通常返済額', interestSavedLabel: '節約できる利息', periodsSavedLabel: '短縮される期間', payoffDateLabel: '完済予定日', totalInterestLabel: 'このプランで支払う利息', totalExtraLabel: '追加返済する元金', baselineLabel: '元の返済計画', planLabel: '繰り上げ返済あり', balanceSceneLabel: '元の住宅ローン残高と繰り上げ返済後の残高', balanceSceneHelp: '破線は元の計画、銅色の線は入力した計画です。緑の印は追加元金のある期間を示します。', annualScheduleTitle: '年別支払予定表', yearLabel: '年', paymentLabel: '支払総額', interestLabel: '利息', principalPaidLabel: '予定元金', extraPaidLabel: '追加元金', endingBalanceLabel: '年末残高', formulaTitle: 'モデルと制限', formulaText: '固定金利の返済モデルを使います。各期間の開始残高から利息を計算し、通常返済を利息と元金に配分した後、定期および一度きりの繰り上げ返済を適用します。年利は年間の支払回数で割ります。残高が予定返済額より小さい場合、最後の返済額は減額されます。通貨を変更すると内部の計画比率で金額を換算し、同じシナリオを再計算します。', riskNote: 'これは目安であり、金融機関の明細ではありません。通貨選択ではリアルタイムの市場レートではなく内部の計画比率を使います。変動金利、手数料、保険、税金、日割り利息、違約金、契約上の繰り上げ返済規則は含みません。', emptyMessage: '有効な元金、金利、期間、日付を入力すると計画を表示できます。', invalidInputMessage: '計画を表示するには入力を確認してください', currencyOptions: { AUD: 'A$ AUD · オーストラリアドル', BRL: 'R$ BRL · ブラジルレアル', CAD: 'C$ CAD · カナダドル', CHF: 'CHF · スイスフラン', CNY: '¥ CNY · 中国人民元', CZK: 'Kč CZK · チェココルナ', DKK: 'kr DKK · デンマーククローネ', EUR: '€ EUR · ユーロ', GBP: '£ GBP · 英ポンド', IDR: 'Rp IDR · インドネシアルピア', INR: '₹ INR · インドルピー', JPY: '¥ JPY · 日本円', KRW: '₩ KRW · 韓国ウォン', MXN: 'MX$ MXN · メキシコペソ', NOK: 'kr NOK · ノルウェークローネ', PLN: 'zł PLN · ポーランドズロチ', RUB: '₽ RUB · ロシアルーブル', SEK: 'kr SEK · スウェーデンクローナ', TRY: '₺ TRY · トルコリラ', USD: '$ USD · 米ドル' }, currencySymbols: { AUD: 'A$', BRL: 'R$', CAD: 'C$', CHF: 'CHF', CNY: '¥', CZK: 'Kč', DKK: 'kr', EUR: '€', GBP: '£', IDR: 'Rp', INR: '₹', JPY: '¥', KRW: '₩', MXN: 'MX$', NOK: 'kr', PLN: 'zł', RUB: '₽', SEK: 'kr', TRY: '₺', USD: '$' }, frequencyOptions: { monthly: '毎月', biweekly: '2週間ごと', weekly: '毎週' },
};
const faq = [{ question: '繰り上げ返済で返済計画はどう変わりますか？', answer: '通常の返済額を変えず、予定返済の後に追加元金を適用します。そのため残高が早くゼロになり、利息総額が減る場合があります。金融機関の扱いは契約によって異なるため、結果を契約と照合してください。' }, { question: '通貨を変更するとどうなりますか？', answer: '内部の計画比率で金額を新しい通貨に換算し、同じシナリオを再計算します。リアルタイムの為替レートではないため、計画用の目安として使ってください。' }, { question: 'なぜ通貨セレクターは1つだけですか？', answer: '選択した通貨を元金、繰り上げ返済、通常返済、利息、残高、年別表のすべてに適用します。単一の単位にすることで入力を読みやすくし、通貨の混在を防ぎます。' }, { question: '実際の金融機関の返済額を計算できますか？', answer: '固定金利の返済計画を推定しますが、日数計算、手数料、保険、税金、金利変更、違約金、繰り上げ返済の契約条件は把握できません。契約上の金額は明細と契約書で確認してください。' }];
const howTo = [{ name: '通貨を設定', text: 'すべての金額と結果に使う1つの通貨を選びます。' }, { name: 'ローンを入力', text: '元金、年利、残りの期間、初回支払日、支払頻度を入力します。' }, { name: '繰り上げ返済を追加', text: '定期額を入力し、必要なら一度きりの金額と期間を追加します。' }, { name: '比較を読む', text: '元の残高と計画を比較し、利息、短縮期間、完済日、年別表を確認します。' }];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'JPY' }, inLanguage: 'ja' };
const seo: ToolLocaleContent['seo'] = [{ type: 'title', text: '繰り上げ返済の効果を計画する', level: 2 }, { type: 'paragraph', html: '<p>返済予定表は各回の支払いを利息と元金に分けます。追加の元金を払い、通常返済額を変えない場合、残高を早くゼロにできます。このツールは元の残高と、定期・一時的な繰り上げ返済を入れた残高を比較します。</p>' }, { type: 'paragraph', html: '<p>結果は固定金利ローンの計画用推定です。元金、名目年利、支払回数、各回の後に変わる残高を使います。契約の手数料、丸め、日数計算、繰り上げ返済の扱いは異なることがあります。</p>' }, { type: 'title', text: '返済計算の仕組み', level: 3 }, { type: 'paragraph', html: '<p>各期間の開始残高に対して利息を計算します。年利を年間の支払回数で割り、通常返済を利息と元金に分け、さらに追加元金を残高から差し引きます。</p>' }, { type: 'table', headers: ['項目', '計算', '意味'], rows: [['期間利率', '年利 / 年間支払回数', '各期間に適用する利率'], ['通常返済', '固定返済の式', '追加返済前の支払額'], ['期間利息', '開始残高 x 期間利率', 'モデルが想定する利息'], ['支払後残高', '開始残高 - 元金 - 追加分', 'まだ残っている金額']] }, { type: 'title', text: '繰り上げ返済で変わるもの', level: 3 }, { type: 'paragraph', html: '<p>このモデルでは追加支払いが元金を直接減らすため、後の利息は小さくなった残高にかかります。節約できる利息と短縮される期間の両方を見ると、費用と完済時期を分けて理解できます。</p>' }, { type: 'paragraph', html: '<p>金融機関は返済額を下げたり期間を維持したり、正式な申請を求めたりすることがあります。年ごとの上限、最低額、手数料を確認してください。</p>' }, { type: 'title', text: '通貨を混ぜずに計画する', level: 3 }, { type: 'paragraph', html: '<p>金額を入力する前に1つの通貨を選びます。元金、追加返済、通常返済、利息、残高に同じ単位を使い、変更時は内部で換算して同じシナリオを計算します。</p>' }, { type: 'list', items: ['家計や金融機関の明細に合わせた通貨を選ぶ。', '元金と追加返済を選択した通貨で入力する。', '通貨変更は計画単位の変更であり、契約変更ではないと考える。', '支払頻度と繰り上げ返済の規則を確認する。', '年別表で一時的な返済の影響を確認する。'] }, { type: 'title', text: '結果を読む簡単な例', level: 3 }, { type: 'paragraph', html: '<p>250,000 EUR、固定年利3.5%、25年の場合、各期間150 EURと12期間目の5,000 EURを追加しても、このモデルの通常返済額は変わりません。ただし残高と後の利息は減ります。</p>' }, { type: 'paragraph', html: '<p>USDに切り替えると、内部の計画比率で金額を換算し、同じシナリオを再計算します。国際的な予算には便利ですが、現在の市場価格や為替の提示ではありません。</p>' }, { type: 'title', text: '実行前に確認すること', level: 3 }, { type: 'list', items: ['追加返済で期間が短くなるか、返済額が下がるかを聞く。', '上限、最低額、手数料を確認する。', '金利が名目・実効・固定・変動のどれかを確認する。', '計算した残高を最新の明細と比べる。', '国際予算では使った為替と日付を記録する。'] }, { type: 'tip', title: 'グラフは比較であり、約束ではありません', html: '<p>破線は追加返済なしの元の計画、銅色の線は入力した計画です。手数料、保険、税金、日割り利息、為替変動、金融機関の契約規則は含まれません。</p>' }, { type: 'title', text: 'この住宅ローン計画の制限', level: 3 }, { type: 'paragraph', html: '<p>固定金利で定期返済し、任意の追加元金を払うローンをモデル化します。シナリオ検討や金融機関への質問には役立ちますが、返済能力の判定、税務・法律助言、為替予測、公式明細の代替にはなりません。</p>' }];
export const content: ToolLocaleContent<MortgageExtraPaymentPlannerUI> = { slug, title, description, ui, faq, bibliography, howTo, schemas: [appSchema, faqSchema, howToSchema], seo };
