import { bibliography } from '../bibliography';
import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { MortgageExtraPaymentPlannerUI } from '../ui';

const slug = 'mortgage-amortization-extra-payment-planner';
const title = '추가 상환을 포함한 주택담보대출 상환 계획';
const description = '고정금리 주택담보대출에 정기 또는 일회성 추가 상환을 적용하고, 절약되는 이자와 상환 기간을 비교하며 모든 금액을 하나의 통화로 확인하세요.';
const ui: MortgageExtraPaymentPlannerUI = {
  currencyLabel: '통화', currencyHelp: '하나만 선택하세요. 계획의 모든 금액에 이 통화를 사용합니다.', principalLabel: '시작 원금', principalHelp: '계획 시작 시 아직 갚지 않은 금액', annualRateLabel: '연 이자율', annualRateHelp: '각 납부 기간에 적용하는 명목 고정금리', termLabel: '남은 기간(년)', termHelp: '추가 상환 전의 계획 기간', frequencyLabel: '납부 주기', recurringExtraLabel: '정기 추가 상환', recurringExtraHelp: '매 기간 추가로 갚는 원금', oneOffExtraLabel: '일회성 추가 상환', oneOffExtraHelp: '아래 기간에 한 번 납부하는 원금', oneOffPeriodLabel: '일회성 상환 기간', oneOffPeriodHelp: '1은 첫 번째 납부 기간입니다', startDateLabel: '첫 납부일', startDateHelp: '예상 완납일을 계산하는 데 사용합니다', extraSectionTitle: '추가 상환 계획', outputTitle: '잔액 변화', regularPaymentLabel: '추가 상환 전 정기 납부액', interestSavedLabel: '절약되는 이자', periodsSavedLabel: '단축되는 기간', payoffDateLabel: '예상 완납일', totalInterestLabel: '이 계획에서 납부하는 이자', totalExtraLabel: '추가 상환 원금', baselineLabel: '기존 일정', planLabel: '추가 상환 적용', balanceSceneLabel: '기존 대출 잔액과 추가 상환 후 잔액 비교', balanceSceneHelp: '점선은 기존 일정을, 구리색 선은 입력한 계획을 보여줍니다. 녹색 표시는 추가 원금이 납부되는 기간입니다.', annualScheduleTitle: '연간 납부 일정', yearLabel: '연도', paymentLabel: '총 납부액', interestLabel: '이자', principalPaidLabel: '예정 원금', extraPaidLabel: '추가 원금', endingBalanceLabel: '기말 잔액', formulaTitle: '모델과 한계', formulaText: '고정금리 상환 모델을 사용합니다. 각 기간의 시작 잔액에서 이자를 계산하고, 정기 납부액을 이자와 원금으로 나눈 뒤 정기 및 일회성 추가 원금을 적용합니다. 연 이자율은 연간 기간 수로 나눕니다. 남은 잔액이 계획 납부액보다 작으면 마지막 납부액을 줄입니다. 통화를 바꾸면 내부 계획 비율로 금액을 환산한 뒤 같은 시나리오를 다시 계산합니다.', riskNote: '이 결과는 금융기관 명세서가 아닌 추정치입니다. 통화 선택은 실시간 시장 환율이 아니라 내부 계획 비율을 사용합니다. 변동금리, 수수료, 보험, 세금, 일할 이자, 위약금 및 계약상 추가 상환 규칙은 포함하지 않습니다.', emptyMessage: '유효한 원금, 금리, 기간, 날짜를 입력하면 계획을 볼 수 있습니다.', invalidInputMessage: '계획을 보려면 입력값을 확인하세요', currencyOptions: { AUD: 'A$ AUD · 호주 달러', BRL: 'R$ BRL · 브라질 헤알', CAD: 'C$ CAD · 캐나다 달러', CHF: 'CHF · 스위스 프랑', CNY: '¥ CNY · 중국 위안', CZK: 'Kč CZK · 체코 코루나', DKK: 'kr DKK · 덴마크 크로네', EUR: '€ EUR · 유로', GBP: '£ GBP · 영국 파운드', IDR: 'Rp IDR · 인도네시아 루피아', INR: '₹ INR · 인도 루피', JPY: '¥ JPY · 일본 엔', KRW: '₩ KRW · 대한민국 원', MXN: 'MX$ MXN · 멕시코 페소', NOK: 'kr NOK · 노르웨이 크로네', PLN: 'zł PLN · 폴란드 즈워티', RUB: '₽ RUB · 러시아 루블', SEK: 'kr SEK · 스웨덴 크로나', TRY: '₺ TRY · 튀르키예 리라', USD: '$ USD · 미국 달러' }, currencySymbols: { AUD: 'A$', BRL: 'R$', CAD: 'C$', CHF: 'CHF', CNY: '¥', CZK: 'Kč', DKK: 'kr', EUR: '€', GBP: '£', IDR: 'Rp', INR: '₹', JPY: '¥', KRW: '₩', MXN: 'MX$', NOK: 'kr', PLN: 'zł', RUB: '₽', SEK: 'kr', TRY: '₺', USD: '$' }, frequencyOptions: { monthly: '매월', biweekly: '2주마다', weekly: '매주' },
};
const faq = [{ question: '추가 상환은 상환 일정을 어떻게 바꾸나요?', answer: '계산기는 정기 납부액을 그대로 두고 예정 납부 후 추가 원금을 적용합니다. 잔액이 더 빨리 0이 되고 총 이자가 줄어들 수 있습니다. 금융기관의 처리 방식은 계약에 따라 다르므로 계약서와 비교하세요.' }, { question: '통화를 바꾸면 어떻게 되나요?', answer: '금액을 내부 계획 비율로 새 통화에 환산한 다음 같은 시나리오를 다시 계산합니다. 실시간 환율이 아니므로 계획용 결과로 사용하세요.' }, { question: '통화 선택기가 하나뿐인 이유는 무엇인가요?', answer: '선택한 통화를 원금, 추가 상환, 정기 납부, 이자, 잔액, 연간 표 전체에 적용합니다. 하나의 단위를 사용하면 입력이 명확하고 통화가 섞이지 않습니다.' }, { question: '실제 금융기관 납부액을 계산하나요?', answer: '고정금리 상환 일정을 추정하지만 일수 계산, 비용, 보험, 세금, 금리 변경, 위약금, 조기 상환 조건은 알 수 없습니다. 공식 금액은 명세서와 계약서를 확인하세요.' }];
const howTo = [{ name: '통화 설정', text: '모든 금액과 결과에 사용할 하나의 통화를 선택합니다.' }, { name: '대출 입력', text: '원금, 명목 연이율, 남은 기간, 첫 납부일과 납부 주기를 입력합니다.' }, { name: '추가 상환 입력', text: '정기 추가 금액을 입력하고 필요하면 일회성 금액과 기간도 추가합니다.' }, { name: '비교 확인', text: '기존 잔액과 계획을 비교하고 이자, 기간, 완납일, 연간 일정을 확인합니다.' }];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'KRW' }, inLanguage: 'ko' };
const seo: ToolLocaleContent['seo'] = [{ type: 'title', text: '추가 상환이 바꾸는 것을 계획하세요', level: 2 }, { type: 'paragraph', html: '<p>상환 일정은 각 납부액을 이자와 원금으로 나눕니다. 추가 원금을 납부하고 정기 납부액을 유지하면 잔액을 더 일찍 0으로 만들 수 있습니다. 이 도구는 기존 잔액과 정기·일회성 추가 상환을 적용한 잔액을 비교합니다.</p>' }, { type: 'paragraph', html: '<p>결과는 고정금리 대출에 대한 계획용 추정치입니다. 원금, 명목 연이율, 납부 기간 수와 매 납부 후 변하는 잔액을 사용합니다. 계약의 일수 계산, 반올림, 비용 및 추가 상환 방식은 다를 수 있습니다.</p>' }, { type: 'title', text: '상환 계산 방식', level: 3 }, { type: 'paragraph', html: '<p>각 기간의 시작 잔액을 기준으로 이자를 계산합니다. 연 이자율을 연간 납부 횟수로 나누고, 정기 납부액을 이자와 원금으로 분리한 뒤 추가 원금을 잔액에서 차감합니다.</p>' }, { type: 'table', headers: ['항목', '계산', '의미'], rows: [['기간 이율', '연 이율 / 연간 기간 수', '각 기간에 적용하는 이율'], ['정기 납부액', '고정 납부 공식', '추가 원금 전 납부액'], ['기간 이자', '시작 잔액 x 기간 이율', '모델이 가정한 이자'], ['납부 후 잔액', '잔액 - 원금 - 추가분', '남은 채무']] }, { type: 'title', text: '추가 상환이 실제로 바꾸는 것', level: 3 }, { type: 'paragraph', html: '<p>이 모델에서 추가 상환은 원금을 직접 줄이므로 이후 이자는 더 작은 잔액에 적용됩니다. 절약되는 이자와 단축되는 기간을 함께 확인하면 비용 절감과 완납 시점을 나누어 이해할 수 있습니다.</p>' }, { type: 'paragraph', html: '<p>금융기관은 납부액을 낮추거나 기간을 유지하거나 공식 신청을 요구할 수 있습니다. 연간 한도, 최소 금액, 수수료를 확인하세요.</p>' }, { type: 'title', text: '통화를 섞지 않고 사용하기', level: 3 }, { type: 'paragraph', html: '<p>금액을 입력하기 전에 하나의 통화를 선택합니다. 원금, 추가 상환, 납부액, 이자, 잔액에 같은 단위를 사용하며, 통화를 바꾸면 내부에서 환산해 같은 시나리오를 계산합니다.</p>' }, { type: 'list', items: ['가계 예산이나 금융기관 명세서의 통화를 선택하세요.', '원금과 추가 상환을 선택한 통화로 입력하세요.', '통화 변경은 계획 단위 변경이지 계약 변경이 아닙니다.', '납부 주기와 조기 상환 조건을 확인하세요.', '연간 표에서 일회성 상환의 효과를 확인하세요.'] }, { type: 'title', text: '결과를 읽는 간단한 예', level: 3 }, { type: 'paragraph', html: '<p>250,000 EUR, 고정금리 3.5%, 25년의 경우 매 기간 150 EUR와 12번째 기간 5,000 EUR를 추가해도 모델의 기존 정기 납부액은 바뀌지 않습니다. 하지만 잔액과 이후 이자는 줄어듭니다.</p>' }, { type: 'paragraph', html: '<p>USD로 바꾸면 내부 계획 비율로 금액을 환산하고 같은 시나리오를 다시 계산합니다. 국제 예산에는 유용하지만 현재 시장 가치나 실시간 환율은 아닙니다.</p>' }, { type: 'title', text: '실행 전에 확인할 사항', level: 3 }, { type: 'list', items: ['추가 상환이 기간을 줄이는지 납부액을 줄이는지 물어보세요.', '한도, 최소 금액, 수수료를 확인하세요.', '금리가 명목·실효·고정·변동 중 무엇인지 확인하세요.', '계산 잔액을 최신 명세서와 비교하세요.', '국제 예산이라면 사용한 환율과 날짜를 기록하세요.'] }, { type: 'tip', title: '그래프는 비교이지 약속이 아닙니다', html: '<p>점선은 추가 상환이 없는 기존 고정 계획을, 구리색 선은 입력한 계획을 보여줍니다. 비용, 보험, 세금, 일할 이자, 환율 변동과 금융기관의 계약 규칙은 포함하지 않습니다.</p>' }, { type: 'title', text: '이 주택담보대출 계획의 한계', level: 3 }, { type: 'paragraph', html: '<p>고정금리와 정기 납부, 선택적 추가 원금이 있는 대출을 모델링합니다. 시나리오를 살펴보고 금융기관에 질문을 준비하는 데 유용하지만 상환 가능성, 세무·법률 조언, 환율 예측 또는 공식 명세서를 대신하지 않습니다.</p>' }];
export const content: ToolLocaleContent<MortgageExtraPaymentPlannerUI> = { slug, title, description, ui, faq, bibliography, howTo, schemas: [appSchema, faqSchema, howToSchema], seo };
