import { bibliography } from '../bibliography';
import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { MortgageExtraPaymentPlannerUI } from '../ui';

const slug = 'mortgage-amortization-extra-payment-planner';
const title = '含额外还款的房贷摊销计划';
const description = '为固定利率房贷加入定期或一次性额外还款，比较节省的利息，并用一种货币查看所有金额。';
const ui: MortgageExtraPaymentPlannerUI = {
  currencyLabel: '货币', currencyHelp: '只需选择一次。计划中的所有金额都会使用此货币。', principalLabel: '初始剩余本金', principalHelp: '计划开始时仍需偿还的金额', annualRateLabel: '年利率', annualRateHelp: '每个还款周期使用的名义固定利率', termLabel: '剩余期限（年）', termHelp: '未进行额外还款前的计划期限', frequencyLabel: '还款频率', recurringExtraLabel: '定期额外还款', recurringExtraHelp: '每个周期额外偿还的本金', oneOffExtraLabel: '一次性额外还款', oneOffExtraHelp: '在下方周期进行的一次本金还款', oneOffPeriodLabel: '一次性还款周期', oneOffPeriodHelp: '1表示第一个还款周期', startDateLabel: '首次还款日期', startDateHelp: '用于估算还清日期', extraSectionTitle: '额外还款计划', outputTitle: '余额变化', regularPaymentLabel: '额外还款前的常规还款', interestSavedLabel: '节省的利息', periodsSavedLabel: '缩短的周期', payoffDateLabel: '预计还清日期', totalInterestLabel: '按此计划支付的利息', totalExtraLabel: '额外偿还的本金', baselineLabel: '原始计划', planLabel: '加入额外还款后', balanceSceneLabel: '原始房贷余额与额外还款后的余额对比', balanceSceneHelp: '虚线表示原始计划，铜色线表示你的计划，绿色标记表示有额外本金的周期。', annualScheduleTitle: '年度还款计划', yearLabel: '年份', paymentLabel: '支付总额', interestLabel: '利息', principalPaidLabel: '计划本金', extraPaidLabel: '额外本金', endingBalanceLabel: '期末余额', formulaTitle: '模型与限制', formulaText: '计算器使用固定利率摊销模型。每个周期根据期初余额计算利息，将常规还款分配给利息和本金，然后应用定期及一次性额外本金。年利率除以每年的周期数。如果剩余余额小于计划还款额，最后一笔还款会相应减少。切换货币时，金额会用内部计划比例换算，并重新计算同一场景。', riskNote: '这是估算结果，不是贷款机构的账单。货币选择使用内部计划比例，而不是实时市场汇率。模型不包括浮动利率、费用、保险、税费、按日计息、罚金或合同中的提前还款规则。', emptyMessage: '输入有效的本金、利率、期限和日期即可查看计划。', invalidInputMessage: '请检查输入后查看计划', currencyOptions: { AUD: 'A$ AUD · 澳大利亚元', BRL: 'R$ BRL · 巴西雷亚尔', CAD: 'C$ CAD · 加拿大元', CHF: 'CHF · 瑞士法郎', CNY: '¥ CNY · 人民币', CZK: 'Kč CZK · 捷克克朗', DKK: 'kr DKK · 丹麦克朗', EUR: '€ EUR · 欧元', GBP: '£ GBP · 英镑', IDR: 'Rp IDR · 印度尼西亚卢比', INR: '₹ INR · 印度卢比', JPY: '¥ JPY · 日元', KRW: '₩ KRW · 韩元', MXN: 'MX$ MXN · 墨西哥比索', NOK: 'kr NOK · 挪威克朗', PLN: 'zł PLN · 波兰兹罗提', RUB: '₽ RUB · 俄罗斯卢布', SEK: 'kr SEK · 瑞典克朗', TRY: '₺ TRY · 土耳其里拉', USD: '$ USD · 美元' }, currencySymbols: { AUD: 'A$', BRL: 'R$', CAD: 'C$', CHF: 'CHF', CNY: '¥', CZK: 'Kč', DKK: 'kr', EUR: '€', GBP: '£', IDR: 'Rp', INR: '₹', JPY: '¥', KRW: '₩', MXN: 'MX$', NOK: 'kr', PLN: 'zł', RUB: '₽', SEK: 'kr', TRY: '₺', USD: '$' }, frequencyOptions: { monthly: '每月', biweekly: '每两周', weekly: '每周' },
};
const faq = [{ question: '额外还款会如何改变房贷计划？', answer: '计算器保持常规还款不变，并在每次计划还款后应用额外本金。余额可能更早归零，总利息也可能减少。贷款机构的处理方式可能不同，请将结果与合同核对。' }, { question: '切换货币后会发生什么？', answer: '金额会按内部计划比例换算为新货币，然后重新计算同一场景。这不是实时市场报价，应将结果用于规划。' }, { question: '为什么只有一个货币选择器？', answer: '所选货币会应用于本金、额外还款、常规还款、利息、余额和年度表格。统一单位让表单更清楚，也避免在一次计算中混用货币。' }, { question: '能计算贷款机构的真实还款额吗？', answer: '它只能估算固定利率摊销计划，不知道合同中的计息天数、费用、保险、税费、利率调整、罚金或提前还款处理方式。正式金额应以账单和合同为准。' }];
const howTo = [{ name: '设置货币', text: '选择用于所有金额和结果的一种货币。' }, { name: '填写贷款信息', text: '输入本金、名义年利率、剩余期限、首次还款日期和频率。' }, { name: '加入额外还款', text: '输入定期额外金额，并可添加一次性金额及其周期。' }, { name: '阅读对比', text: '比较原始余额与计划余额，并查看利息、周期、日期和年度计划。' }];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'FinanceApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'CNY' }, inLanguage: 'zh' };
const seo: ToolLocaleContent['seo'] = [{ type: 'title', text: '规划额外还款会带来的变化', level: 2 }, { type: 'paragraph', html: '<p>摊销计划会把每次还款分成利息和本金。支付额外本金并保持常规还款不变，可以让余额更早归零。本工具将原始余额路径与定期、一次性额外还款后的路径放在一起比较。</p>' }, { type: 'paragraph', html: '<p>结果是固定利率贷款的规划估算，使用本金、名义年利率、还款周期数量以及每次还款后变化的余额。合同可能采用不同的计息天数、四舍五入、费用或提前还款规则。</p>' }, { type: 'title', text: '摊销计算如何工作', level: 3 }, { type: 'paragraph', html: '<p>每个周期根据期初余额计算利息，将年利率除以每年的还款周期数，再把常规还款分配给利息和本金，最后扣除额外本金。</p>' }, { type: 'table', headers: ['项目', '计算', '含义'], rows: [['周期利率', '年利率 / 每年周期数', '每个周期使用的利率'], ['常规还款', '固定还款公式', '额外本金之前的还款'], ['周期利息', '期初余额 x 周期利率', '模型估算的利息'], ['还款后余额', '余额 - 本金 - 额外本金', '仍需偿还的金额']] }, { type: 'title', text: '额外还款真正改变什么', level: 3 }, { type: 'paragraph', html: '<p>在此模型中，额外还款会直接减少本金，因此之后的利息按更小的余额计算。请同时查看节省的利息和缩短的周期：前者表示减少的融资成本，后者表示更早还清的时间。</p>' }, { type: 'paragraph', html: '<p>贷款机构可能降低还款额、保持期限，或要求正式申请。还款前请确认年度上限、最低金额和可能的补偿费用。</p>' }, { type: 'title', text: '不混用货币进行计划', level: 3 }, { type: 'paragraph', html: '<p>输入金额前先选择一种货币。本金、额外还款、常规还款、利息和余额都使用同一单位。切换货币时金额在内部换算，场景结构保持不变。</p>' }, { type: 'list', items: ['选择家庭预算或贷款账单使用的货币。', '用所选货币输入本金和所有额外还款。', '把切换看作规划单位变化，而不是合同变化。', '确认允许的还款频率和提前还款规则。', '查看年度表格，了解一次性还款的影响。'] }, { type: 'title', text: '阅读结果的简单示例', level: 3 }, { type: 'paragraph', html: '<p>假设本金为250,000 EUR、固定年利率3.5%、期限25年，每周期额外支付150 EUR，并在第12周期支付5,000 EUR。在此模型中，原始常规还款额不变，但余额和之后的利息会下降。</p>' }, { type: 'paragraph', html: '<p>切换到USD后，工具用内部计划比例换算金额，并重新计算同一场景。这适合国际预算，但不是当前市场估值或实时汇率。</p>' }, { type: 'title', text: '行动前需要检查的事项', level: 3 }, { type: 'list', items: ['询问额外还款会缩短期限还是降低还款额。', '确认上限、最低金额和补偿费用。', '确认利率是名义、实际、固定还是浮动。', '将计算余额与最新账单比较。', '国际预算中记录使用的汇率和日期。'] }, { type: 'tip', title: '图表用于比较，不是承诺', html: '<p>虚线表示没有额外还款的原始固定计划，铜色线表示输入的计划。两者都不包含费用、保险、税费、按日计息、汇率变化或贷款机构的合同规则。</p>' }, { type: 'title', text: '本房贷计划的限制', level: 3 }, { type: 'paragraph', html: '<p>本工具模拟固定利率、定期还款和可选额外本金的贷款。它适合探索方案和准备问题，但不能评估还款能力，不能提供税务或法律建议，不能预测汇率，也不能替代贷款机构账单。</p>' }];
export const content: ToolLocaleContent<MortgageExtraPaymentPlannerUI> = { slug, title, description, ui, faq, bibliography, howTo, schemas: [appSchema, faqSchema, howToSchema], seo };
