/* eslint-disable max-lines, max-lines-per-function */
import type { WithContext, FAQPage, HowTo, SoftwareApplication } from "schema-dts";
import type { ToolLocaleContent } from "../../types";
import { bibliography } from "./bibliography";
import type { SubscriptionCostAnnualizerUI } from "./ui";

type LocaleKey = "en" | "de" | "es" | "fr" | "id" | "it" | "ja" | "ko" | "nl" | "pl" | "pt" | "ru" | "sv" | "tr" | "zh";

const englishUI: SubscriptionCostAnnualizerUI = {
  currencyLabel: "Currency",
  currencyHelp: "Use one currency for every row; no exchange rates are applied.",
  subscriptionLabel: "Subscriptions",
  nameLabel: "Name",
  namePlaceholder: "e.g. Video service",
  amountLabel: "Price per charge",
  frequencyLabel: "Billed",
  renewalLabel: "Renewal date",
  optionalLabel: "optional",
  addButton: "Add subscription",
  removeButton: "Remove subscription",
  resetButton: "Restore example",
  weeklyOption: "Weekly",
  monthlyOption: "Monthly",
  quarterlyOption: "Quarterly",
  annualOption: "Annually",
  monthlyTotalLabel: "Monthly equivalent",
  annualTotalLabel: "Yearly cost",
  dailyTotalLabel: "Average per day",
  yearlyViewTitle: "A year of recurring charges",
  yearlyViewText: "Each billing rhythm contributes to the same yearly picture.",
  scenarioTitle: "What could you save?",
  scenarioText: "Remove one row to see the annual cost left and the amount released.",
  keepLabel: "Cost if kept",
  saveLabel: "Annual saving",
  renewalTitle: "Next renewals",
  noRenewals: "Add renewal dates to see the next charges in calendar order.",
  renewalDateLabel: "Date",
  renewalAmountLabel: "Charge",
  emptyMessage: "Add at least one subscription with a name, a positive price and a supported billing frequency.",
  methodTitle: "How the calculation works",
  methodText: "Weekly prices are multiplied by 52, monthly prices by 12, quarterly prices by 4 and annual prices by 1. The annual total is divided by 12 for the monthly equivalent and by 365 for an average daily view.",
  limitationText: "This is a planning estimate using the prices and frequencies you enter. It does not include taxes, price changes, trials, refunds, exchange rates, proration or account data.",
  privacyNote: "Your entries stay in this browser. Nothing is sent to a server.",
  removeSubscriptionAria: "Remove this subscription",
  reorderHint: "Use your own list of recurring charges; rows can be edited directly.",
};

const packs: Record<
  LocaleKey,
  {
    title: string;
    description: string;
    ui?: Partial<SubscriptionCostAnnualizerUI>;
    intro: string;
    method: string;
    limit: string;
    faq: [string, string];
    steps: [string, string][];
  }
> = {
  en: {
    title: "Subscription Cost Annualizer",
    description: "Turn weekly, monthly, quarterly and annual subscriptions into a clear monthly and yearly spending picture.",
    intro: "Recurring charges are easy to underestimate when they arrive on different schedules. Enter the prices you already pay and this browser-only calculator puts them on one comparable monthly and yearly scale.",
    method: englishUI.methodText,
    limit: englishUI.limitationText,
    faq: ["How do I compare subscriptions with different billing periods?", "The calculator converts each charge to an annual amount, then divides the total by 12 for a monthly equivalent."],
    steps: [
      ["Add the charges you recognise", "Enter a name, price and billing frequency for each subscription you want to compare."],
      ["Choose one currency", "Keep every row in the same currency because the tool does not exchange or retrieve prices."],
      ["Read the yearly picture", "Use the monthly equivalent, yearly cost and per-subscription scenarios to decide what deserves another look."],
    ],
  },
  de: {
    title: "Abonnementkosten-Jahresrechner",
    description: "Vergleiche wöchentliche, monatliche, vierteljährliche und jährliche Abos auf einer gemeinsamen Kostenübersicht.",
    ui: {
      currencyLabel: "Währung",
      subscriptionLabel: "Abonnements",
      nameLabel: "Name",
      amountLabel: "Preis pro Abbuchung",
      frequencyLabel: "Abrechnung",
      renewalLabel: "Verlängerung",
      addButton: "Abo hinzufügen",
      resetButton: "Beispiel wiederherstellen",
      weeklyOption: "Wöchentlich",
      monthlyOption: "Monatlich",
      quarterlyOption: "Vierteljährlich",
      annualOption: "Jährlich",
      monthlyTotalLabel: "Monatlicher Gegenwert",
      annualTotalLabel: "Jahreskosten",
      dailyTotalLabel: "Durchschnitt pro Tag",
      scenarioTitle: "Was könntest du sparen?",
      renewalTitle: "Nächste Verlängerungen",
      privacyNote: "Deine Eingaben bleiben in diesem Browser.",
    },
    intro: "Wiederkehrende Abbuchungen sind schwer zu vergleichen, wenn sie in unterschiedlichen Abständen erfolgen. Trage deine eigenen Preise ein und erhalte eine gemeinsame Monats- und Jahresansicht.",
    method: "Wöchentliche Preise werden mit 52, monatliche mit 12, vierteljährliche mit 4 und jährliche mit 1 multipliziert.",
    limit: "Eine Planungsschätzung aus deinen Eingaben; Steuern, Preisänderungen, Erstattungen und Wechselkurse sind nicht enthalten.",
    faq: ["Wie vergleiche ich Abos mit unterschiedlichen Abrechnungszeiträumen?", "Jede Abbuchung wird auf ein Jahr hochgerechnet und die Summe durch 12 geteilt."],
    steps: [
      ["Abos eintragen", "Gib Name, Preis und Abrechnungsrhythmus ein."],
      ["Währung wählen", "Verwende dieselbe Währung für alle Zeilen."],
      ["Jahresbild lesen", "Vergleiche Jahreskosten und mögliche Einsparungen."],
    ],
  },
  es: {
    title: "Calculadora de coste anual de suscripciones",
    description: "Convierte suscripciones semanales, mensuales, trimestrales y anuales en un gasto mensual y anual comparable.",
    ui: {
      currencyLabel: "Moneda",
      subscriptionLabel: "Suscripciones",
      nameLabel: "Nombre",
      amountLabel: "Precio por cobro",
      frequencyLabel: "Cobro",
      renewalLabel: "Renovación",
      addButton: "Añadir suscripción",
      resetButton: "Restaurar ejemplo",
      weeklyOption: "Semanal",
      monthlyOption: "Mensual",
      quarterlyOption: "Trimestral",
      annualOption: "Anual",
      monthlyTotalLabel: "Equivalente mensual",
      annualTotalLabel: "Coste anual",
      dailyTotalLabel: "Media diaria",
      scenarioTitle: "¿Qué podrías ahorrar?",
      renewalTitle: "Próximas renovaciones",
      privacyNote: "Tus datos permanecen en este navegador.",
    },
    intro: "Los cobros recurrentes se subestiman cuando llegan con distintas frecuencias. Introduce los precios que ya pagas y compáralos en una escala mensual y anual común.",
    method: "Los precios semanales se multiplican por 52, los mensuales por 12, los trimestrales por 4 y los anuales por 1.",
    limit: "Es una estimación basada en tus datos: no incluye impuestos, cambios de precio, devoluciones, tipos de cambio ni datos de cuentas.",
    faq: ["¿Cómo comparo suscripciones con distintas frecuencias?", "Cada cobro se convierte a un coste anual y el total se divide entre 12 para obtener el equivalente mensual."],
    steps: [
      ["Añade tus cobros", "Escribe el nombre, el precio y la frecuencia de cada suscripción."],
      ["Elige una moneda", "Mantén una sola moneda porque la herramienta no hace conversiones."],
      ["Revisa los escenarios", "Consulta cuánto quedaría si eliminas cada fila."],
    ],
  },
  fr: {
    title: "Annualisateur du coût des abonnements",
    description: "Comparez les abonnements hebdomadaires, mensuels, trimestriels et annuels dans une vue mensuelle et annuelle.",
    ui: {
      currencyLabel: "Devise",
      subscriptionLabel: "Abonnements",
      nameLabel: "Nom",
      amountLabel: "Prix par prélèvement",
      frequencyLabel: "Facturation",
      renewalLabel: "Renouvellement",
      addButton: "Ajouter un abonnement",
      resetButton: "Restaurer l'exemple",
      weeklyOption: "Hebdomadaire",
      monthlyOption: "Mensuel",
      quarterlyOption: "Trimestriel",
      annualOption: "Annuel",
      monthlyTotalLabel: "Équivalent mensuel",
      annualTotalLabel: "Coût annuel",
      dailyTotalLabel: "Moyenne par jour",
      scenarioTitle: "Que pourriez-vous économiser ?",
      renewalTitle: "Prochains renouvellements",
      privacyNote: "Vos données restent dans ce navigateur.",
    },
    intro: "Les prélèvements récurrents sont difficiles à comparer quand ils suivent des rythmes différents. Saisissez vos prix réels pour obtenir une vue mensuelle et annuelle comparable.",
    method: "Les prix hebdomadaires sont multipliés par 52, les mensuels par 12, les trimestriels par 4 et les annuels par 1.",
    limit: "Une estimation fondée sur vos saisies, sans taxes, changements de prix, remboursements, change ou données de compte.",
    faq: ["Comment comparer des abonnements facturés à des rythmes différents ?", "Chaque prélèvement est annualisé, puis le total est divisé par 12 pour obtenir un équivalent mensuel."],
    steps: [
      ["Ajoutez vos prélèvements", "Saisissez le nom, le prix et la fréquence."],
      ["Choisissez une devise", "Gardez la même devise pour chaque ligne."],
      ["Lisez les scénarios", "Comparez le coût restant si vous retirez un abonnement."],
    ],
  },
  id: {
    title: "Penghitung biaya langganan tahunan",
    description: "Bandingkan langganan mingguan, bulanan, triwulanan, dan tahunan dalam gambaran biaya bulanan dan tahunan.",
    ui: {
      currencyLabel: "Mata uang",
      subscriptionLabel: "Langganan",
      nameLabel: "Nama",
      amountLabel: "Harga per tagihan",
      frequencyLabel: "Ditagih",
      renewalLabel: "Tanggal perpanjangan",
      addButton: "Tambah langganan",
      resetButton: "Pulihkan contoh",
      weeklyOption: "Mingguan",
      monthlyOption: "Bulanan",
      quarterlyOption: "Triwulanan",
      annualOption: "Tahunan",
      monthlyTotalLabel: "Setara per bulan",
      annualTotalLabel: "Biaya tahunan",
      dailyTotalLabel: "Rata-rata per hari",
      scenarioTitle: "Berapa yang bisa dihemat?",
      renewalTitle: "Perpanjangan berikutnya",
      privacyNote: "Data Anda tetap di browser ini.",
    },
    intro: "Tagihan berulang mudah diremehkan ketika jadwalnya berbeda. Masukkan harga yang Anda bayar dan bandingkan semuanya dalam skala bulanan dan tahunan.",
    method: "Harga mingguan dikalikan 52, bulanan 12, triwulanan 4, dan tahunan 1.",
    limit: "Ini adalah perkiraan dari data Anda; pajak, perubahan harga, pengembalian dana, dan kurs tidak disertakan.",
    faq: ["Bagaimana membandingkan langganan dengan periode tagihan berbeda?", "Setiap tagihan diubah menjadi biaya tahunan lalu totalnya dibagi 12."],
    steps: [
      ["Masukkan tagihan", "Isi nama, harga, dan frekuensi."],
      ["Pilih mata uang", "Gunakan satu mata uang untuk semua baris."],
      ["Baca skenario", "Lihat penghematan jika satu langganan dihapus."],
    ],
  },
  it: {
    title: "Calcolatore del costo annuale degli abbonamenti",
    description: "Confronta abbonamenti settimanali, mensili, trimestrali e annuali con una panoramica dei costi.",
    ui: {
      currencyLabel: "Valuta",
      subscriptionLabel: "Abbonamenti",
      nameLabel: "Nome",
      amountLabel: "Prezzo per addebito",
      frequencyLabel: "Frequenza",
      renewalLabel: "Rinnovo",
      addButton: "Aggiungi abbonamento",
      resetButton: "Ripristina esempio",
      weeklyOption: "Settimanale",
      monthlyOption: "Mensile",
      quarterlyOption: "Trimestrale",
      annualOption: "Annuale",
      monthlyTotalLabel: "Equivalente mensile",
      annualTotalLabel: "Costo annuale",
      dailyTotalLabel: "Media giornaliera",
      scenarioTitle: "Quanto potresti risparmiare?",
      renewalTitle: "Prossimi rinnovi",
      privacyNote: "I tuoi dati restano nel browser.",
    },
    intro: "Gli addebiti ricorrenti sono difficili da confrontare quando hanno frequenze diverse. Inserisci i prezzi che paghi e rendili comparabili.",
    method: "I prezzi settimanali vengono moltiplicati per 52, quelli mensili per 12, trimestrali per 4 e annuali per 1.",
    limit: "Stima basata sui dati inseriti, senza tasse, variazioni di prezzo, rimborsi o cambi.",
    faq: ["Come confronto abbonamenti con frequenze diverse?", "Ogni addebito viene annualizzato e il totale viene diviso per 12."],
    steps: [
      ["Inserisci gli addebiti", "Indica nome, prezzo e frequenza."],
      ["Scegli una valuta", "Usa la stessa valuta in ogni riga."],
      ["Controlla gli scenari", "Vedi il costo residuo rimuovendo una voce."],
    ],
  },
  ja: {
    title: "サブスクリプション年間コスト計算機",
    description: "週次、月次、四半期、年次のサブスクリプションを月額と年額で比較します。",
    ui: {
      currencyLabel: "通貨",
      subscriptionLabel: "サブスクリプション",
      nameLabel: "名前",
      amountLabel: "1回の料金",
      frequencyLabel: "請求頻度",
      renewalLabel: "更新日",
      addButton: "追加",
      resetButton: "例を復元",
      weeklyOption: "毎週",
      monthlyOption: "毎月",
      quarterlyOption: "四半期ごと",
      annualOption: "毎年",
      monthlyTotalLabel: "月額換算",
      annualTotalLabel: "年間コスト",
      dailyTotalLabel: "1日平均",
      scenarioTitle: "いくら節約できますか？",
      renewalTitle: "次回の更新",
      privacyNote: "入力内容はこのブラウザ内に保存されます。",
    },
    intro: "請求頻度が違うと、定期支出は実際より小さく見えます。支払っている料金を入力して、月額と年額で比較しましょう。",
    method: "週額は52倍、月額は12倍、四半期額は4倍、年額は1倍して年間費用にします。",
    limit: "入力値に基づく見積もりです。税金、価格変更、返金、為替、アカウント情報は含みません。",
    faq: ["請求期間の異なるサービスをどう比較しますか？", "各料金を年間費用に換算し、合計を12で割って月額換算を出します。"],
    steps: [
      ["支出を追加", "名前、料金、請求頻度を入力します。"],
      ["通貨を選択", "すべての行で同じ通貨を使います。"],
      ["結果を確認", "各行を削除した場合の節約額を比較します。"],
    ],
  },
  ko: {
    title: "구독 비용 연간 환산기",
    description: "주간, 월간, 분기별, 연간 구독료를 월간 및 연간 비용으로 비교합니다.",
    ui: {
      currencyLabel: "통화",
      subscriptionLabel: "구독",
      nameLabel: "이름",
      amountLabel: "청구 금액",
      frequencyLabel: "청구 주기",
      renewalLabel: "갱신일",
      addButton: "구독 추가",
      resetButton: "예시 복원",
      weeklyOption: "매주",
      monthlyOption: "매월",
      quarterlyOption: "분기별",
      annualOption: "매년",
      monthlyTotalLabel: "월 환산액",
      annualTotalLabel: "연간 비용",
      dailyTotalLabel: "일평균",
      scenarioTitle: "얼마나 절약할 수 있나요?",
      renewalTitle: "다음 갱신",
      privacyNote: "입력값은 이 브라우저에만 저장됩니다.",
    },
    intro: "청구 주기가 다르면 반복 지출을 과소평가하기 쉽습니다. 실제 요금을 입력해 월간 및 연간 기준으로 비교하세요.",
    method: "주간 요금은 52배, 월간은 12배, 분기별은 4배, 연간은 1배하여 연간 비용을 계산합니다.",
    limit: "입력한 값으로 계산한 예상치이며 세금, 가격 변경, 환불, 환율과 계정 데이터는 포함하지 않습니다.",
    faq: ["청구 주기가 다른 구독을 어떻게 비교하나요?", "각 요금을 연간 비용으로 환산한 뒤 합계를 12로 나눕니다."],
    steps: [
      ["요금 추가", "이름, 금액, 청구 주기를 입력합니다."],
      ["통화 선택", "모든 행에 같은 통화를 사용합니다."],
      ["시나리오 확인", "한 항목을 없앴을 때의 절약액을 봅니다."],
    ],
  },
  nl: {
    title: "Jaarlijkse abonnementskosten calculator",
    description: "Zet wekelijkse, maandelijkse, kwartaal- en jaarabonnementen om naar een vergelijkbaar kostenoverzicht.",
    ui: {
      currencyLabel: "Valuta",
      subscriptionLabel: "Abonnementen",
      nameLabel: "Naam",
      amountLabel: "Prijs per afschrijving",
      frequencyLabel: "Facturering",
      renewalLabel: "Verlengingsdatum",
      addButton: "Abonnement toevoegen",
      resetButton: "Voorbeeld herstellen",
      weeklyOption: "Wekelijks",
      monthlyOption: "Maandelijks",
      quarterlyOption: "Per kwartaal",
      annualOption: "Jaarlijks",
      monthlyTotalLabel: "Maandelijks equivalent",
      annualTotalLabel: "Jaarlijkse kosten",
      dailyTotalLabel: "Gemiddeld per dag",
      scenarioTitle: "Wat kun je besparen?",
      renewalTitle: "Volgende verlengingen",
      privacyNote: "Je gegevens blijven in deze browser.",
    },
    intro: "Terugkerende afschrijvingen lijken kleiner wanneer ze op verschillende momenten komen. Vul je eigen prijzen in en vergelijk ze per maand en per jaar.",
    method: "Wekelijkse prijzen worden met 52 vermenigvuldigd, maandelijkse met 12, kwartaalprijzen met 4 en jaarprijzen met 1.",
    limit: "Een schatting op basis van je invoer; belastingen, prijswijzigingen, terugbetalingen en wisselkoersen zijn uitgesloten.",
    faq: ["Hoe vergelijk ik abonnementen met verschillende factuurperiodes?", "Elke afschrijving wordt omgerekend naar een jaarbedrag en het totaal wordt door 12 gedeeld."],
    steps: [
      ["Voeg kosten toe", "Vul naam, prijs en frequentie in."],
      ["Kies een valuta", "Gebruik dezelfde valuta voor alle regels."],
      ["Bekijk scenario’s", "Zie wat er overblijft als je een abonnement verwijdert."],
    ],
  },
  pl: {
    title: "Roczny koszt subskrypcji",
    description: "Porównuj subskrypcje tygodniowe, miesięczne, kwartalne i roczne w jednej skali kosztów.",
    ui: {
      currencyLabel: "Waluta",
      subscriptionLabel: "Subskrypcje",
      nameLabel: "Nazwa",
      amountLabel: "Cena za pobranie",
      frequencyLabel: "Rozliczenie",
      renewalLabel: "Data odnowienia",
      addButton: "Dodaj subskrypcję",
      resetButton: "Przywróć przykład",
      weeklyOption: "Tygodniowo",
      monthlyOption: "Miesięcznie",
      quarterlyOption: "Kwartalnie",
      annualOption: "Rocznie",
      monthlyTotalLabel: "Miesięczny odpowiednik",
      annualTotalLabel: "Koszt roczny",
      dailyTotalLabel: "Średnio dziennie",
      scenarioTitle: "Ile możesz zaoszczędzić?",
      renewalTitle: "Najbliższe odnowienia",
      privacyNote: "Twoje dane pozostają w tej przeglądarce.",
    },
    intro: "Opłaty cykliczne łatwo zaniżyć, gdy pojawiają się w różnych odstępach. Wpisz własne ceny i porównaj je miesięcznie oraz rocznie.",
    method: "Ceny tygodniowe mnożymy przez 52, miesięczne przez 12, kwartalne przez 4, a roczne przez 1.",
    limit: "To szacunek na podstawie danych wejściowych; nie obejmuje podatków, zmian cen, zwrotów ani kursów walut.",
    faq: ["Jak porównać subskrypcje o różnych okresach rozliczeniowych?", "Każdą opłatę przeliczamy na rok, a sumę dzielimy przez 12."],
    steps: [
      ["Dodaj opłaty", "Wpisz nazwę, cenę i częstotliwość."],
      ["Wybierz walutę", "Użyj jednej waluty we wszystkich wierszach."],
      ["Sprawdź scenariusze", "Zobacz oszczędność po usunięciu pozycji."],
    ],
  },
  pt: {
    title: "Calculadora do custo anual de subscrições",
    description: "Compare subscrições semanais, mensais, trimestrais e anuais numa visão clara de custos.",
    ui: {
      currencyLabel: "Moeda",
      subscriptionLabel: "Subscrições",
      nameLabel: "Nome",
      amountLabel: "Preço por cobrança",
      frequencyLabel: "Cobrança",
      renewalLabel: "Data de renovação",
      addButton: "Adicionar subscrição",
      resetButton: "Restaurar exemplo",
      weeklyOption: "Semanal",
      monthlyOption: "Mensal",
      quarterlyOption: "Trimestral",
      annualOption: "Anual",
      monthlyTotalLabel: "Equivalente mensal",
      annualTotalLabel: "Custo anual",
      dailyTotalLabel: "Média diária",
      scenarioTitle: "Quanto pode poupar?",
      renewalTitle: "Próximas renovações",
      privacyNote: "Os seus dados ficam neste navegador.",
    },
    intro: "As cobranças recorrentes parecem menores quando têm frequências diferentes. Introduza os preços que já paga e compare-os por mês e por ano.",
    method: "Os preços semanais são multiplicados por 52, os mensais por 12, os trimestrais por 4 e os anuais por 1.",
    limit: "É uma estimativa baseada nos seus dados; não inclui impostos, alterações de preço, reembolsos ou câmbio.",
    faq: ["Como comparar subscrições com períodos de cobrança diferentes?", "Cada cobrança é convertida num custo anual e o total é dividido por 12."],
    steps: [
      ["Adicione cobranças", "Indique o nome, o preço e a frequência."],
      ["Escolha uma moeda", "Use a mesma moeda em todas as linhas."],
      ["Leia os cenários", "Veja a poupança possível ao retirar uma subscrição."],
    ],
  },
  ru: {
    title: "Калькулятор годовой стоимости подписок",
    description: "Сравните еженедельные, ежемесячные, квартальные и годовые подписки в единой шкале расходов.",
    ui: {
      currencyLabel: "Валюта",
      currencyHelp: "Используйте одну валюту; обменные курсы не применяются.",
      subscriptionLabel: "Подписки",
      nameLabel: "Название",
      namePlaceholder: "Например, видеосервис",
      amountLabel: "Сумма списания",
      frequencyLabel: "Период оплаты",
      renewalLabel: "Дата продления",
      optionalLabel: "необязательно",
      addButton: "Добавить подписку",
      removeButton: "Удалить подписку",
      resetButton: "Восстановить пример",
      weeklyOption: "Еженедельно",
      monthlyOption: "Ежемесячно",
      quarterlyOption: "Ежеквартально",
      annualOption: "Ежегодно",
      monthlyTotalLabel: "Эквивалент в месяц",
      annualTotalLabel: "Расход за год",
      dailyTotalLabel: "В среднем в день",
      yearlyViewTitle: "Повторяющиеся расходы за год",
      yearlyViewText: "Каждый период оплаты складывается в общую картину.",
      scenarioTitle: "Сколько можно сэкономить?",
      scenarioText: "Удалите строку, чтобы увидеть оставшуюся стоимость и высвободившуюся сумму.",
      keepLabel: "Если оставить",
      saveLabel: "Экономия за год",
      renewalTitle: "Ближайшие продления",
      noRenewals: "Добавьте даты, чтобы увидеть ближайшие списания.",
      renewalDateLabel: "Дата",
      renewalAmountLabel: "Списание",
      emptyMessage: "Добавьте подписку с названием, положительной суммой и поддерживаемым периодом.",
      methodTitle: "Как работает расчёт",
      methodText: "Еженедельная сумма умножается на 52, ежемесячная на 12, квартальная на 4, годовая на 1.",
      limitationText: "Это оценка по введённым данным без налогов, изменения цен, возвратов и валютных курсов.",
      privacyNote: "Ваши данные остаются в этом браузере.",
      removeSubscriptionAria: "Удалить эту подписку",
      reorderHint: "Редактируйте строки напрямую, используя собственные регулярные расходы.",
    },
    intro: "Регулярные списания легко недооценить, когда они происходят с разной частотой. Введите свои цены и сравните их за месяц и за год.",
    method: "Еженедельная сумма умножается на 52, ежемесячная на 12, квартальная на 4, годовая на 1.",
    limit: "Это оценка по введённым данным без налогов, изменения цен, возвратов и валютных курсов.",
    faq: ["Как сравнить подписки с разными периодами оплаты?", "Каждое списание пересчитывается на год, затем сумма делится на 12."],
    steps: [
      ["Добавьте списания", "Укажите название, сумму и период оплаты."],
      ["Выберите валюту", "Используйте одну валюту во всех строках."],
      ["Проверьте сценарии", "Посмотрите экономию при удалении строки."],
    ],
  },
  sv: {
    title: "Årskostnad för prenumerationer",
    description: "Jämför vecko-, månads-, kvartals- och årsprenumerationer i en gemensam kostnadsbild.",
    ui: {
      currencyLabel: "Valuta",
      subscriptionLabel: "Prenumerationer",
      nameLabel: "Namn",
      amountLabel: "Pris per debitering",
      frequencyLabel: "Debiteras",
      renewalLabel: "Förnyelsedatum",
      addButton: "Lägg till prenumeration",
      resetButton: "Återställ exempel",
      weeklyOption: "Varje vecka",
      monthlyOption: "Varje månad",
      quarterlyOption: "Varje kvartal",
      annualOption: "Årligen",
      monthlyTotalLabel: "Månadsekvivalent",
      annualTotalLabel: "Årskostnad",
      dailyTotalLabel: "Genomsnitt per dag",
      scenarioTitle: "Vad kan du spara?",
      renewalTitle: "Nästa förnyelser",
      privacyNote: "Dina uppgifter stannar i webbläsaren.",
    },
    intro: "Återkommande debiteringar är lätta att underskatta när de kommer med olika intervall. Skriv in priserna du betalar och jämför dem per månad och år.",
    method: "Veckopriser multipliceras med 52, månadspriser med 12, kvartalspriser med 4 och årspriser med 1.",
    limit: "En uppskattning från dina uppgifter utan skatter, prisändringar, återbetalningar eller valutakurser.",
    faq: ["Hur jämför jag prenumerationer med olika betalningsperioder?", "Varje debitering räknas om till ett år och totalsumman delas med 12."],
    steps: [
      ["Lägg till debiteringar", "Skriv namn, pris och frekvens."],
      ["Välj valuta", "Använd samma valuta i alla rader."],
      ["Läs scenarierna", "Se besparingen om du tar bort en post."],
    ],
  },
  tr: {
    title: "Abonelik yıllık maliyet hesaplayıcı",
    description: "Haftalık, aylık, üç aylık ve yıllık abonelikleri ortak bir maliyet görünümünde karşılaştırın.",
    ui: {
      currencyLabel: "Para birimi",
      subscriptionLabel: "Abonelikler",
      nameLabel: "Ad",
      amountLabel: "Ödeme başına fiyat",
      frequencyLabel: "Faturalama",
      renewalLabel: "Yenileme tarihi",
      addButton: "Abonelik ekle",
      resetButton: "Örneği geri yükle",
      weeklyOption: "Haftalık",
      monthlyOption: "Aylık",
      quarterlyOption: "Üç aylık",
      annualOption: "Yıllık",
      monthlyTotalLabel: "Aylık karşılık",
      annualTotalLabel: "Yıllık maliyet",
      dailyTotalLabel: "Günlük ortalama",
      scenarioTitle: "Ne kadar tasarruf edebilirsiniz?",
      renewalTitle: "Sonraki yenilemeler",
      privacyNote: "Verileriniz bu tarayıcıda kalır.",
    },
    intro: "Farklı aralıklarla gelen düzenli ödemeleri olduğundan küçük görmek kolaydır. Ödediğiniz fiyatları girin ve aylık ve yıllık olarak karşılaştırın.",
    method: "Haftalık fiyatlar 52, aylık fiyatlar 12, üç aylık fiyatlar 4 ve yıllık fiyatlar 1 ile çarpılır.",
    limit: "Girdiğiniz değerlere dayalı bir tahmindir; vergiler, fiyat değişiklikleri, iadeler ve döviz kurları dahil değildir.",
    faq: ["Farklı faturalama dönemlerini nasıl karşılaştırırım?", "Her ödeme yıllık maliyete çevrilir ve toplam 12’ye bölünür."],
    steps: [
      ["Ödemeleri ekleyin", "Adı, fiyatı ve sıklığı girin."],
      ["Para birimi seçin", "Tüm satırlarda aynı para birimini kullanın."],
      ["Senaryoları inceleyin", "Bir aboneliği kaldırınca kalan maliyeti görün."],
    ],
  },
  zh: {
    title: "订阅费用年度计算器",
    description: "将每周、每月、每季度和每年的订阅费用换算成清晰可比的月度和年度支出。",
    ui: {
      currencyLabel: "货币",
      currencyHelp: "所有项目使用同一种货币，不进行汇率换算。",
      subscriptionLabel: "订阅",
      nameLabel: "名称",
      namePlaceholder: "例如：视频服务",
      amountLabel: "每次扣款",
      frequencyLabel: "计费周期",
      renewalLabel: "续订日期",
      optionalLabel: "可选",
      addButton: "添加订阅",
      removeButton: "删除订阅",
      resetButton: "恢复示例",
      weeklyOption: "每周",
      monthlyOption: "每月",
      quarterlyOption: "每季度",
      annualOption: "每年",
      monthlyTotalLabel: "月度等值",
      annualTotalLabel: "年度费用",
      dailyTotalLabel: "日均",
      yearlyViewTitle: "一年的定期扣款",
      yearlyViewText: "不同的计费周期汇总为同一年度视图。",
      scenarioTitle: "可以节省多少？",
      scenarioText: "删除一行，查看剩余年度费用和释放的金额。",
      keepLabel: "保留后的费用",
      saveLabel: "年度节省",
      renewalTitle: "下一次续订",
      noRenewals: "添加日期即可按日历顺序查看扣款。",
      renewalDateLabel: "日期",
      renewalAmountLabel: "扣款",
      emptyMessage: "请添加名称、正数价格和支持的计费周期。",
      methodTitle: "计算方式",
      methodText: "每周价格乘以52，每月乘以12，每季度乘以4，每年乘以1，得到年度费用。",
      limitationText: "这是根据输入数据的估算，不包含税费、价格变化、退款或汇率。",
      privacyNote: "您的数据只保留在此浏览器中。",
      removeSubscriptionAria: "删除此订阅",
      reorderHint: "直接编辑您自己的定期扣款列表。",
    },
    intro: "当定期扣款的周期不同时，很容易低估实际支出。输入您正在支付的价格，即可按月和按年比较。",
    method: "每周价格乘以52，每月乘以12，每季度乘以4，每年乘以1，得到年度费用。",
    limit: "这是根据输入数据的估算，不包含税费、价格变化、退款或汇率。",
    faq: ["如何比较不同计费周期的订阅？", "将每笔扣款换算为年度费用，再将总额除以12。"],
    steps: [
      ["添加扣款", "输入名称、价格和计费周期。"],
      ["选择货币", "所有行使用同一种货币。"],
      ["查看方案", "比较移除某项订阅后的节省金额。"],
    ],
  },
};

const localeExtras: Partial<Record<LocaleKey, Partial<SubscriptionCostAnnualizerUI>>> = {
  it: {
    limitationText: "È una stima basata sui dati inseriti: non include tasse, variazioni di prezzo o rimborsi.",
  },
  ja: {
    currencyHelp: "すべての項目で同じ通貨を使います。為替レートは適用されません。",
    namePlaceholder: "例：動画サービス",
    optionalLabel: "任意",
    removeButton: "削除",
    yearlyViewTitle: "一年間の定期支出",
    yearlyViewText: "異なる請求周期を一つの年間表示にまとめます。",
    scenarioText: "行を削除すると、残りの年間費用と節約額が表示されます。",
    keepLabel: "継続した場合",
    saveLabel: "年間の節約額",
    noRenewals: "日付を追加すると、次回の請求を確認できます。",
    renewalDateLabel: "日付",
    renewalAmountLabel: "請求額",
    emptyMessage: "名前、正の価格、対応する請求周期を入力してください。",
    methodTitle: "計算方法",
    methodText: "週額は52倍、月額は12倍、四半期額は4倍、年額は1倍にして年間費用を求めます。",
    limitationText: "入力値に基づく目安です。税金、価格変更、返金、為替、アカウント情報は含みません。",
    removeSubscriptionAria: "このサブスクリプションを削除",
    reorderHint: "自分の定期支出を直接編集できます。",
  },
  ko: {
    currencyHelp: "모든 항목에 같은 통화를 사용하며 환율은 적용하지 않습니다.",
    namePlaceholder: "예: 동영상 서비스",
    optionalLabel: "선택 사항",
    removeButton: "삭제",
    yearlyViewTitle: "1년간의 반복 지출",
    yearlyViewText: "서로 다른 청구 주기를 하나의 연간 화면으로 합칩니다.",
    scenarioText: "행을 삭제하면 남은 연간 비용과 절약액을 확인할 수 있습니다.",
    keepLabel: "유지할 때 비용",
    saveLabel: "연간 절약액",
    noRenewals: "날짜를 추가하면 다음 결제일을 볼 수 있습니다.",
    renewalDateLabel: "날짜",
    renewalAmountLabel: "청구액",
    emptyMessage: "이름, 양수 금액과 지원되는 청구 주기를 입력하세요.",
    methodTitle: "계산 방식",
    methodText: "주간 금액은 52배, 월간은 12배, 분기별은 4배, 연간은 1배하여 연간 비용을 계산합니다.",
    limitationText: "입력값에 따른 예상치이며 세금, 가격 변경, 환불, 환율과 계정 데이터는 포함하지 않습니다.",
    removeSubscriptionAria: "이 구독 삭제",
    reorderHint: "반복 지출 목록을 직접 편집할 수 있습니다.",
  },
  ru: packs.ru.ui ?? {},
  zh: packs.zh.ui ?? {},
};

export function createSubscriptionContent(locale: LocaleKey): ToolLocaleContent<SubscriptionCostAnnualizerUI> {
  const pack = packs[locale];
  const ui = {
    ...englishUI,
    ...pack.ui,
    ...localeExtras[locale],
  } as SubscriptionCostAnnualizerUI;
  const externalQuestions: Partial<Record<LocaleKey, string>> = {
    de: "Verwendet der Rechner externe Kontodaten?",
    en: "Does the calculator use bank or account data?",
    es: "¿Usa datos externos de cuentas?",
    fr: "Le calculateur utilise-t-il des données externes ?",
    it: "Il calcolatore usa dati esterni del conto?",
    ja: "外部の口座データを使いますか？",
    ko: "외부 계정 데이터를 사용하나요?",
    ru: "Использует ли калькулятор внешние данные счёта?",
    zh: "计算器会使用外部账户数据吗?",
  };
  const externalQuestion = externalQuestions[locale] ?? "Does this calculator use external account data?";
  const faq = [
    { question: pack.faq[0], answer: pack.faq[1] },
    { question: externalQuestion, answer: ui.privacyNote },
  ];
  const howTo = pack.steps.map(([name, text]) => ({ name, text }));
  const faqSchema: WithContext<FAQPage> = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faq.map((item) => ({
      "@type": "Question",
      name: item.question,
      acceptedAnswer: { "@type": "Answer", text: item.answer },
    })),
  };
  const howToSchema: WithContext<HowTo> = {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name: pack.title,
    description: pack.description,
    step: howTo.map((step, index) => ({
      "@type": "HowToStep",
      position: index + 1,
      name: step.name,
      text: step.text,
    })),
  };
  const appSchema: WithContext<SoftwareApplication> = {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: pack.title,
    description: pack.description,
    applicationCategory: "FinanceApplication",
    operatingSystem: "All",
    offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
    inLanguage: locale,
  };
  const slugs: Record<LocaleKey, string> = {
    en: "subscription-cost-annualizer",
    de: "abonnementkosten-jahresrechner",
    es: "calculadora-coste-suscripciones",
    fr: "annualisateur-cout-abonnements",
    id: "penghitung-biaya-langganan",
    it: "calcolatore-costo-abbonamenti",
    ja: "subscription-cost-annualizer",
    ko: "subscription-cost-annualizer",
    nl: "jaarlijkse-abonnementskosten",
    pl: "roczny-koszt-subskrypcji",
    pt: "custo-anual-subscricoes",
    ru: "godovaya-stoimost-podpisok",
    sv: "arskostnad-prenumerationer",
    tr: "abonelik-yillik-maliyet",
    zh: "subscription-cost-annualizer",
  };
  return {
    slug: slugs[locale],
    title: pack.title,
    description: pack.description,
    ui,
    faq,
    bibliography,
    howTo,
    schemas: [faqSchema, howToSchema, appSchema],
    seo: [
      { type: "title", text: pack.title, level: 2 },
      { type: "paragraph", html: `<p>${pack.intro}</p>` },
      { type: "title", text: ui.yearlyViewTitle, level: 3 },
      { type: "paragraph", html: `<p>${pack.method}</p>` },
      {
        type: "list",
        items: [ui.monthlyTotalLabel, ui.annualTotalLabel, ui.scenarioText],
      },
      { type: "title", text: ui.methodTitle, level: 3 },
      { type: "paragraph", html: `<p>${pack.limit}</p>` },
    ],
  };
}
