export const CURRENCY_SYMBOLS: Record<string, string> = {
  EUR: '\u20ac',
  USD: '$',
  GBP: '\u00a3',
  JPY: '\u00a5',
  KRW: '\u20a9',
  CNY: '\u00a5',
  BRL: 'R$',
  MXN: '$',
  PLN: 'z\u0142',
  IDR: 'Rp',
  TRY: '\u20ba',
  RUB: '\u20bd',
  SEK: 'kr',
  AUD: 'A$',
  CAD: 'C$',
};

export const MARKET_CURRENCY_MAP: Record<string, string> = {
  es: 'EUR',
  eu: 'EUR',
  us: 'USD',
  uk: 'GBP',
  jp: 'JPY',
  kr: 'KRW',
  cn: 'CNY',
  br: 'BRL',
  mx: 'MXN',
  pl: 'PLN',
  id: 'IDR',
  tr: 'TRY',
  ru: 'RUB',
  se: 'SEK',
  au: 'AUD',
  ca: 'CAD',
};
