export { compoundInterest } from './tool/compoundInterest/entry';
export type { CompoundInterestLocaleContent } from './tool/compoundInterest/entry';
export { financialFreedom } from './tool/financialFreedom/entry';
export type { FinancialFreedomLocaleContent } from './tool/financialFreedom/entry';
export { profitability } from './tool/profitability/entry';
export type { ProfitabilityLocaleContent } from './tool/profitability/entry';
export { courtFeeCalculator } from './tool/courtFeeCalculator/entry';
export type { CourtFeeCalculatorLocaleContent } from './tool/courtFeeCalculator/entry';
export { debtSnowball } from './tool/debtSnowball/entry';
export type { DebtSnowballLocaleContent } from './tool/debtSnowball/entry';
export { fireCalculator } from './tool/fireCalculator/entry';
export type { FIRECalculatorLocaleContent } from './tool/fireCalculator/entry';
export { ibanBicSwift } from './tool/ibanBicSwiftConverter/entry';
export type { IBANBICSwiftLocaleContent } from './tool/ibanBicSwiftConverter/entry';
export { inflation } from './tool/inflation/entry';
export type { InflationLocaleContent } from './tool/inflation/entry';
export { lateInterest } from './tool/lateInterest/entry';
export type { LateInterestLocaleContent } from './tool/lateInterest/entry';
export { legalInterestRate } from './tool/legalInterestRate/entry';
export type { LegalInterestRateLocaleContent } from './tool/legalInterestRate/entry';
export { lotteryOptimizer } from './tool/lotteryOptimizer/entry';
export type { LotteryOptimizerLocaleContent } from './tool/lotteryOptimizer/entry';
export { mortgage } from './tool/mortgage/entry';
export type { MortgageLocaleContent } from './tool/mortgage/entry';
export { percentageCalculator } from './tool/percentageCalculator/entry';
export type { PercentageCalculatorLocaleContent } from './tool/percentageCalculator/entry';
export { rentIncrease } from './tool/rentIncreaseCalculator/entry';
export type { RentIncreaseLocaleContent } from './tool/rentIncreaseCalculator/entry';
export { revolvingCardCalculator } from './tool/revolvingCardCalculator/entry';
export type { RevolvingCardCalculatorLocaleContent } from './tool/revolvingCardCalculator/entry';
export { pesetaValue } from './tool/pesetaValue/entry';
export type { PesetaValueLocaleContent } from './tool/pesetaValue/entry';
export { salaryEmployerCost } from './tool/salaryEmployerCost/entry';
export type { SalaryEmployerCostLocaleContent } from './tool/salaryEmployerCost/entry';
export { dividendYield } from './tool/dividendYield/entry';
export type { DividendYieldLocaleContent } from './tool/dividendYield/entry';
export { inflationPurchasingPower } from './tool/inflationPurchasingPower/entry';
export type { InflationPurchasingPowerLocaleContent } from './tool/inflationPurchasingPower/entry';
export { subscriptionCostAnnualizer } from './tool/subscriptionCostAnnualizer/entry';
export type { SubscriptionCostAnnualizerLocaleContent } from './tool/subscriptionCostAnnualizer/entry';
export { loanToIncomeRatio } from './tool/loanToIncomeRatio/entry';
export type { LoanToIncomeRatioLocaleContent } from './tool/loanToIncomeRatio/entry';
export { financeCategory } from './category';
import { compoundInterest } from './tool/compoundInterest/entry';
import { financialFreedom } from './tool/financialFreedom/entry';
import { profitability } from './tool/profitability/entry';
import { courtFeeCalculator } from './tool/courtFeeCalculator/entry';
import { debtSnowball } from './tool/debtSnowball/entry';
import { fireCalculator } from './tool/fireCalculator/entry';
import { ibanBicSwift } from './tool/ibanBicSwiftConverter/entry';
import { inflation } from './tool/inflation/entry';
import { lateInterest } from './tool/lateInterest/entry';
import { legalInterestRate } from './tool/legalInterestRate/entry';
import { lotteryOptimizer } from './tool/lotteryOptimizer/entry';
import { mortgage } from './tool/mortgage/entry';
import { percentageCalculator } from './tool/percentageCalculator/entry';
import { rentIncrease } from './tool/rentIncreaseCalculator/entry';
import { revolvingCardCalculator } from './tool/revolvingCardCalculator/entry';
import { pesetaValue } from './tool/pesetaValue/entry';
import { salaryEmployerCost } from './tool/salaryEmployerCost/entry';
import { dividendYield } from './tool/dividendYield/entry';
import { mortgageExtraPaymentPlanner } from './tool/mortgageExtraPaymentPlanner/entry';
import { inflationPurchasingPower } from './tool/inflationPurchasingPower/entry';
import { subscriptionCostAnnualizer } from './tool/subscriptionCostAnnualizer/entry';
import { loanToIncomeRatio } from './tool/loanToIncomeRatio/entry';
export const ALL_ENTRIES = [compoundInterest, financialFreedom, profitability, courtFeeCalculator, debtSnowball, fireCalculator, ibanBicSwift, inflation, lateInterest, legalInterestRate, lotteryOptimizer, mortgage, percentageCalculator, rentIncrease, revolvingCardCalculator, pesetaValue, salaryEmployerCost, dividendYield, mortgageExtraPaymentPlanner, inflationPurchasingPower, subscriptionCostAnnualizer, loanToIncomeRatio];
